src/modules/processdef-list/processdef-list.html
> This feature changes the ProcessDef list pagination routes from `processlist` to `processdef`.
=> Add :bug: Fix ProcessDef list pagination routes

src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-detail/processdef-detail.ts
This PR adds a dropdown buttion to the processdef detail page:
- start charon
- view process def details page
- try to start a process
=> ✨ Add very fancy start button with dropdown menu to details

src/modules/processdef-detail/processdef-detail.html
=> 🐛 Disable fancy start button for now and use old /start/ route

src/modules/user-login/user-login.ts
Fixes login and logout state is not detected in navbar
- Login and logut does not change navbar menus
=> 🐛 Fix login/logout not detected in navbar

src/modules/processdef-start/processdef-start.ts
When on /start/ route and you logged in or out, the process would get started each time. Now it gets only started when you first visit the page.
Fixes #1
Goto /start/ Route and login/logout, the process should only get started once per page request.
=> 🐛 Fix #1, processes beeing started on login/logout on start page

src/modules/dynamic-ui-checkbox-element/dynamic-ui-checkbox-element.ts, src/modules/dynamic-ui-dropdown-element/dynamic-ui-dropdown-element.ts, src/modules/dynamic-ui-textbox-element/dynamic-ui-textbox-element.html, src/modules/dynamic-ui-textbox-element/dynamic-ui-textbox-element.ts
When using the new consumer client we didn't change how default values are handled this is now correct.
Fixes a regression from #29 and fixes #43.
=> 🐛 Fix #43: Default values are ignored

src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.html
=> 🐛 Fix decline button

src/modules/process-list/process-list.html, src/modules/processdef-list/processdef-list.html, src/modules/processdef-start/processdef-start.html, src/modules/processengine/processengine.repository.ts, src/modules/task-dynamic-ui/task-dynamic-ui.html, src/modules/task-list/task-list.html
- Fixes #23 
- Translates some german labels to english
=> 💄 Fix wrong/not detailed labels

src/modules/processdef-detail/processdef-detail.ts
=> changes export suffix to '.bpmn'

src/modules/processdef-list/processdef-list.html
This PR adds a start button to processdef list.
[#53](https://github.com/process-engine/charon/issues/53)
=> :sparkles: Add start-button to processdef list

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/environment.ts, src/modules/consumer-client/index.ts
This branch makes the consumer-client use the same route as configured in charons config
change charons base-route and see how the consnumer-client-requests also have a different base-route
=> 🔧 add consumer_client-config

src/app.ts, src/modules/process-list/process-list.html, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-list/processdef-list.html
=> 💄 Rename Process to ProcessInstance and ProcessDef to ProcessDefinition

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/environment.ts
This PR removes the createprocess route from the config.
=> Add :fire: Remove createprocess route from config

src/modules/process-list/process-list.html, src/modules/task-list/task-list.html
This PR adds links to task list and process instance list. 
You are now able to click on the process name/state and get navigated to the target (detail view, usertasks of an instance).
closes #24 
=> ✨ Add links for entries on task list and process instance list

README.md, aurelia_project/tasks/run.ts, package.json
When running `npm start` clicks, scroll actions, location changes and form actions are no longer sync between tabs.
Fixes #69 
- run `npm start`.
- open 2 tabs
- do stuff in one tab
- the other tab will not be synced.
=> 🐛 Disable sync features of browser sync in ghostmode

package.json
Fixes there are non ASCII charatars in a bpmn diagram, they are replaced by `?`. This is caused by a regression in `downloadsjs`. See https://github.com/rndme/download/issues/56.
Try to download a bpmn diagram with special charactars.
=> 📌 Pin downloadjs to 1.4.4 to fix Issues with non ASCII Charaters

package.json
=> 📦 Add Missing Files Section to package.json

electron_app/electron.js, index.html, package.json
Adds an electron application. First part of https://github.com/process-engine/charon/issues/77
- `npm run electron`
=> ✨ Add Basic Structure for Electron Application

aurelia_project/aurelia.json, package.json, src/app.html, src/app.ts, src/modules/processdef-list/processdef-list.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts, src/modules/waiting-room/waiting-room.html, src/modules/waiting-room/waiting-room.scss, src/modules/waiting-room/waiting-room.ts, src/resources/images/rolling.svg
This Branch adds the "Waiting Room".
If the User proceeds a task, in any way, he won't be delegated to the Task List directly.
He will be delegated to the "Waiting Room" where Charon will listen to the "renderUserTask"-Event and "processEnd"-Event to redirect the user to the correct view.
If there is an "renderUserTask"-Event, while the user is waiting, he will be redirected to the new Task in the dynamic-ui.
If there is an "processEnd"-Event he will be redirected to the Task-List automatically.
Closes #79.
Switch to this branch and start Charon with `npm install` and `npm start`.
Now navigate to `localhost:9000`.
Create a new UserTask by starting the Create-Process. (Don't forget to put "persist" on "true")
You should be redirected to the form to enter the data and, after you clicked …
=> ✨ Make UI Flow More Intuitive

README.md
Updates the GitHub links in `README.md`
Fixes #97 
=> 💄 Update github links

package.json
This PR fixes the npm start script.
`npm start`
=> ✏️  Fix start script

package.json
Adds bootstrap fonts (glyphicons) to files array in package.json.
=> Add bootstrap fonts to files array

package.json
Upgrade @process-engine/bpmn-js-custom-bundle to 1.0.0-rc4
Run charon and see the new version of the bpmnio components
=> ⬆️ :arrow_up: Upgrade @process-engine/bpmn-js-custom-bundle to 1.0.0-rc4

src/modules/import-process-button/import-process-button.ts, src/modules/processdef-detail/processdef-detail.ts
Fixes #103 
- Save process now gives toastr notification
- Any other places where alerts were used before
=> 💄 :lipstick: Use Toastr instead of alert(..)

src/modules/processdef-list/processdef-list.html
Add missing css class to processdef list
the `draft` header should now be centered
=> 💄 :lipstick: Add missing css class to processdef list

src/modules/processdef-detail/processdef-detail.ts
Added error handling for publishDraft()
Closes #105
Start Charon, open a draft, stop the PE and try to publish draft.
It will now show a toastr message instead of throwing unhandled rejection error.
=> 🐛 Fix #105

README.md, aurelia_project/aurelia.json, bin/bpmn-studio.js, index.html, package.json, src/app.html, src/app.ts
I just renamed Charon to BPMN-Studio as wished in #131.
- 🔜 https://github.com/process-engine/process_engine_meta/pull/23
- 🔜 https://github.com/process-engine/documentation/pull/63
- 🔜 https://github.com/process-engine/consumer_client/pull/13
=> Rename Charon to BPMN-Studio

src/modules/processdef-start/processdef-start.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts, test/unit/setup.ts
This PR fixes all current `tslint` errors
- checkout
- `npm run tslint` and see no errors
=> 🚨 :rotating_light: Fix tslint Errors

package.json
Adds missing author data to package.json
Read
=> 🔧 :wrench: Add Missing Author Information to package.json

Jenkinsfile, Jenkinsfile-node-v7
tslint errors now fail the build
Make errors, commit, build fails
=> 👷 :construction_worker: tslint Errors Now Fail the Build

src/contracts/bpmnmodeler/IBpmnFunction.ts, src/contracts/bpmnmodeler/IBpmnModeler.ts, src/contracts/bpmnmodeler/IEvent.ts, src/contracts/bpmnmodeler/constants.ts, src/contracts/bpmnmodeler/index.ts, src/modules/bpmn-io/bpmn-io.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-detail/processdef-detail.ts
This branch adds the "Distribute Elements"-Functionallity to bpmn-studio.
Closes #121 
- build & start bpmn-studio
- see new dropdown in processdef-details
=> ✨ Distribute Elements Horizontal/Vertical

src/contracts/bpmnmodeler/IModeling.ts, src/contracts/bpmnmodeler/index.ts, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
This branch adds Colorfunctions to bpmn-studio, allowing the User to Color the selected Elements of a Diagramm.
Closes #138 
- checkout this branch
- build and start bpmn-studio
- go to the prozessdef-detail page (the diagramm modeler)
- click on an element and try the new color button in the upper right corner
=> ✨ Add Colors

package.json, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
This PR just upgrades jquery from `^2.2.4` to `^3.0.0` and fixes some style.
Closes #142 
- `rm -rf node_modules/`
- `npm i`
- `au run`
and see that all works correctly.
=> ⬆️ :arrow_up: Upgrade jquery, 💄 :lipstick: Fix indent

src/contracts/processengine/IProcessEngineRepository.ts, src/contracts/processengine/IProcessEngineService.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-detail/processdef-detail.ts, src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss, src/modules/processdef-list/processdef-list.ts, src/modules/processengine/processengine.repository.ts, src/modules/processengine/processengine.service.ts
This branch deletes the old versioning completely from bpmn-studio.
- start bpmn-studio
- see processdef-list and -details 
=> 🔥 Delete Versioning

aurelia_project/aurelia.json
=> copy default avatar to supposed folder

src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.scss, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.scss, src/modules/processdef-detail/processdef-detail.html, src/modules/waiting-room/waiting-room.html, src/modules/waiting-room/waiting-room.scss
This branch deletes grid and adds some minor responsiveness.
Closes #148 
- start charon
- see waiting-room and config-panel in ie11
=> Delete grid and some responsivness

package.json
Upgrade consumer client to rc5
=> ⬆️ :arrow_up: Update @process-engine/consumer_client to 1.0.0-rc5

aurelia_project/aurelia.json, package.json
=> 🐛 :bug: Add Polyfill for Proxy

src/modules/processdef-start/processdef-start.ts
This branch fixes a timing problem when rendering the dynamic ui.
- start bpmn-studio
- start "create process" a few times and see how its working
=> Fix rendering ui 

package.json, src/modules/dynamic-ui-number-element/dynamic-ui-number-element.html, src/modules/dynamic-ui-number-element/dynamic-ui-number-element.ts, src/modules/form-widget/form-widget.ts
~~⏰ Waits on https://github.com/process-engine/consumer_client/pull/16~~
Adds support for long field types in forms
Use long field typ
=> ✨ :sparkles: Add support for long from widget field type

src/modules/bpmn-io/bpmn-io.ts, src/modules/property-panel/property-panel.ts
This PR let the property-panel refresh after an import of a xml.
Closes #162 
- go to the detail-view of a processdef
- import a processdef
- look at the property-panel
=> 🐛 :bug: Refresh Property Panel After Import of New Process Definition

Jenkinsfile, Jenkinsfile-node-v7, package.json, src/modules/config-panel/config-panel.ts
Make leftover Configvariables configureable via config-panel.
- Checkout branch
- Start 2 instances of the process-engine-server (one on port 8000 and the other on 8001 for example)
- Start switching between these two and see how everything works
=> Make leftover Configvariables configurable via config-panel

src/modules/processdef-detail/processdef-detail.ts
Closes #156 
- checkout branch & start bpmn-studio
- start a process from the detail view (modeler)
- see that it's only started once
=> stop process from being started twice

src/modules/property-panel/property-panel.html, src/modules/property-panel/property-panel.scss, src/modules/property-panel/property-panel.ts
I added a label to display the id of the selected element above the dropdown.
Closes #173.
- open the BPMN-Studio
- select an element
- have a look at the property-panel
=> ✨:sparkles: Add a Label to Display the Id of the Selected Element

src/modules/processdef-detail/processdef-detail.ts, src/modules/property-panel/indextabs/extensions/extensions.ts, src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/forms/forms.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/general.html, src/modules/property-panel/indextabs/general/general.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/property-panel/indextabs/general/sections/flow/flow.html, src/modules/property-panel/indextabs/general/sections/flow/flow.ts, src/modules/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/pool/pool.ts, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/property-panel/property-panel.ts
This PR removes unnecessary code (imports/definitions) and fixes some code style.
=> 🔥 :fire: Remove unnecessary code

src/modules/bpmn-io/bpmn-io.scss, src/modules/property-panel/indextabs/extensions/extensions.html, src/modules/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/property-panel/indextabs/forms/forms.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.scss, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/general.html, src/modules/property-panel/indextabs/general/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/property-panel/indextabs/general/sections/flow/flow.html, src/modules/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/pool/pool.scss, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/property-panel/property-panel.html, src/modules/property-panel/property-panel.scss, src/modules/property-panel/styles/registers.scss, src/modules/property-panel/styles/sections.scss
This branch refactors the css of the Property Panel
=> 💄Rework css of Property Panel

src/modules/dynamic-ui-textbox-element/dynamic-ui-textbox-element.html, src/modules/dynamic-ui-textbox-element/dynamic-ui-textbox-element.scss, src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.scss
This branch improves the css of the dynamic ui. 
- Checkout branch & start BPMN-Studio.
- Create a process and see the rearranged input fields.
=> Add minor css enhancement in dynamic Ui

src/modules/property-panel/indextabs/general/sections/flow/flow.ts
The condition of the flow did not get displayed correctly when not changed.
- Run BPMN-Studio
- Click on any flow connected to a gateway
- Have a look at the Condition-Textbox
- Notice that it's empty whether it should or not
=> 🚑 :ambulance: Fix Loading the Value of a Flow Condition

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/contracts/bpmnmodeler/constants.ts, src/environment.ts, src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/property-panel/styles/sections.scss
This PR adds a resize function for the propertypanel and has also a small style fix for form-controls.
- `au run`
- click the `resize` button and move your mouse for resizing the propertypanel
- click again to set the size
=> ✨ :sparkles: Add resizing

src/contracts/bpmnmodeler/IBpmnModdle.ts, src/contracts/bpmnmodeler/IElementRegistry.ts, src/contracts/bpmnmodeler/IIds.ts, src/contracts/bpmnmodeler/ISeed.ts, src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts, src/contracts/bpmnmodeler/index.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.scss, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/pool/pool.ts
This PR adds a feature to check whether an ID or Process-ID is unique.
If not, you cannot safe and a warning appears.
Fixes #163 
1. Checkout the branch.
2. npm install
3. au run --watch
4. Open a diagram, open an element and type an existing Id
5. A warning should appear inside the ID field.
Same for Process ID.
=> ✨:sparkles: Check Unique Ids

debugging_electron.md
I added hints and infos about debugging an electron application.
See if you can now debug your electron application
=> 📝 Add Electron Debugging Notes

src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.ts
This branch fixes a minor bug in pagination. 
=> Fix Pagination

src/modules/task-list/task-list.html, src/modules/task-list/task-list.scss, src/modules/task-list/task-list.ts
This branch adds a loading spinner to the Tasklist to indicate if the task lists are still loading or not.
- Checkout branch 
- `au run`
- Create a process with a usertask and start it some times
- Navigate to the tasklist and you can shortly see the loading spinner doing it's job
=> ✨Loading Spinner For Tasklist

src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-detail/processdef-detail.ts, src/modules/property-panel/indextabs/general/repository/general.repository.ts, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.scss, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/property-panel/indextabs/general/service/general.service.ts
This branch adds the possibility to navigate directly to the called Process when using a Call Activitiy.
Closes #192 
Closes #60 
- Checkout this branch & start bpmn-studio
- Create a new process and use a call activity
- See the changes in the property panel section for call activities
=> ✨Call Activity Navigation

src/modules/process-list/process-list.html, src/modules/process-list/process-list.scss, src/modules/process-list/process-list.ts, src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss, src/modules/task-list/task-list.html, src/modules/task-list/task-list.scss
This branch adds a loading spinner to the process-instance-list.
- Checkout branch
- `au run`
- Create a process with a usertask and start it some times
- Navigate to the process instance list and you can shortly see the loading spinner doing it's job
=> ✨Loading Spinner for process instance list

src/contracts/bpmnmodeler/IBpmnModeler.ts, src/contracts/bpmnmodeler/IModeling.ts, src/contracts/bpmnmodeler/IShape.ts, src/contracts/bpmnmodeler/bpmnElements/IError.ts, src/contracts/bpmnmodeler/bpmnElements/IEscalation.ts, src/contracts/bpmnmodeler/bpmnElements/IMessage.ts, src/contracts/bpmnmodeler/bpmnElements/IProcessRef.ts, src/contracts/eventbus/IEventBus.ts, src/contracts/propertypanel/ISection.ts, src/modules/property-panel/indextabs/extensions/extensions.ts, src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/forms/forms.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/general.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/property-panel/indextabs/general/sections/flow/flow.ts, src/modules/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/pool/pool.ts, src/modules/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/property-panel/property-panel.html, src/modules/property-panel/property-panel.ts
This branch will add all codestyle changes from https://github.com/process-engine/bpmn-studio_property-panel/pull/1
=> Code Style Rework

electron_app/electron.js
This branch adds a menu to the electron app. This enables the user to use functions like cut, copy and paste.
- Checkout branch
- `npm install && npm run electron-start-dev`
This will start the electron app in a dev setup. You will be able to paste something into all input fields of BPMN-Studio.
=> ✨Add Menu to Electron App

package.json
- :arrow_up: Update bpmn-studio_client to 2.0.0
=> :arrow_up: Update bpmn-studio_client to 2.0.0

src/app.scss
This PR adds a small stylefix.
before:
after:
checkout the branch and start bpmn-studio, then move to the xml view of a processdef and scroll down.
=> :art: Fix baseroute style

src/modules/waiting-room/waiting-room.html
This branch just alters some texts in the waiting-room to make it more intuitive.
Closes #224 
Start the studio and go to http://localhost:8080/#/waitingroom/anything
=> ✨Make waiting room more intuitive

README.md
This PR adds information into the ```README.md``` on how to build the electron application and where to download the BPMN-Studio releases.
Fixes #215 
You can read the README.md file to see whether everything looks fine.
=> 📝 Update Documentation for Electron-App

src/modules/processdef-list/processdef-list.html, test/e2e/src/pages/processdef-list-page.ts, test/e2e/src/processDefList.spec.ts
This branch adds a simple navigation test for protractor.
Closes #226 
- checkout this branch
- run `npm run integration-test-init`
- open another terminal in the bpmn-studio folder
- run `au run`
- open another terminal in the bpmn-studio folder
- run `au e2e`
- tests should be running
=> Add simple navigation test for protractor

README.md
Correct spelling and change text to german.
=> :sparkles: Correct Spelling; Germanify

src/modules/processdef-detail/processdef-detail.ts
Fixes #232 
- Open Diagram
- Click export
- xml should be formatted
=> :bug: Format BPMN XML Before Exporting. Closes #232

.ci-tools/publish-github-release.js, Jenkinsfile, electron_app/electron.js
- Every commit gets its own version
- Versions on master will be releases
- Versions on develop will be prereleases
n/a
=> :construction_worker: Improve Release Process by Releasing Every Version

.ci-tools/publish-github-release.js, Jenkinsfile
Fixes issues wth filenames
n/a
=> :construction_worker::ambulance: Fix Filename in Buildpipeline

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, electron_app/electron.js, src/contracts/processengine/IProcessEngineRepository.ts, src/contracts/processengine/IProcessEngineService.ts, src/environment.ts, src/main.ts, src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss, src/modules/processdef-list/processdef-list.ts, src/modules/processengine/processengine.repository.ts, src/modules/processengine/processengine.service.ts
This PR adds an import BPMN button to the processdef-list.
Closes #159 
- `au run`
- import a BPMN file 
=> ✨Feature/add importprocess button

.ci-tools/publish-github-release.js
Release bodies are now auto generated by github
n/a
=> :fire:(:construction_worker:) Remove Body From Releases

.ci-tools/publish-github-release.js, Jenkinsfile, electron_app/electron.js
- Set Package Version Before Building Binaries
- Fixes wrong update channel in bpmn studio
=> :construction_worker: Set Package Version Before Building Binaries

src/modules/property-panel/property-panel.scss
Use overflow: auto instead of scroll in property panel to solve inconsistent behavior.
Open a diagram and add properties to an element until the property panel starts to scroll.
=> 🐛Fix overflow at Property Panel

src/contracts/bpmnmodeler/bpmnElements/IFlowElement.ts, src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts, src/modules/property-panel/indextabs/general/sections/flow/flow.ts
This PR handles default-flows correctly. Closes #269 
Also it fixes a small bug with the condition value.
- `au run`
- click on normal flows, and then default-flows and see that you have no condition on the property panel
=> ✨ 🐛 Add Feature/fix condition on flow

electron_app/electron.js, src/modules/bpmn-io/bpmn-io.ts
This PR adds the basic function described in #231
Closes #231 
- start bpmn-studio 
- navigate to detail view of a process
- select an element with mouseclick or select all with `cmd+a`
- use `cmd+c` to copy
- move the mouse and use `cmd+v` to paste the element(s)
- undo it with `cmd+z`
- redo it with `cmd+shift+z`
=> ✨ :sparkles: Add basic functions to modeler and electron

.ci-tools/publish-github-release.js, Jenkinsfile, electron_app/electron.js, package.json
=> 👷 Change Prerelease Version Tags

src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts, src/contracts/bpmnmodeler/bpmnElements/ITimerElement.ts, src/contracts/bpmnmodeler/bpmnElements/index.ts, src/modules/property-panel/indextabs/general/general.ts, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.html, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.ts
This PR adds TimerEvent support to the PropertyPanel
Closes #248 
- `au run`
- add a timer boundary event to your diagram and set date, duration or cycle with the property panel
=> ✨ Add Feature/add timer event

README.md, debugging_electron.md
The readme needed a little attention.
1. Add a TL;DR Section
1. Restructuring
1. Add me to Email List
=> :books: Improve Readme

src/main.ts
Closes #261 
- start bpmn-studio
- disable cookies for the origin url
- reload the tab and see an error on the dev tools
=> ✨ :sparkles: Throw Error if Cookies are not Enabled

src/modules/bpmn-io/bpmn-io.ts
This PR fixes the resize function on firefox.
Closes #266 
- start bpmn-studio 
- open it with firefox
- try to resize the property panel on a processdef detail view
- also test it with chrome and safari
=> 🐛:bug: Fix resize function on firefox

src/contracts/processengine/IProcessEngineRepository.ts, src/contracts/processengine/IProcessEngineService.ts, src/modules/notification/notification.service.ts, src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss, src/modules/processdef-list/processdef-list.ts, src/modules/processengine/processengine.repository.ts, src/modules/processengine/processengine.service.ts
A user can now choose a name for the process definition he is importing.
Instead of simply overwriting process definitions with the same name as the process definition to be imported, the user can now set a different name or intentionally overwrite the existing process definition.
- Add Select Own Name On Import
- Add Name Selection Modal
- Add Overwrite Confirmation Modal
- Add Name Suggestion
- Format Code of ProcessDef-List
- Fix Private Names
- Sort Imports and Members
- Refactor ProcessSolutionPanel
- Cleanup & Beautify CSS
- Improve CSS Classes for ProcessDef-List Buttons
- Prettify CSS and HTML of ProcessSolutionExplorer
- Refactor CSS of ProcessDef-List
- Style HTML of ProcessDef-List
- Replace Glyphicons With Font Awesome Icons
- Use Correct Icon for Importing and Exporting
- Add …
=> ✨ Add Select Name On Import

src/modules/processdef-list/processdef-list.ts
Negation was falsely refactored. This fixes it.
Build and test the import function; the import should no longer autmomatically overwrite the file.
=> :bug: Use Correct negation

Jenkinsfile
Only Build Electron Application on master and develop
=> 👷 :construction_worker: Only Build Electron Application on master and develop

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/app.scss, src/environment.ts, src/main.ts, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.ts
This PR renames the `baseRoute` to `processEngineRoute`
Closes #287 
=> 🎨 Rename baseRoute to processEngineRoute

electron_app/electron.js, package.json, src/main.ts
- Upgrades the @process-engine/skeleton-electron dependency to 2.0.0
- Catch any errors during startup and display notification
⏰ Depends on https://github.com/process-engine/skeleton/pull/46
Build and see that the `Import process` function is working.
See https://github.com/process-engine/bpmn-studio/pull/294
=> :arrow_up: Update @process-engine/skeleton-electron to 2.0.0

electron_app/electron.js, src/app.scss, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.scss, src/modules/process-list/process-list.scss, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/conditional-event/conditional-event.html, src/modules/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/property-panel/indextabs/general/sections/flow/flow.html, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.html, src/modules/property-panel/property-panel.scss, src/modules/property-panel/styles/sections.scss, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss, src/modules/status-bar/status-bar.ts, src/modules/task-list/task-list.scss, src/modules/user-login/user-login.html, src/modules/user-login/user-login.scss
This branch:
- Fixes Paddings between the navbar, panels and so on.
- Deletes the outline for :active pseudoclass.
- Deletes the bootstrap styles for the property panels.
- Deletes the hover effect on nav- and sidebars.
- Decreases the Paddings on the sidebar-icons.
- Moves the settings button from the top left corner to the statusbar.
- Deletes the image from the account-box.
- Moves the save-, export-, etc. buttons to the left of the account-box.
- Removes some padding on the navbar.
- Deletes the default frame from the electron app and adds the native macos buttons to the navbar.
Open BPMN-Studio in electron dev.
=> ♻️ Refactor Theme

src/modules/user-login/user-login.html, src/modules/user-login/user-login.scss
=> :bug: Fix left-hand tools

electron_app/electron.js
I replaced two comments in the `electron.js` that asked for some explanation of what is happening with the requested explanation
The functionality didn't change. All you can do is read the comments that were added
=> 💡 Answer TODOs

src/modules/bpmn-xml-view/bpmn-xml-view.scss
This branch polishes the XML View.
Look at XML View.
=> 💄Polish XML View

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/environment.ts, src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-list/processdef-list.ts
This PR refreshs the Process Solution Panel when the backend route has changed.
Also the Process Solution Panel is scrollable now.
Closes #315 
- start bpmn-studio as electron app
- open the process solution explorer
- connect to another ProcessEngine
- see that the process solution panel is refreshed
=> :bug: Auto Refresh Process Solution Panel

src/main.ts
Link to Issue #316 When Internal ProcessEngine Fails to Start
- make internal processengine fail to start
- view notification
=> :sparkles: Link to Issue #316 When Internal ProcessEngine Fails to Start

src/modules/processdef-detail/processdef-detail.ts
This PR fixes the statusbar when the process is changed via the Process Solution Explorer, the Back-Button or the Call Activity.
Fixes #413 
- Go to the Detail View of any ProcessDefinition
- Change the ProcessDefinition via the Process Solution Explorer, the Back-Button or a Call Activity
- Notice that the statusbar gets updated
=> 🐛 Fix Update Statusbar on Process Change

src/modules/bpmn-io/bpmn-io.scss
This PR sets the size of the left toolbar to a fixed width.
Fixes #418 
- Resize the Browser Window
- Notice that the Size of the left toolbar will not change while resizing anymore
=> 🐛 Fixed Width for Toolsbars

README.md
This PR replaces the `npm run electron-build` command in the TL;DR part, because it is no longer existing.
- Have a look at the Readme
=> 📝 Fix TL;DR Part of Readme

src/contracts/colorpicker/IColorPickerSettings.ts, src/contracts/colorpicker/index.ts, src/contracts/index.ts, src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/diagramm-tools-right/diagramm-tools-right.html, src/modules/diagramm-tools-right/diagramm-tools-right.scss, src/modules/diagramm-tools-right/diagramm-tools-right.ts
This branch moves the functionality of the left toolbar into a new component thats placed above the property-panel.
Switch to this branch.
User au run to start BPMN-Studio.
Now navigate to locahost:9000.
Open the "detail-view" and see the new buttons above the property panel.
Closes #381, #380, #379, #378 
=> ♻️Refactor Left Toolbar

src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/process-solution-panel/process-solution-panel.ts
This PR refactors the CSS and HTML of the "process-solution-panel"-component.
Closes #345, #343
=> ♻️Refactor Process Solution Explorer

src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss, src/modules/status-bar/status-bar.ts
This PR refactors the CSS and HTML of the "status-bar"-component.
Closes #368, #435 
=> ♻️Refactor Statusbar

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/environment.ts, src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.scss, src/modules/diagram-tools-right/diagram-tools-right.html, src/modules/diagram-tools-right/diagram-tools-right.scss, src/modules/diagram-tools-right/diagram-tools-right.ts, src/modules/navbar/navbar.ts, src/modules/processdef-detail/processdef-detail.ts, src/modules/status-bar/status-bar.html
This PR only renames `Diagramm` `Diagram`
- start bpmn-studio
=> :art: Rename Diagramm to Diagram

src/modules/bpmn-io/bpmn-io.html
This PR fixes #347 
Closes #347 
- open the detail view of a process
- click on show xml 
=> :sparkles: Hide the left toolbar when the XML-View is shown

src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts
This branch only places the resize div correctly
Try to resize the property-panel.
Closes #439 
=> 🐛Place Resize Div Correctly

src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts, src/modules/user-login/user-login.html, src/modules/user-login/user-login.scss, src/modules/user-login/user-login.ts
This PR fixes the bug that occurs when changing the backend while logged in. 
Also it fixes #382 
Fixes #427
Closes #382 
See also https://github.com/process-engine/bpmn-studio/issues/455
- Checkout the branch & start bpmn-studio
- Login
- Change the backend route via settings
- See that the user is logged out
=> :sparkles: Logs out the user, when changing the backend route

src/app.scss, src/modules/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/property-panel/indextabs/general/sections/conditional-event/conditional-event.html, src/modules/property-panel/indextabs/general/sections/conditional-event/conditional-event.ts, src/modules/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/property-panel/indextabs/general/sections/flow/flow.html, src/modules/property-panel/indextabs/general/sections/flow/flow.ts, src/modules/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/pool/pool.ts, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.html, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.ts
This branch:
- Refactors the Code-Style of Property Panel.
- Deletes all green "ok"-symbols.
- Removes all remove "x"-buttons from property-inputs.
- Redesigns the remove buttons for extensions slightly.
Open a diagram in detail-view.
Closes #325 
Closes #324 
Closes #323 
=> ♻️Refactor Property Panel

src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/property-panel/property-panel.scss
This branch will move all tools from the diagram-canvas to the left toolbar.
Open a diagram in detail-view.
Closes #337 
Closes #336 
Closes #438
=> ✨Use Custom Tool Palette

src/modules/processdef-list/processdef-list.ts, src/modules/processengine/processengine.service.ts
This PR adds the "Select Own Name" functionality to the file association.
- Run Electron app
- Import file via file association
- Notice that you can choose the name for the new Diagramm
=> ✨ Add "Select Own Name"-Functionality to File Association

src/modules/navbar/navbar.scss, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/styles/sections.scss
This PR replaces the `cursor: not-allowed` to `cursor: default`.
Closes #440 
=> :art: Remove not-allowed cursor

src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss, src/modules/status-bar/status-bar.ts
Use Font Awesome icon instead of "Connected to: ".
| Before: | After: |
| ------- | ------ |
| <img width="191" alt="string" src="https://user-images.githubusercontent.com/20394992/40612263-1841c9de-627a-11e8-9ce2-7604d802100d.png"> | <img width="119" alt="lock" src="https://user-images.githubusercontent.com/20394992/40615890-05260540-6289-11e8-820d-1c51aefb9bfa.png"> |
Closes #367 
- Have a look at the left side of the statusbar
=> 💄 Use Icon Instead of 'Connected to: '

src/modules/bpmn-io/bpmn-io.html
This PR hides all tools from the left toolbar
- npm run build
- npm electron-start-dev
- switch to the xml view of a process
=> :bug: Hide all tools on left toolbar

Jenkinsfile, package.json
- Install build dependencies on each platform
- Rebuild native dependencies on each platform
- Dont build web application twice
- Add npm scripts for each new task
Checkout the build 🎉 
=> 👷 Cleanup Build Process

src/contracts/bpmnmodeler/IEditorActions.ts, src/contracts/bpmnmodeler/IKeyboard.ts, src/contracts/bpmnmodeler/index.ts, src/modules/bpmn-io/bpmn-io.ts
This PR fixes #352 
- open detail-view of a process
- select one or more elements/shapes
- click backspace and see that they are deleted
=> ✨Remove elements with backspace

src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts
This PR fixes #476 
- `au run`
- open the settings view (config-panel)
- see that there isn't a logout warning below the input field
- also open the settings view when you are logged in
- see the logout warning 
=> ✨ Show logout warning only when logged in

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/contracts/bpmnmodeler/IBpmnModeler.ts, src/environment.ts, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-detail/processdef-detail.ts, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/status-bar/status-bar.ts
This branch adds a basic modal-dialog that asks the user if he/she wants to save the diagram if changes were made to the diagram.
Fixes #362 
Fixes #363 
Fixes #364 
Fixes #365 
Fixes #366 
Fixes #478
- Open a diagram.
- Make a change to it, like moving a shape from a to b.
- Try to open another diagram via the process solution explorer.
=> ✨Add Saving Diagram Dialog

aurelia_project/aurelia.json, aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, package.json, src/contracts/bpmnmodeler/ICanvgOptions.ts, src/contracts/bpmnmodeler/index.ts, src/environment.ts, src/modules/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts, src/modules/processdef-detail/processdef-detail.ts
This PR adds printing functionality for the diagrams.
Also the exported PNG and JPEG images now look a lot better.
Fixes: https://github.com/process-engine/bpmn-studio/issues/372
- Open BPMN-Studio
- Go to the detail view of any process definition
- Click on the print icon
- Print your diagramm
=> ✨ Add Print Functionality

src/modules/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.scss
Before:
After:
- `au run`
- click on an element
=> 💄 Improve the width of input fields on extensions

package.json
This should fixes these build errors:
```
Error: Cannot find module 'aurelia-dependency-injection'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/lib/jenkins/workspace/re_improve_properties_style-NG7MBEF2B2PKFRIPA6QEAQINI47W26DCTN2QDPHUHE77H5N4V5XA/node_modules/aurelia-cli/lib/cli.js:3:19)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```
- chekout the branch
- `rm -rf node_modules`
- `npm i`
- `au run`
=> 🐛📌 Use aurelia-dependency-injection v1.3.0

src/modules/processdef-detail/processdef-detail.ts, src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/property-panel/indextabs/general/sections/conditional-event/conditional-event.ts, src/modules/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/property-panel/indextabs/general/sections/flow/flow.ts, src/modules/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/pool/pool.ts, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.ts
This branch will update every section of the property-panel to publish the "diagram change" event.
Open a diagram and change the properties of it.
See how the save diagram dialog opens if you want to leave without saving.
Closes #488 
Closes #486
=> ✨Update Property Panel For Diagram Change Feature

src/modules/navbar/navbar.html
This PR fixes the position of the print button when the browser window is very small.
Fixes #499
- Go to the Detail View of any process definition
- Resize the browser window
=> 🐛 Fix Position of Print Button

package.json
Removes the package because aurelia fixed the bug with version 1.4.1
- `rm -rf node_modules/`
- `npm i`
- `au run/npm run build`
=> 🔥 Remove aurelia-dependency-injection

src/modules/navbar/navbar.html, src/modules/navbar/navbar.scss, src/modules/navbar/navbar.ts
- Make the process diagram name dropdown clickable
- Imcrease the size of the click target
Fixes #341
Fixes #446
- Click on the process diagram name in the status bar
- Click on the dropdown
=> 💄 Improve Process Diagram Name Dropdown

package.json, src/modules/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.ts
- Update bpmn-io_custom_bundle
- Remove old MiniMap Styling
Closes #462 
Closes #351 
- `npm install`
- `au run`
- open detail view of a process
=> 🔥⬆️ Remove old MiniMap styling & Update bpmn-io_custom_bundle

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/contracts/colorpicker/IColorPickerColor.ts, src/contracts/colorpicker/index.ts, src/environment.ts, src/modules/diagram-tools-right/diagram-tools-right.html, src/modules/diagram-tools-right/diagram-tools-right.scss, src/modules/diagram-tools-right/diagram-tools-right.ts, src/modules/processdef-detail/processdef-detail.scss
This PR improves the style of the color selection and the colorpicker to make its look adapt to that of the BPMN-Studio.
Also the glyphicons got replaced by font awesome icons.
Closes #442
- Have a look at the color selection and the colorpicker
=> 💄 Improve Style of Color Selection and Colorpicker

src/modules/bpmn-io/bpmn-io.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
This PR adds a simple validation before the actual saving of the diagram in the `saveDiagram()` Method of the _processdef-detail_ module.
Related Feature: #502
Fixes #507
=> Check if the diagram is valid before saving

src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts
This PR fixes #490 
- start bpmn studio
- try to reproduce the issue
=> 🐛Fix multiple extension properties bug

src/modules/bpmn-io/bpmn-io.ts
This PR fixes an issue, that the filetypes where missing when exporting a diagram. 
=> Fix missing filetypes when exporting a diagram

src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts
Closes #533 
Closes #528 
See #533 
=> 🐛Fix Deletion of Properties

src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/status-bar/status-bar.html
This PR fixes some style bugs of the SolutionExplorer and the Statusbar.
Fixes #537 
- see that the style bug described in #537 is fixed 
=> 🎨 Fix Style in SolutionExplorer and Statusbar

src/modules/bpmn-io/bpmn-io.ts
This PR fixes getting the xml on attach.
Now the incomparable check should work as expected.
- Open any diagram via the solution explorer
- Go to the diff view
- Notice that the change list now says "The diagrams are identical." instead of "The diagrams are incomparable."
=> 🐛 Fix Getting SavedXml on Attach

src/modules/bpmn-io/bpmn-io.scss, src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss
=> 💄 SolutionExplorer Layout Fix

src/modules/property-panel/indextabs/extensions/sections/process/process.ts, src/modules/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.ts
This PR fixes the saving of a message on an error-event.
- `au run`
- create a diagram with an error boundary event on a task
- add a new error and write sth. into the message input field
- save the diagram and reload it
- see that the message is saved when selecting the error event
=> 🐛Fix Saving Bug on Error-Event

src/modules/bpmn-io/bpmn-io.scss, src/modules/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/property-panel/indextabs/extensions/sections/process/process.scss, src/modules/property-panel/indextabs/forms/sections/basics/basics.scss, src/modules/property-panel/styles/sections.scss
This PR adds a hover effect to the following 4 css-classes (elements):
1. key-value-delete-button ('x'-buttons in property panel)
1. add-context-button ('+'-buttons in property panel)
1. remove-context-button (trash-button in property panel)
1. menu-bar__menu-left--tool (toggle property panel button)
This PR also fixes the order of the css classes in section.scss.
Fixes: #559
- Tab through the property panel
- Notice that the buttons in focus are now highlighted
=> 💄 Add Hover Effect on Focus

src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss
- Fix the width issue of the solution headlines.
- Fix the cursor style for the solution explorer
- Open up the BPMN-Studio Application
- Open the Solution Explorer
- Add a solution with a really long name
- Notice that the headline will no longer wrap into a multiple line
- Hover over the "Opened Diagramms", "Opened Solutions" and the headline of the solutions
- Notice that the default cursor is used instead of the text cursor
=> 💄 Fix Style of solution-headline & Cursor Style of Solution Explorer

src/app.scss, src/modules/bpmn-diff-view/bpmn-diff-view.scss, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-xml-view/bpmn-xml-view.scss, src/modules/diagram-detail/diagram-detail.scss, src/modules/diagram-tools-right/diagram-tools-right.scss, src/modules/navbar/navbar.scss, src/modules/process-list/process-list.scss, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-list/processdef-list.scss, src/modules/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.scss, src/modules/status-bar/status-bar.scss, src/modules/task-list/task-list.scss, src/modules/user-login/user-login.scss, src/modules/waiting-room/waiting-room.scss
This PR refactors the css part of the bpmn-studio modules.
Only the order of the css rules has been changed, so it should has no effect.
Fixes #288 
=> ♻️Refactor BPMN-Studio CSS

src/modules/processdef-list/processdef-list.ts
**Changes**:
- Reset selected files input after loading file
- Open firefox
- import bpmn
- import bpmn (did fail before this pr)
=> 🐛 :bug: Fix Multiple Imports Not Working

src/modules/process-solution-panel/process-solution-panel.html
This PR fixes the accept attribute for the process solution explorer.
- Open up the BPMN-Studio (Application)
- Open the Process Solution Explorer
- Open the filesystem tab
- Try to add a .bpmn or .xml file
- Notice that .bpmn and .xml files can be added
=> 🐛 Fix Accept Attribute For Process Solution Explorer

src/modules/processdef-list/processdef-list.ts, src/modules/processengine/processengine.repository.ts
**Changes**:
- Remove route dependency in processengine repository.
- Navigate after import is now handled inside the import function.
- Check if the import button still works
=> 🎨 :art: Remove Router Dependency In ProcessEngine Repository

src/modules/processdef-list/processdef-list.html
**Changes**:
- Add missing accept types to process import button
PR: #597 
Read
=> :bug: Add Missing Accept Types to Process Import Button

package.json, src/main.ts, src/modules/fetch-http-client/HttpFetchClient.ts, src/modules/fetch-http-client/index.ts, src/modules/management-api_client/index.ts
**Changes**:
- Extract HttpFetchClient into class.
- Implement IHttpClient interface.
=> :sparkles: Add HttpFetchClient for Management API

src/modules/authentication/authentication.service.ts, src/modules/config-panel/config-panel.ts, src/modules/processdef-list/processdef-list.ts
This branch:
- Shows a proper way to guard routes in aurelia. See example in process-def-list.
- Refactors the config-panel.
Try to navigate to the process-def-list when not logged in and when logged in.
Change between different PEs freely using the config-panel.
=> ✨Show proper way to guard routes & refactor config-panel

src/modules/dashboard/dashboard.html, src/modules/dashboard/dashboard.ts, src/modules/process-list/process-list.html, src/modules/task-list/task-list.html, src/modules/task-list/task-list.ts
**Changes:**
- Implement access checks for dashboard.
=> :sparkles: Implement Access Checks For Dashboard

src/modules/bpmn-io/bpmn-io.ts
This fixes updating the xml before opening the xml view.
Fixes: #652 
- Add changes
- Check the xml view
=> 🐛 Fix Updating Xml Before Opening XmlView

electron_app/electron.js
**Changes**:
- Only start one internal processengine.
PR: #663 
=> :bug: Dont Create Multipe Internal ProcessEngine Instances

src/modules/process-solution-panel/process-solution-panel.ts
**Changes**:
- Bump solutionexplorer management repository to 0.0.2.
- Add error handling for authentication errors.
PR: #655 
=> :bug: Fix Access Checks of Solution Explorer

src/modules/config-panel/config-panel.ts
**Changes**:
- Use the localstorage entry if set.
PR: #665 
=> :bug: Prefer LocalStorage Entry if Set in Config Panel

src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.ts, src/modules/dynamic-ui/dynamic-ui.service.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts
**Changes**:
- Remove usages of NewAuthenticationService that were missed.
PR: #666 
=> :bug: Correct Some Missed Usages of NewAuthenticationService

src/modules/diagram-detail/diagram-detail.ts
**Changes**:
- Displays an error message if the diagram upload fails.
PR: #674 
=> :sparkles: Display Error If Diagram Upload Fails

src/modules/diagram-detail/diagram-detail.ts, src/modules/process-solution-panel/process-solution-panel.ts
**Changes**:
- Display notification after successfull upload.
- Fire refresh processdef event after upload.
- Listen for event and refresh solution explorer.
PR: #688 
- Checkout + build
- Run electron app
- Upload process
- See notification if success
- Switch to solutionexplorer for PE (fast)
- New processmodel is already there.
=> :sparkles: Refresh ProcessModels After Upload

src/modules/waiting-room/waiting-room.ts
This PR fixes the polling of the waiting room.
- Go to the Detail View of any diagram with user tasks
- Navigate to another view while in waiting room
- Notice that user tasks will no longer be shown
=> 🐛 Fix Polling of Waiting Room

src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss
This PR removes the details button from the plan view.
- Have a look at the Plan View
=> 🔥 Remove Details Button

package.json, src/modules/process-solution-panel/process-solution-panel.ts
This PR Fixes #700 
* Start BPMN Studio
* Open the DevTools
* Toggle the solution explorer pane
=> Fix collapsing of the Solution Explorer

package.json
This branch fixes the postinstall so the internal PE works again.
Start the BPMN-Studio with `npm run electron_start_dev`
=> 🐛Fix Postinstall

src/main.ts, src/modules/config-panel/config-panel.ts, src/modules/management-api_client/index.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/status-bar/status-bar.ts
This branch makes BPMN-Studio start with correct internal PE route every time.
Start BPMN-Studio and see that the correct route is configured at the start.
Closes #694 
=> 🐛Make BPMN-Studio start with the correct route

src/modules/diagram-creation-service/DiagramCreationService.ts
This PR adds a start- and an endevent to the diagram that gets created by the diagram creation service.
- Open up the BPMN-Studio (Electron Application)
- Open the Solution Explorer
- Add a folder
- Add a new file
- Have a look at the created diagram
=> ✨ Add Start- And Endevent to Diagram Creation Service

src/modules/dashboard/dashboard.ts
* removed the erroneous fetch calls
* left a TODO comment for the poor claim check
=> Fix undefined route params

src/modules/authentication/authentication.service.ts
* added a method to `AuthenticationService` to validate if IdentityServer is online
* show custom notification after login is clicked if IdentityServer is offline
Try to login without an IdentityServer.
=> Show notification if identity server is offline

package.json
* updated the skeleton-electron
=> Update skeleton-electron to 6.0.8

src/modules/property-panel/indextabs/forms/forms.ts
This branch fixes the model binding on formsections.
Click on a usertask in any diagram und then click outside the diagram.
See how no warning is thrown now.
=> 🐛Fix activate in forms sections

src/modules/config-panel/config-panel.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.ts
This PR fixes the unique id validation for the collaboration.
The problem was that the id of the collaboration was compared with itself, so that it could never be unique
- Change Collaboration Id
- Notice that it is now changable
=> 🐛 Fix Unique Id Validation For Collaboration

src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.scss, src/modules/processdef-detail/processdef-detail.ts
This PR fixes #707 and reenables the _Save before run_ Dialog. 
* Load a diagram
* Make some changes
* Start the Process
=> Fix overlapping Modals

src/modules/diagram-detail/diagram-detail.html, src/modules/diagram-detail/diagram-detail.scss, src/modules/diagram-detail/diagram-detail.ts
This PR adds a modal if a user tries to upload a process with unsaved changes to the ProcessEngine.
* Open a solution inside the solution explorer
* Open a diagrams detail view
* Make some changes
* Click deploy
=> Show a modal when the user wants to deploy a diagram with unsaved changes

src/modules/navbar/navbar.html
This PR fixes the title in the navbar when a diagram is opened for both views, the one you see when opening a diagram from database and the one you see when opening a diagram from a solution.
- Open a diagram from the database
- Open a diagram from a solution
- Notice that in both cases the navbar has a title
=> 🐛 Fix Process Name in Navbar

src/modules/diagram-detail/diagram-detail.ts
This branch adds the validation controller to the detail view for the file system.
It disables the save button when the validation fails.
Open a process and give two elements the same id, then try to save it.
=> ✨Add errorhandling to filesystem detail-view

electron_app/electron.js, src/main.ts
This PR quits the app if all windows are closed.
Also it shows a notification for windows user that the auto updater is currently broken.
#715
=> ✨Disable Autoupdater on Windows and show Notification

src/modules/process-solution-panel/process-solution-panel.scss
Reverts process-engine/bpmn-studio#740
=> Revert "🎨 Make the diagram close button black when hovering"

src/modules/status-bar/status-bar.html
- Add some missing tooltips
- Open the diff view
- Hover over the 'After vs. Before' and 'Before vs. After' Buttons
- Notice the tooltips
=> ✨ Add Tooltips to Diff View

Jenkinsfile
=> Remove windows and linux buildstep

Jenkinsfile, dev_tooling/scripts/build_clean_setup.bash
=> 🐛Fix Resetscript on .citools dir

Jenkinsfile
=> ✨ Enable windows and linux build

Jenkinsfile
=> 🔥 Remove reset script from windows build

src/modules/process-solution-panel/process-solution-panel.ts
This branch fixes the solution call on the solution-explorer
Start BPMN-Studio
=> 🐛Fix Solution Call

src/modules/navbar/navbar.scss
Fixes #741 
* Start BPMN Studio
* Click at Plan
* Hover the active Plan Element
=> 🐛🎨Fix Wrong Text Decoration at the Menu Bar

.github/PULL_REQUEST_TEMPLATE.md
=> ✨💄 Update Pull Request Template

PULL_REQUEST_TEMPLATE.md
Reverts process-engine/bpmn-studio#761
=> Revert "✨💄 Update Pull Request Template"

Jenkinsfile
**Changes:**
- Dont run faulty reset script on Jenkins to prevent cache corruption.
PR: #766 
<details>
<summary>
<b>Merge information</b>
</summary>
Please use `:twisted_rightwards_arrows:` at the beginning of your commit title.
Example: 
<pre>
<code>
</code>
</pre>
Example:
<pre>
<code>
**Changes:**
- ...
Fixes: #NumberOfFixedIssue
</code>
</pre>
</details>
=> :construction_worker: Dont run Faulty Reset on Jenkins 

src/app.ts, src/contracts/file-input-event/IFile.ts, src/modules/process-solution-panel/process-solution-panel.ts
This PR adds files to solution explorer that are added via drag and drop 
Fixes #763 
- Drag a file into BPMN-Studio
- Notice that if it is a valid BPMN file it will be opened and is now shown in the Solution Explorer
=> ✨Add Drag And Drop Functionality

src/modules/form-widget/form-widget.ts
* fixed the type of bindable property `widget` on custom element `FormWidget`
Run a process with user task in BPMN-Studio.
=> Fix type annotation

dev_tooling/scripts/generate_changelog/README.md, dev_tooling/scripts/generate_changelog/generate_release_markdown_file.sh, dev_tooling/scripts/generate_changelog/get_fixed_issues.sh, dev_tooling/scripts/generate_changelog/get_merge_commits.sh, dev_tooling/scripts/generate_changelog/sort_and_format_merge_commits.sh
**Changes:**
- Add scripts to help generate changlogs.
- Add a README with knowhow on changelogs.
PR: #764 
- Read the README
- Try the scripts
<details>
<summary>
<b>Merge information</b>
</summary>
Please use `:twisted_rightwards_arrows:` at the beginning of your commit title.
Example: 
<pre>
<code>
</code>
</pre>
Example:
<pre>
<code>
**Changes:**
- ...
Fixes: #NumberOfFixedIssue
</code>
</pre>
</details>
=> :memo: Add DevTooling for Changelog Generation

src/modules/diagram-validation-service/DiagramValidationService.ts
**Changes**:
- BPMN diagrams do no longer have to contain bpmn:definitions.
Try to open a diagram without `bpmn:definitions`.
=> WIP :bug: Fix BPMN Validation

src/modules/bpmn-io/bpmn-io.ts
**Changes:**
1. Subscribes to the 'elements.paste.rejected' event.
2. Shows a helpful notification if this event gets fired.
**Issues:**
PR: #791 
Try to copy an element without moving your cursor outside of the element.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> ✨Show Notification For Paste Rejected Event

src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
This PR fixes a missing modal backdrop to make the modals more persistent. 
* Open a Diagram, which lays on a ProcessEngine
* Make some changes
* Try to leave the diagram
* look at the modal
=> 🐛Fix missing modal backdrop

package.json, protractor.conf.js, src/modules/status-bar/status-bar.html, test/e2e/src/processDefList.spec.ts, test/e2e/src/statusBar.spec.ts
**Changes:**
1. Upgrade protractor version
2. Use Jasmine 2.x
3. Add Protractor parameter (aureliaUrl, defaultTimeoutMS)
4. Add Integration test for status-bar
```shell
npm run integration-test-init
npm run integration-test
```
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✅ Status-bar protractor tests

src/app.html, src/app.ts, src/modules/navbar/navbar.ts, src/modules/process-solution-panel/process-solution-panel.ts
**Changes:**
- Makes the solution explorer show up in default when starting the app.
- Makes the solution explorer defaulting to filesystem on start on electron.
Fixes: #769 
Open BPMN-Studio on electron.
<details>
<summary>
<b>Merge information</b>
</summary>
Please use `:twisted_rightwards_arrows:` at the beginning of your commit title.
Example: 
<pre>
<code>
</code>
</pre>
Example:
<pre>
<code>
**Changes:**
- ...
Fixes: #NumberOfFixedIssue
</code>
</pre>
</details>
=> ✨ Open the SolutionExplorer on Studio Start

src/modules/dashboard/dashboard.html, src/modules/dashboard/dashboard.scss, src/modules/dashboard/dashboard.ts, src/modules/dynamic-ui-dropdown-element/dynamic-ui-dropdown-element.html, src/modules/dynamic-ui-number-element/dynamic-ui-number-element.html, src/modules/dynamic-ui-textbox-element/dynamic-ui-textbox-element.html, src/modules/task-dynamic-ui/task-dynamic-ui.html, src/modules/task-dynamic-ui/task-dynamic-ui.scss, src/modules/task-list/task-list.html, src/modules/task-list/task-list.scss, src/modules/task-list/task-list.ts
**Changes:**
Adds padding to tasklist. 
Fixes: 
#692 
#799 
Open task list, look at layout (accessible via dashboard->`User tasks` of a running process).
=> 💄 Add padding to tasklist

src/modules/bpmn-diff-view/bpmn-diff-view.ts, src/modules/status-bar/status-bar.ts
**Changes:**
1. Preselect the Diffmode "After vs. Before".
**Issues:**
This was requested by @roblen45 
PR: #800
- Start BPMN-Studio.
- Open a Diagram.
- Open Diffviewer.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details> …
=> ✨Preselect Diffmode

src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/extensions/sections/process/process.ts
---
**Changes:**
1. Remove empty extensionElements after removing the last extension property of an element
2. Fix the empty properties bug inside an processRef extensionElement (collaboration element)
3. Remove empty extensionElements after removing the last extension property of a participants  processRef of a collaboation
4. Publish a diagramChange event when changing the xml
**Issues:**
Closes #794 …
=> 🐛Fix Empty ExtensionElements and Properties

src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss, src/modules/processdef-list/processdef-list.ts
---
**Changes:**
1. Remove the Paginator from the Process defintion list.
The Paginator is just a relict of old times. Its basically without any function and can be removed.
2. Remove old CSS Classes used by the Import Process Definition Modal
The _Import Process Button_ displayed on the Process Defintion list is long gone. But the relicts are still here (in the form of CSS Classes). This PR Removes them. …
=> 🔥♻️ Remove Paginator from the Process Definition list / tidy up Processsdef-List

src/modules/navbar/navbar.scss, src/modules/start-page/start-page.scss
---
**Changes:**
1. Disables the ability to drag certain elements around.
2. Disable the selection of Elements from the start view.
---
* Start BPMN Studio
* Try to drag around the start image or Elements from the navbar
<details>
<summary>
:warning: Before merging please click here to expand and …
=> 🐛 Prevent the user from dragging around elements

package.json
**Changes:**
1. Pins the Version of "aurelia-open-id-connect" to "1.0.3" since later versions are creating compile errors.
**Issues:**
PR: #815
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at …
=> 📌Nail Down open-id-connect Version

src/modules/navbar/navbar.html, src/modules/navbar/navbar.scss, src/modules/navbar/navbar.ts
---
**Changes:**
1. Add Edited Label to Navbar When Diagram is Changed
**Issues:**
Closes #818
PR: #822
---
- **Notice the edited label in the navbar**
- Save the diagram
- **Notice that the edited label is no longer existing**
Please check the boxes in this list after …
=> ✨ Add Edited Label to Navbar When Diagram is Changed

src/modules/property-panel/indextabs/extensions/sections/process/process.html, src/modules/property-panel/indextabs/extensions/sections/process/process.scss
---
**Changes:**
1. Fix design of "process properties"-panel
**Issues:**
Closes #817
PR: #820
---
- Have a look at the "process properties"-panel in the property panel
<details>
<summary>
:warning: Before merging please click here to …
=> 💄 Fix Design of Process Properties Panel

src/modules/authentication/authentication.service.ts
---
**Changes:**
1. Fixes getting dummy token after canceled login
**Issues:**
Closes #808
PR: #824
---
- Run the IdentityServer
- Click on the login button
- Cancel the login
- **Notice that the dummy token will still be used**
<details>
<summary>
:warning: Before merging …
=> 🐛 Fix Getting Dummy Token After Canceled Login

electron_app/electron.js
---
**Changes:**
1. Fix Setting File Type on Export for Windows
2. Fix Title of Explorer Window When Exporting
3. Fix Missing File Extension on Windows
**Issues:**
Closes #647 
Closes #805 
Closes #648
PR: #825 
---
**On Windows:**
- Export the diagram
- **Notice:**
- the window title is: …
=> ♻️ Fix Download Menu On Windows

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts
---
**Changes:**
1. Decrease Polling Interval
PR: #826
---
- Run any diagram with a user task at the beginning
- **Notice how fast the user task will be rendered**
<details>
<summary>
</summary>
<br> …
=> ⚡️ Decrease Polling Interval

src/modules/process-solution-panel/process-solution-panel.html, src/modules/process-solution-panel/process-solution-panel.scss
**Changes:**
1. Remove Margin From Solution Headling
2. Add Border After Each Solution
PR: #828
---
- Add solutions and diagrams to the solution explorer
- **Have a look at the style of the solution explorer**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> 💄 Improve Style of Solution Explorer

package.json
**Changes:**
1. Update Skeleton Electron
PR: #835
---
Run:
```
npm i
npm list @process-engine/skeleton-electron
```
Output should contain:
```
└── @process-engine/skeleton-electron@6.3.0
```
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ⬆️ Update Skeleton Electron

src/contracts/bpmnmodeler/IElementRegistry.ts, src/modules/processdef-detail/processdef-detail.ts
---
**Changes:**
1. Fix a bug in the `_dropInvalidFormData()` Method from the _Processdef-detail_ Component. 
This bug leads to a _Cannot read property length of undefined_ Error when trying to save a Diagram that contains a UserTask with no defined FormFields.
2. Add a comment to describe a kinda strange behavior.
**Issues:**
Closes #771 
---
* Create a …
=> 🐛 Fix an error when trying to save a process that contains a UserTask with no FormFields 

src/modules/navbar/navbar.html
**Changes:**
1. Renames the Navbar links to "Think - Design - Inspect".
PR: #827
Start BPMN-Studio.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br> …
=> ♻️Rename Navbar Links

src/modules/navbar/navbar.ts, src/modules/process-solution-panel/process-solution-panel.ts
**Changes:**
1. Fix Not Changing the Navbar Title When Diagram Changing Was Prevented by Save Modal
2. Fix Removing Edited Flag When Diagram Was Changed
PR: #834
---
1:
- Select another diagram
- Click cancel in the save modal
- **Notice that the navbar title will no longer be changed**
2:
- Select another diagram
- Click on any of the buttons except cancel
- **Notice that the edited flag will no longer be shown**
<details>
<summary> …
=> 🐛Fix Updating Navbar When Changing Diagram

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/diagram-detail/diagram-detail.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-detail/processdef-detail.ts
---
**Changes:**
1. Always show both buttons
2. Disable the start button on filesystem view and enable the deploy button
3. Disable the deploy button on ProcessEngine view and enable the start button
4. Navigate to the ProcessEngine design view after deploy
**Issues:**
Closes #856 
Relates #788 
PR: #860 
--- …
=> ✨Show Start and Deploy Button on Filesystem and ProcessEngine

src/modules/navbar/navbar.html, test/e2e/src/navBar.spec.ts, test/e2e/src/pages/navBar.ts
**Changes:**
1. Replace old Navbar IDs
2. Remove Publish link test
```shell
npm run build
npm run start_dev
npm run integration-test-init
npm run integration-test
```
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details> …
=> ✅Align tests to renamed navbar links

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/bpmn-io/bpmn-io.ts, src/modules/diagram-tools-right/diagram-tools-right.html, src/modules/diagram-tools-right/diagram-tools-right.scss, src/modules/diagram-tools-right/diagram-tools-right.ts
---
**Changes:**
1. Disables the color picker if the user does not click on a diagram element.
**Issues:**
Closes #819 
PR: #861
---
<details>
<summary>
:warning: Before merging please click here to expand …
=> ✨Disable the color picker if the user does not select a diagram element.

dev_tooling/scripts/generate_changelog/README.md
---
**Changes:**
1. Adds a section which describes all needed requirements to run the scripts.
---
* Look at the readme
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the …
=> 📝 Add a note to install jq before running the get_fixed_issues script

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/dashboard/dashboard.ts, src/modules/process-list/process-list.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-list/processdef-list.ts, src/modules/task-list/task-list.ts, src/modules/waiting-room/waiting-room.ts
---
**Changes:**
1. Add a second polling interval for the waiting room
**Issues:**
Closes #867 
PR: #870 
---
<details>
<summary> …
=> 💄 Improve the PollingInterval for the Waiting-Room

src/modules/property-panel/indextabs/general/sections/flow/flow.ts
…s type is default
---
**Changes:**
1. Check if sourceRef of a flow is null before checking for default flow
**Issues:**
Closes #836 
PR: #869 
---
<details>
<summary>
:warning: Before merging please click …
=> 🐛 Check if sourceRef of a flow is null before checking whether its type is default

src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
---
**Changes:**
1. Only shows Modal for StartEventSelection when there is more than one StartEvent.
2. Improve dialog message.
**Issues:**
Closes #875 
---
<details>
<summary>
:warning: …
=> ♻️Only show Select-StartEvent-Modal when there is more than one StartEvent

electron_app/electron.js, package.json
**Changes:**
1. Deletes electron-skeleton dependency
2. Adds process_engine_runtime depdency
3. Let's BPMN-Studio use the runtime instead of the electron-skeleton.
**Issues:**
Closes #876 
Start BPMN-Studio and test anything.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> ✨Integrate process-engine-runtime

src/modules/bpmn-xml-view/bpmn-xml-view.scss, src/modules/bpmn-xml-view/bpmn-xml-view.ts, src/modules/dashboard/dashboard.html, src/modules/dashboard/dashboard.scss, src/modules/process-list/process-list.html, src/modules/process-list/process-list.scss, src/modules/task-list/task-list.html, src/modules/task-list/task-list.scss
---
**Changes:**
1. Eliminates side effects in task-list.
2. Eliminates side effects in dashboard.
3. Eliminates side effects in process-list.
4. Eliminates side effects in xml-view.
**Issues:**
Closes #410 
---
Start BPMN-Studio.
Open a diagram.
Navigate to the dashboard via "Inspect".
Open another or the same diagram again.
Open XML-View.
The …
=> 🐛Fix XML-View

src/modules/diagram-detail/diagram-detail.ts
---
**Changes:**
1. Formats the xml before saving
**Issues:**
Closes #879 
---
Start BPMN-Studio.
Open a diagram from file system.
Change something in the diagram.
Save it.
XML should now be saved formatted.
<details>
<summary>
:warning: Before merging please click here to expand and …
=> 🐛Format XML Before Saving

src/modules/navbar/navbar.html
---
**Changes:**
1. Improves the tooltips for start and deploy buttons
PR: #880 
---
<details>
<summary>
</summary>
<br>
Please use …
=> 💄Improve Tooltips for Start and Deploy Button

aurelia_project/tasks/e2e.ts, aurelia_project/tasks/e2eCrossbrowser.ts, integration-test.sh, test/e2e/src/statusBar.spec.ts, test/protractor.conf.crossbrowser.js, test/protractor.conf.js
**Changes:**
1. Add multiple browsers in crossbrowsertesting setup
2. Add multiple browser in protractor setup
3. Remove integration-test.sh 
4. Allow library compiler option (Reduces number of errors)
```shell
npm run build
npm run start_dev
npm run integration-test-init
npm run integration-test
```
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> ✅ Improve protractor tests

package.json, src/modules/dashboard/dashboard.html, src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.html, src/modules/process-list/process-list.html, src/modules/task-list/task-list.html, test/e2e/src/dashboard.spec.ts, test/e2e/src/pages/dashboard.ts, test/e2e/src/pages/processDefListPage.ts, test/e2e/src/pages/processModel.ts, test/e2e/src/pages/processdef-list-page.ts, test/e2e/src/pages/solutionExplorer.ts, test/e2e/src/processDefList.spec.ts, test/e2e/src/solutionExplorer.spec.ts, test/protractor.conf.js
**Changes:**
1. Add protractor test for dashboard
2. Add IDs in Web UI to reference elements by ID
3. Increase default timeout for testing framework
Have a look in documentation #832 
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre> …
=> ✅ Add dashboard tests

dev_tooling/scripts/reinstall_setup.bash, package.json
---
**Changes:**
1. Fix the reinstall script, when its called by `npm run reinstall` 
When running a script with `npm run ...` which also runs `npm` commands, `npm` is started from the `node_modules` folder instead of the global installation directory. Because the `reinstall` script
deletes the `node_modules` directory, it obviously fails when trying to execute `npm` from the `node_modules` folder. 
This …
=> 🐛 Fix reinstall script

Jenkinsfile
---
**Changes:**
1. Publish to npm even if last build failed.
2. Add message explaining why the build was not published. 
**Issues:**
Closes #899
PR: #900 
---
n/a
<details>
<summary>
</summary>
<br>
Please use …
=> :construction_worker: Publish On Retry if Previous Failed

src/modules/authentication/authentication.service.ts, src/modules/bpmn-diff-view/bpmn-diff-view.ts, src/modules/bpmn-io/services/diagram.print.service.ts, src/modules/bpmn-io/services/diagram.svg.converter.ts, src/modules/dashboard/dashboard.ts, src/modules/diagram-detail/diagram-detail.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-list/processdef-list.ts
---
**Changes:**
1. Fix some spelling in comments.
**Issues:**
Closes none
PR: #904
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre> …
=> ✏️ Fix Spelling

src/modules/diagram-tools-right/diagram-tools-right.html, src/modules/process-solution-panel/process-solution-panel.html
---
**Changes:**
1. Add tooltipps to the colorpicker
1. Change tooltipps of the SolutionExplorer's index cards
**Issues:**
Closes #886 
Closes #889 
PR: #887
---
<details>
<summary>
:warning: Before merging …
=> 💄 Add tooltips to the colorpicker and SolutionExplorer index cards

src/modules/property-panel/indextabs/forms/sections/basics/basics.html
---
**Changes:**
1. Change the description of the UserTask Form field type names.
**Issues:**
Closes #893 
PR: #903
---
<details>
<summary>
:warning: Before merging please click here to expand and follow the …
=> 🚸 Change the description of the user task form field types.

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/bpmn-io/bpmn-io.ts, src/modules/diagram-tools-right/diagram-tools-right.html, src/modules/diagram-tools-right/diagram-tools-right.ts
---
**Changes:**
1. Disable the Distribute Elements Buttons if the User has selected less than 3 elements
1. Remove all events used by the colorpicker, published by the bpmn-io component
Currently, it was unecessary to throw this events since the _diagram-tool-right_ component also has access to the modeler.
**Isses*
1. fixes #888 
PR: #890
---
> Describe how …
=> 💄♻️Disable the Distribute Element buttons, refactor colorpicker events

src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.ts
---
**Changes:**
1. Add dedicated variables to store the current xml for the xml- and the diff- view.
This fixes a bug, where the command stack got lost if the user opens the xml- or diff view.
**Issues:**
Closes #865 
---
Please check the boxes in …
=> 🐛 Fix lost command stack when opening the xml- or diff - view. 

package.json, src/contracts/bpmnmodeler/IBpmnModeler.ts, src/contracts/bpmnmodeler/IBpmnXmlSaveOptions.ts, src/contracts/bpmnmodeler/index.ts, src/modules/bpmn-diff-view/bpmn-diff-view.ts, src/modules/bpmn-io/bpmn-io.ts, src/modules/bpmn-io/services/diagram.xml.converter.ts, src/modules/bpmn-xml-view/bpmn-xml-view.ts, src/modules/diagram-detail/diagram-detail.ts
---
**Changes:**
1. Removes the `xml-beautifier` package.
2. Formats the XML string while getting it from the BPMN modeler.
**Issues:**
Closes #884 
---
- see that all works as expected
The xml should be formatted if you
- save a diagram on the filesystem,
- open the xml view of a diagram,
- …
=> ♻️🔥Remove XML Beautifier

src/contracts/file-input-event/IFile.ts, src/modules/dashboard/dashboard.ts, src/modules/process-list/process-list.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-list/processdef-list.ts, src/modules/task-list/task-list.ts
---
**Changes:**
1. Adds simple if-case to only update the displayed list when there was an update to this list.
**Issues:**
Closes #872 
---
<details>
<summary>
:warning: Before merging …
=>  ✨Only update lists when there was an update

.ci-tools/publish-github-release.js, Jenkinsfile, package.json
**Summary:**
The actual Bug that occured in 4.2.0 on windows that crashed the auto-updater was that the file generated by the electron-builder had not the name the updater expected.
This branch will add the correct "artifactName", this way the builder will build the file like the updater expects it.
This branch will not enable the updater with windows just yet since i want to see if there are other errors after this.
---
**Changes:**
1. Sets "artifactName" for windows builds
**Issues:**
Relates to #715 
---
<details>
<summary>
:warning: Before merging please click here to …
=> 🐛Fix ArtifactName on Windows

src/modules/bpmn-diff-view/bpmn-diff-view.scss
---
**Changes:**
1. Fix the wrong overflow of the diff view's summary
**Issues:**
Closes #609 
---
<details>
<summary>
:warning: Before merging please click here to expand and follow the …
=> 💄 Fix wrong text overflow of the diff view summary

aurelia_project/aurelia.json, package.json
---
**Changes:**
1. Remove faye from aurelia.json and package.json
2. Remove xml-beautifier from aurelia.json
---
<details>
<summary>
:warning: Before merging please click here to expand and …
=> 🔥Remove unused Dependencies

electron_app/electron.js, package.json
---
**Changes:**
1. Add an about window for windows 
2. Improve about window
**Issues:**
Closes #716 
PR: #921 
---
<details>
<summary>
:warning: Before merging please click here to expand and follow the …
=> ✨ Add and Improve About Window (Windows Support)

src/app.ts, src/modules/dashboard/dashboard.html, src/modules/dashboard/dashboard.ts, src/modules/task-list-container/task-list-container.html, src/modules/task-list-container/task-list-container.scss, src/modules/task-list-container/task-list-container.ts, src/modules/task-list/task-list.html, src/modules/task-list/task-list.scss, src/modules/task-list/task-list.ts
---
**Changes:**
1. Lets the dashboard view uses the task-list.
2. Adds a new component that uses the task-list for processmodels and correlations.
3. Removes xml-beautifier from aurelia config
**Issues:**
Closes #821 
---
Please check the boxes in …
=> ♻️Refactor Dashboard and Tasklist View

package.json
---
**Changes:**
1. Updates bpmn-js-differ to 2.0.2
2. Removes `^`
**Issues:**
Closes #656 
Closes #601
---
Open a diagram im BPMN-Studio.
Make some changes.
Open diff-view.
<details>
<summary>
</summary>
<br> …
=> ⬆️ :pushpin: Update bpmn-js-differ to 2.0.2 & Pin Down Version to 2.0.2

electron_app/electron.js
---
**Changes:**
1. Add double-click handling for Windows
**Issues:**
Closes #806
Closes #646 
---
<details>
<summary>
:warning: Before merging please click here to expand and follow the …
=> 🐛Fix double-click on Windows

src/modules/bpmn-io/bpmn-io.ts
---
**Changes:**
1. Set both xml-variables initially
**Issues:**
Closes #915
---
Open a diagram in BPMN-Studio.
Now no uncaught error should be thrown.
<details>
<summary>
</summary>
<br>
Please use …
=> 🐛Set xml-variables initially 

src/modules/navbar/navbar.scss, src/modules/navbar/navbar.ts
---
**Changes:**
1. Give the highlighting a more space.
2. Remove dropdownClickListener()
**Issues:**
Closes #924 
PR: #926
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre> …
=> ♻️Refactor Hightlighting in Navbar

electron_app/electron.js
**Changes:**
1. Add handling for redirects from identity server on windows.
**Issues:**
Closes #916
Closes #804
PR: #923
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> 🐛Fix Identity Server Redirect on Windows

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/diagram-detail/diagram-detail.ts
---
**Changes:**
1. Removes an event that is not used anymore.
PR: #956
---
<details>
<summary>
</summary>
<br>
Please use …
=> 🔥 Remove Obsolete Event

src/modules/diagram-tools-right/diagram-tools-right.ts
**Changes:**
1. Changes event on which the modeler is subscribing
**Issues:**
Closes #940 
PR: #966 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> 🐛 Enable tools from right toolbar on selection changed

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, test/e2e/src/bpmnXmlView.spec.ts, test/e2e/src/dashboard.spec.ts, test/e2e/src/navBar.spec.ts, test/e2e/src/pages/bpmnXmlView.ts, test/e2e/src/pages/dashboard.ts, test/e2e/src/pages/navBar.ts, test/e2e/src/pages/processDefListPage.ts, test/e2e/src/pages/processModel.ts, test/e2e/src/pages/solutionExplorer.ts, test/e2e/src/pages/statusBar.ts, test/e2e/src/processDefList.spec.ts, test/e2e/src/solutionExplorer.spec.ts, test/e2e/src/statusBar.spec.ts, test/protractor.conf.crossbrowser.js, test/protractor.conf.js
**Changes:**
1. Fix tests after restructuring solution explorer
2. Make all possible test methods static
3. Await als promises
4. Remove Chrome non-headless
5. Fix spelling issues
PR: #965 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> ✅Fix tests after solution explorer restructuring

src/main.ts, src/modules/solution-explorer-services/RefreshingSolutionExplorerService.ts, src/modules/solution-explorer-services/index.ts
**Changes:**
1. Include a workaround for singelton usage of solution explorer service.
**Issues:**
Closes #963 
PR: #970 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> 🐛 Add Workaround for Singleton Usage

src/modules/solution-explorer-services/SingleDiagramsSolutionExplorerService.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Navigate to diagram if its already opened.
**Issues:**
Closes #959
PR: #968 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :bug: If the Diagram is Already Opened, Navigate to it.

src/modules/solution-explorer-services/RefreshingSolutionExplorerService.ts
**Changes:**
1. Add a missing /index to an enum import.
**Issues:**
PR: #972 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> :bug: Correct Faulty Import

Jenkinsfile, package.json, test/Dockerfile, test/e2e/src/bpmnDiffView.spec.ts, test/e2e/src/bpmnXmlView.spec.ts, test/jenkins_e2e.sh, test/protractor.conf.js
**Changes:**
1. Add test/Dockerfile containing all dependencies for e2e tests.
2. Update Jenkinsfile to run e2e tests.
3. Add helper scripts for jenkins to package.json.
4. Update protractor configuration.
5. Fix a small test typo.
**Issues:**
PR: #928 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just …
=> :construction_worker: Run End-To-End Tests Inside Docker On Jenkins

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Remove Obsolete Refresh Button
**Issues:**
Closes #961
PR: #974
- Have a look at the Solution Explorer
- **Notice that the useless refresh button is no longer existing**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> 🔥 Remove Obsolete Refresh Button

src/contracts/bpmnmodeler/IModeling.ts, src/modules/property-panel/indextabs/general/sections/basics/basics.ts
**Changes:**
1. Fix Label Creation When Adding Name Via Property Panel 
**Issues:**
Closes #954 
PR: #982
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> 🐛 Fix Label Creation When Adding Name Via Property Panel 

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html
**Changes:**
1. Fix Style of CreateNewDiagram Input 
**Issues:**
Closes #939
PR: #976
- Open up the BPMN-Studio on windows
- Open a folder in the solution explorer
- Click on the "Add a Diagram"-Button
- **Notice that the style of the input is no longer broken**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> 💄 Fix Style of CreateNewDiagram Input

Jenkinsfile, src/modules/process-list/process-list.html, test/e2e/src/dashboard.spec.ts, test/e2e/src/pages/processModel.ts
**Changes:**
1. Changes the route to task-list-correlation
**Issues:**
Closes #945 
PR: #980 
---
- go to inspect view
- click on usertasks of an table entry
- now you should only see the usertasks of the active correlation 
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> 🐛Update Think View; Show UserTasks of Correlation Instead of ProcessModel

src/modules/bpmn-diff-view/bpmn-diff-view.ts
**Changes:**
1. Fix Setting the Default Diff Mode
**Issues:**
Closes #935 
PR: #983
- Open up the Diff View
- Change the Diff Mode to `Before vs. After`
- Close the Diff View
- Open it up again
- **Notice that the `Before vs. After`-Button is still selected, and `Before vs. After`-diff is shown as well**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this …
=> 🐛 Fix Setting the Default Diff Mode

src/modules/bpmn-io/bpmn-io.ts, src/modules/diagram-detail/diagram-detail.ts, src/modules/processdef-detail/processdef-detail.ts
---
**Changes:**
1. Fix a bug where it was possible to save an invalid diagram with the hotkeys and with the _save on leave_ modal
2. Fix a bug where it was possible to print an invalid diagram with the desired hotkey.
PR: #987
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this …
=> 🐛 Fix saving of invalid diagrams

Jenkinsfile
**Changes:**
1. Run all build steps on macos slave.
**Issues:**
PR: #996
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> :construction_worker: Run All Steps on MacOS

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/contracts/bpmnmodeler/IBpmnModeler.ts, src/contracts/diffview/constants.ts, src/modules/authentication/authentication.service.ts, src/modules/bpmn-diff-view/bpmn-diff-view.html, src/modules/bpmn-diff-view/bpmn-diff-view.ts, src/modules/bpmn-io/bpmn-io.html, src/modules/bpmn-io/bpmn-io.scss, src/modules/bpmn-io/bpmn-io.ts, src/modules/diagram-detail/diagram-detail.html, src/modules/processdef-detail/processdef-detail.html, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.ts, test/e2e/src/bpmnDiffView.spec.ts, test/e2e/src/pages/statusBar.ts
**Changes:**
1. Add Diff Against Deployed Process Model
2. Rename Diff Modes
**Issues:**
Closes #986
PR: #988
- Open a Diagram
- Deploy it
- Go to the diagram on the file system
- Click on d
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨ Add Diff Against Deployed Process Model

src/modules/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss, src/modules/start-page/start-page.html, src/modules/start-page/start-page.scss
---
**Changes:**
1. Centers the image on the start page. 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> 💄Center the Image on the Start Page

src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts, src/modules/property-panel/indextabs/general/general.ts, src/modules/property-panel/indextabs/general/sections/service-task/service-task.html, src/modules/property-panel/indextabs/general/sections/service-task/service-task.ts
---
**Changes:**
1. Adds a ServiceTask section to the Property Panel.
---
<details>
<summary>
</summary>
<br> …
=> ✨Create ServiceTask Support of Porperty Panel

test/e2e/src/minimap.spec.ts, test/e2e/src/pages/minimap.ts
**Changes:**
1. Adds BPMN.io minimap E2E tests
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> ✅ Add BPMN.io minimap E2E tests

electron_app/electron.js, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Use Electron Dialog for Opening Single Diagrams
**Issues:**
Closes #990
PR: #1021
- Open up the BPMN-Studio (both, Windows and Mac)
- Click on the Open Single Diagram Button
- **(Mac) Notice that it is still working as before**
- **(Windows) Notice that the filetype filter now displays "BPMN (.bpmn,.xml)".**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> 🐛 Fix Open Single Diagram Dialog

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Fix Diagram Creation When Solution Is Closed
**Issues:**
Closes #1023 
PR: #1024 
- Open a solution
- Click on the add diagram button
- Close the solution
- **Notice that when clicking anywhere no error will be thrown anymore**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some …
=> 🐛 Fix Diagram Creation When Solution Is Closed

electron_app/electron.js
**Changes:**
1. Remove second `open-file` event listener.
2. Add a check if bpmn-studio is started/loaded for the first time
3. Fix typo on a variable
**Issues:**
Closes #1007 
Closes #1016 
PR: #1027 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2: …
=> 🐛Close Diagrams after Reload and Fix Importing Diagrams Several Times

src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.html, src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.scss
The result looks like this: 
---
**Changes:**
1. Unifies the design of the buttons of the confirm dialoge
2. Swaps the Confirm and Decline buttons
**Issues:**
Closes #355 
PR: #1019 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> 💄Unify Confirm buttons

src/contracts/user-input-validation/IUserInputValidationRule.ts, src/contracts/user-input-validation/index.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. List All Invalid Characters That the User Enters While He's Creating a New Diagram.
**Issues:**
Closes #823 
PR: #1022
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of …
=> ✨ Show Invalid Characters When Entering a Name for a New Diagram

src/modules/heatmap/heatmap.ts, src/modules/heatmap/services/heatmap.service.ts
**Changes:**
1. Adding Documentation to Functions of the Heatmap
PR: #1017
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details> …
=> 📝 Adding Documentation to Functions of the Heatmap

src/contracts/bpmnmodeler/bpmnElements/IServiceTaskElement.ts, src/contracts/bpmnmodeler/bpmnElements/index.ts, src/modules/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts, src/modules/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.html, src/modules/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts, src/modules/property-panel/indextabs/general/sections/service-task/service-task.html, src/modules/property-panel/indextabs/general/sections/service-task/service-task.ts
**Changes:**
1. Move the http-service-task logic to its own component.
2. Create an external-task component to handle external tasks.
PR: #1032
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at …
=> ✨Add External Task to Service Task; Restructure PropertyPanel Service Task

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Add trailing whitespaces to the validation.
2. Add whitespaces at the beginning to the validation.
3. Use diagramValidationRegExpList for validation.
4. Fix minor style issues.
**Issues:**
Closes #823
PR: #1040
- Open a solution
- Add a new diagram
- Use whitespace in the beginning/ending of the filename
- **Notice that an error will be shown**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the …
=> 🐛 Improve Validation of Diagram Names

README.md
**Changes:**
1. Update node version in readme
**Issues:**
Closes #994
PR: #1054
- Have a look at the README
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis. …
=> 📝 Update Node Version in README

src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts
**Changes:**
1. Fix call activity configuration when switching between call activities
**Issues:**
Closes #1042
PR: #1053
- Open a diagram with two call activities
- Select for both of the call activities a process in the call activity section
- Switch between the two call activities
- **Notice that the configured process will always be displayed in the call activity section**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, …
=> 🐛 Fix Call Activity Configuration When Switching Between Call Activities

src/contracts/diffview/constants.ts, src/modules/bpmn-diff-view/bpmn-diff-view.ts, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.ts, test/e2e/src/bpmnDiffView.spec.ts, test/e2e/src/pages/statusBar.ts
**Changes:**
1. Renames the "DiffModes" in the Diff View from "previous" and "current" to "old" and "new"
**Issues:**
Closes #1029 
PR: #1051 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at …
=> 💄Rename Diff to Old and New

src/modules/heatmap/contracts/constants.ts
**Changes:**
1. Move the heatmap bubbles of tasks to the upper right corner.
**Issues:**
Closes #992 
PR: #1055 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=> 🐛Move Heatmap Bubbles to the Upper Right Corner

electron_app/electron.js
---
**Changes:**
1. Add a link to the documentation to the menubar
2. Add a link to the release notes to the menubar 
**Issues:**
Related #1036 
Closes #951 
PR: #1061 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> ✨Add a help menu with useful links to the Title Bar

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/app.ts, src/modules/authentication/authentication.service.ts, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts
**Changes:**
1. Add the identity server configuration to the local storage
2. Add option to set the default authority
3. Make config private
**Issues:**
Closes #776 
Closes #454 
PR: #1043 
- Go to settings
- Change the authority
- Restart the BPMN-Studio
- Go to settings
- **Notice that the authority is still the configured one.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this pull …
=> ✨Add Identity Server Configuration to the local storage

electron_app/electron.js
**Changes:**
1. Fix wrong variable name
PR: #1066
- **Notice that there won't be errors anymore**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre> …
=> 🐛 Fix Wrong Variable Name

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Replace Error Message By Warning
**Issues:**
Relates to #1065
PR: #1068
- Try to rename a diagram to an already existing name
- **Notice that there will be a warning instead of an error**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> 💄 Replace Error Message By Warning

aurelia_project/aurelia.json, index.html, src/app.ts
**Changes:**
1. Fix problems with bootstrap bundling
**Issues:**
PR: #1069 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> :bug: Fix Bootstrap Bundling

Jenkinsfile, src/modules/navbar/navbar.scss, test/e2e/src/dashboard.spec.ts, test/e2e/src/pages/dashboard.ts, test/e2e/src/pages/navBar.ts
**Changes:**
1. Run builds again on linux agent
2. Reenable End-To-End tests
3. Fix End-To-End tests for the latest version
**Issues:**
PR: #1067 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration …
=> :construction_worker: Run Builds On Linux Agent and Enable E2E Tests

electron_app/electron.js, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Add menu entries to open diagrams and solutions
**Issues:**
PR: #1082 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :sparkles: Allow Opening Diagrams Via Menubar And Shortcut

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Highlight currently opened diagram in solution explorer
2. Small tweaks to css
**Issues:**
Closes #1037 
PR: #1080
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> :sparkles: Highlight Currently Opened Diagram In SolutionExplorer

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Check for undefined before accessing property
**Issues:**
PR: #1081 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :bug: Fix Creating Of New Diagrams Via SolutionExplorer

Jenkinsfile
**Changes:**
1. Use a custom workspace to shorten the path.
**Issues:**
PR: #1084 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :construction_worker: Use A Custom Workspace Path on Windows to Fix Long Path Issues 

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Treat inspect the same way as processdef detail.
**Issues:**
PR: #1085 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :bug: Highlight Opened Diagram When In Inspect View

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/diagram-detail/diagram-detail.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Fire new event on diagram deploy
2. Listen for new event and refresh solutions
**Issues:**
PR: #1088 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> :sparkles: Refresh SolutionExplorer When A Diagram is Deployed

src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html
**Changes:**
1. Fix the  wrongly disabled _navigate to Process_ button. 
**Issues:**
PR: #1089
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 🐛Fix Call Activity Navigate to Process button

src/modules/processdef-detail/processdef-detail.html
**Changes:**
1. Add missing css class to modal.
**Issues:**
Closes #1094 
PR: #1095
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :bug: Fix Starting Processes With Multiple Start Events

electron_app/electron.js
---
**Changes:**
1. Add an option to create a new folder when trying to open a solution with the systems open dialog.
**Issues:**
Closes #1098 
PR: #1101
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> ✨ :sparkles: Add an Option to Create a Folder When Opening a Solution

src/contracts/bpmnmodeler/bpmnElements/IScriptTaskElement.ts, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/script-task/script-task.ts
**Changes:**
1. ♻️ unused field removed from ScriptTask
**Issues:**
Closes #1106 
PR: #1107 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :sparkles: remove unused fields from ScriptTask

src/modules/bpmn-io/bpmn-io.ts
---
**Changes:**
1. Fix an issue where it was not possible, to copy the selected content from the xml view to the system clipboard using the system shortcuts.
**Issues:**
Closes #1102 
PR: #1103 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre> …
=> 🐛:bug: Fix copy shortcut when using the xml view

src/modules/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss
**Changes:**
1. Improve Selection Color of Correlation Table
**Issues:**
Closes #1091
PR: #1108
---
- Run a process
- Go to inspect correlation view
- Select a correlation
- **Notice that the color of the selected correlation is easier to distinguish from the other colors.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2: …
=> 💄 Improve Selection Color of Correlation Table

src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/property-panel/indextabs/general/sections/message-task/message-task.html, src/modules/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.html, src/modules/property-panel/indextabs/general/sections/service-task/service-task.html, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.html, src/modules/property-panel/styles/sections.scss
---
**Changes:**
1. Fix the design of the dropdown on the UserTask type selection to unify the overall design.
**Issues:**
Closes #1073 
PR: #1096 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration …
=> 🐛💄Fix wrong select design

src/app.scss, src/modules/diagram-detail/diagram-detail.html, src/modules/processdef-detail/processdef-detail.html, src/modules/user-login/user-login.scss
**Changes:**
1. Add missing hover effect
2. Use default button for modals
3. Remove unused CSS class
4. Readd missing modal backdrop
**Issues:**
Closes #1109 
PR: #1110
---
- Open any diagram
- Try to close the BPMN-Studio
- **Notice that the Buttons now have a hover effect.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this …
=> 💄 Add Missing Hover Effect

package.json, src/modules/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/extensions/sections/process/process.html, src/modules/property-panel/indextabs/extensions/sections/process/process.ts
---
**Changes:**
1. This PR adds the ability to check, if the user created an empty extension property and removes it. 
**Issues:**
Related: #1057 
PR: #1077
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> ✨Remove empty extension properties after creating

package.json
**Changes:**
1. Adds the correct path of the resources folder to the npm package
**Issues:**
Closes #1113 
PR: #1114 
---
- `npm i bpmn-studio@4.8.1-52d8ccca-b1 -g`
- `bpmn-studio`
- open the link and see that there is an image on the landing-page
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> ✨ Add correct path to resources for npm package

dev_tooling/scripts/generate_changelog/format_messages.bash
---
**Changes:**
1. Adds new emojis to the format message script to confirm gitmoji. 
**Issues:**
PR: #1116
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=> ✨Add new gitmoji emojis to release format script

src/modules/inspect-correlation/components/token-viewer/token-viewer.html, src/modules/inspect-correlation/components/token-viewer/token-viewer.scss, src/modules/inspect-correlation/components/token-viewer/token-viewer.ts, src/modules/inspect-correlation/contracts/IRawTokenEntry.ts, src/modules/inspect-correlation/contracts/index.ts
**Changes:**
1. Add Raw View for Token Viewer
**Issues:**
Closes #1112
PR: #1118
---
- Go to inspect correlation view
- Select a correlation
- Select a flow node
- Open up the Token Viewer
- **Switch between Raw and Beautified Token**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
=> ✨ Add Raw View for Token Viewer

src/contracts/colorpicker/IDefaultBpmnColors.ts, src/contracts/colorpicker/constants.ts, src/modules/inspect-correlation/components/diagram-viewer/diagram-viewer.ts
**Changes:**
1. Colorize selection in Diagram Viewer
**Issues:**
Closes #1100
PR: #1119
---
- Go to inspect correlation view
- Click on any element
- **Notice that the element gets highlighted**
- Change the correlation
- **Notice that the element is still highlighted**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2: …
=> ✨ Colorize Selection in Diagram Viewer

src/modules/inspect-correlation/inspect-correlation.html, src/modules/inspect-correlation/inspect-correlation.scss, src/modules/inspect-correlation/inspect-correlation.ts
**Changes:**
1. Make Token Viewer Resizeable
**Issues:**
Closes #1120 
PR: #1124
- Go to the inspect correlation view
- Open up the token viewer
- **Resize the token viewer**
**Important:** The diagram viewer should never become smaller than 300px. Even when resizing the application.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> ✨ Make Token Viewer Resizeable

Jenkinsfile
**Changes:**
1. Dont use raw package version, use trimed package version
**Issues:**
Closes #1033 
PR: #1127 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=> :construction_worker: Use Trimed Package Version For Comparison

package.json
**Changes:**
1. Make BPMN-Studio installable as non-admin
PR: #1131
**On Windows**
- Run `npm i` and `npm run electron-build-windows`
- Install the exe in the dist folder
- **Notice that you can choose if you want to install the BPMN-Studio for every user (as admin) or just for the current user (as non-admin)**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> 🚸 Improve Installer on Windows

package.json
**Changes:**
1. Pin aurelia-route-recognizer to 1.2.0
PR: #1139
- Go to Inspect View
- Click on any diagram in the solution explorer
- **Notice that the inspect view is displayed correctly again.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 🐛 Fix Inspect View

src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/pool/pool.ts
**Changes:**
1. Fix breaking PropertyPanel while collapsing pools
2. Fix Bug when selecting the 'Process' after deleting the Participant
**Issues:**
Closes #1150 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> 🐛Fix PropertyPanel after collapse a pool

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/design/processdef-detail/processdef-detail.ts
**Changes:**
1. Add EventListener for ValidationError
2. Prevent saving a diagram with multiple participants
**Issues:**
Closes #1151 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> 🐛Prevent saving a diagram with multiple participants

src/contracts/bpmnmodeler/IDescriptor.ts, src/contracts/bpmnmodeler/IInternalEvent.ts, src/contracts/bpmnmodeler/bpmnElements/IPropertiesElement.ts, src/contracts/bpmnmodeler/index.ts, src/modules/design/bpmn-io/bpmn-io.ts
**Changes:**
1. Add Interfaces for IInternalEvent and IDescriptor
2. Add optional fields to IPropertiesElement
3. Check if a UserTask was Copied Before Pasting it to Rename its formField IDs
**Issues:**
Closes #1149 
PR: #1157 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this …
=> 🐛Fix UserTask FormField IDs are not Unique Bug

src/modules/design/bpmn-diff-view/bpmn-diff-view.scss
**Changes:**
1. Fix Layout of Diff View
**Issues:**
Closes #1159 
PR: #1161
- Go to the Diff View
- **Notice that the diff view look the same all the time**
> There is no sure way to reproduce the issue, but using `flex` instead of `calc` should fix the issue.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> 🐛 Fix Layout of Diff View

src/modules/design/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts
**Changes:**
1. Rename `Number` to `Integer`
2. Add `Decimal` type
**Issues:**
PR: #1144
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :sparkles: Clarify Names of Numeric Form Field Types

src/contracts/solution-explorer/ISolutionService.ts, src/modules/config-panel/config-panel.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/inspect/heatmap/heatmap.html, src/modules/inspect/heatmap/heatmap.scss, src/modules/inspect/heatmap/heatmap.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/SolutionService.ts
**Changes:**
1. Add set and get for ActiveSolution to SolutionService and use it.
2. Fix bug when ProcessEngineRoute has changed where the navbar has shown the previous opened diagram name.
3. Fix bug when navigate to /diagram/detail from browser without a diagram name.
4. Fix bug when the heatmap gets attached without an activeDiagram.
5. Fix bug when navigate between inspect views without an active diagram.
6. Show message on heatmap If no active Diagram.
7. Remove unused EventAggregator from heatmap.
8. Fix bug which shows the inspect view on diagram detail.
9. Remove processdef-detail check on navbar.
10. Use diagram.name instead of diagram.uri for class and title binding.
11. Fix getting the wrong params from router and remove unnecessary processdef stuff.
**Issues:**
Closes #1164 …
=> ♻️ 🐛 Refactor and Bugfixes

src/modules/diagram-creation-service/DiagramCreationService.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts
**Changes:**
1. Set executable flag per default
2. Select latest process instance per default in inspect correlation
PR: #1167
- **Notice that the executable flag is already set**
- Run a diagram multiple times
- Go to inspect correlation
- **Notice that the latest correlation will be selected**
- Change the ProcessModel
- **Notice that the latest correlation will be selected**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, …
=> 🚸 On Deploy Make Process Executable by Default; Show Latest Instance in Correlation List

electron_app/electron.js
**Changes:**
1. Dont show menu reload item when in dev setup.
**Issues:**
Closes #1163
PR: #1168 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨ Disable Reload Menu Item When not in Dev Setup

package.json, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Fix Setting Active Solution
2. Update Runtime Dependency
PR: #1181
- open a solution with diagrams
- deploy a diagram
- rename the same diagram on the fs
- deploy it again
- select another diagram from the fs solution
- **see that no error occurs**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> 🐛 Fix Setting Active Solution

Jenkinsfile, test/Dockerfile, test/e2e/src/bpmnDiffView.spec.ts, test/e2e/src/bpmnXmlView.spec.ts, test/e2e/src/dashboard.spec.ts, test/e2e/src/minimap.spec.ts, test/e2e/src/navBar.spec.ts, test/e2e/src/pages/processModel.ts, test/e2e/src/processDefList.spec.ts, test/e2e/src/solutionExplorer.spec.ts, test/protractor.conf.js
**Changes:**
1. Adds a clean up function that deletes the created diagram after each test.
This will keep the database clean even if multiple test were run.
Previously the diagram wouldn't get deleted that lead to failing tests even though they would succeed.
**Issues:**
Closes #1160 
PR: #1183 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code> …
=> ♻️Refactor E2E Tests

src/modules/design/diagram-detail/diagram-detail.html, src/modules/design/diagram-detail/diagram-detail.scss, src/modules/design/diagram-detail/diagram-detail.ts
**Changes:**
1. Adds the correct handling of closing the modal when changes were saved.
2. Places the modal correctly again.
**Issues:**
Closes #1158 
PR: #1184 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
=> 🐛Fix Save Modal on Start of Process

src/modules/live-execution-tracker/live-execution-tracker.ts
**Changes:**
1. Add Method to get a ProcessModel and Convert it to IDiagram
2. Fix Bug Where the Wrong Diagram is Set After Using Live Execution Tracker
**Issues:**
Closes #1187 
PR: #1188 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> 🐛Fix Setting Correct Solution and Diagram on Live Execution Tracker

src/modules/config-panel/config-panel.ts, src/modules/design/diagram-detail/diagram-detail.ts
**Changes:**
1. Adds a check to determine if the active solution is remote in config-panel.
2. Adds a check for undefined active solution in diagram-detail.
**Issues:**
Closes #1185 
PR: #1186
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre> …
=> 🐛Fix Settings Update Navigate

src/modules/inspect/heatmap/heatmap.scss, src/modules/inspect/heatmap/heatmap.ts
**Changes:**
1. Add minimap to heatmap
2. Move legend to lower left corner
**Issues:**
Closes #1169
- Go to the Heatmap View
- **Notice that there will be a Minimap**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> ✨ Add Minimap to Heatmap

src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts
**Changes:**
1. Make inspect correlation table descending per default
PR: #1201
- Open up the Inspect Correlation
- **Notice that in the inspect correlation table the latest instances will be shown first**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> 🚸 Make Inspect Correlation Table Descending Per Default

dev_tooling/scripts/generate_changelog/create-changelog.sh
**Changes:**
1. Improve Changelog Creation
PR: #1182
- Create a changelog
- **Notice how easy the changelog creation can be.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most …
=> 🚸 Improve Changelog Creation

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/app.scss, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-detail/diagram-detail.html, src/modules/design/diagram-detail/diagram-detail.scss, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.scss, src/modules/navbar/navbar.ts
**Changes:**
1. Add StartProcessWIithOptions Event
2. Remove processDefDetail from Events
3. Refactor and Improve Navbar HTML and add a Dropdown Start Button
4. Add startProcessWithOptions Method
5. Add showStartWithOptions Modal
6. Remove Border-Color and Box-Shadow From Bootstrap Input
7. Add setOptionsAndStart Method to Handle the Modal
8. Fix Bug with StartEvents
PR: #1204 
---
- open the design view of a process
- click on <img width="48" alt="bildschirmfoto 2018-12-14 um 13 46 40" src="https://user-images.githubusercontent.com/17065920/50004421-62fa6b00-ffa7-11e8-861c-7e7b119d1bc9.png"> => <img width="254" alt="bildschirmfoto 2018-12-14 um 13 52 43" src="https://user-images.githubusercontent.com/17065920/50004485-92a97300-ffa7-11e8-9f4c-e …
=> ✨Start Process With Custom CorrelationId and Payload

src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts, src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.ts, src/modules/inspect/inspect-correlation/repositories/inspect-correlation.repository.ts, src/modules/live-execution-tracker/live-execution-tracker.html, src/modules/live-execution-tracker/live-execution-tracker.scss, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/task-dynamic-ui/task-dynamic-ui.html, src/modules/task-dynamic-ui/task-dynamic-ui.ts
**Changes:**
1. Add call activity support to live execution tracker
2. Add modal support to dynamic ui
3. Display tasks in modal in live execution tracker
**Issues:**
Closes #1176 
PR: #1203
- Go to the Detail View of any diagram with a call activity
- **Notice that one can now click on the call activity in order to navigate to it.**
- Click on an active User-/ManualTask
- **Notice that the dynamic ui will now be displayed in a modal**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: …
=> ✨ Add CallActivity Support to Live Execution Tracker

src/app.ts, src/contracts/index.ts, src/contracts/routing/IAureliaRouterResponse.ts, src/contracts/routing/index.ts, src/contracts/solution-explorer/ISolutionService.ts, src/main.ts, src/modules/config-panel/config-panel.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/design/property-panel/indextabs/general/repository/general.repository.ts, src/modules/inspect/inspect.ts, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/navbar/navbar.ts, src/modules/solution-explorer-services/SingleDiagramsSolutionExplorerService.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/status-bar/status-bar.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts, src/modules/think/processdef-list/processdef-list.ts, src/services/SolutionService.ts, test/e2e/src/dashboard.spec.ts, test/e2e/src/pages/processModel.ts
**Changes:**
1. Refactors and unifies the navigation in the whole project.
2. Adds the solution URI to the navigation.
3. Adds the feature of persisting opened solutions.
4. Adds the reload functionality again.
This simplifies the current navigation by far and serves as a first step to make BPMN-Studio handle links to specific diagrams and solutions.
PR: #1196
=> ✨♻️Add Solution to Navigation

src/app.scss
**Changes:**
1. Remove blue outline from inputs
PR: #1213
- Run a process with a UserTask with FormFields
- Click on the UserTask
- Click on a FormField
- **Notice that the blue outline is gone**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 💄 Remove Blue Outline from Inputs

src/modules/live-execution-tracker/live-execution-tracker.html
**Changes:**
1. Fix displaying dynamic ui modal
**Issues:**
Closes #1210
PR: #1209
- Run a process with a UserTask
- Close the BPMN-Studio
- Go to the dashboard
- Click on the 'live execution tracker'-button of the process instance you have just started
- Click on the UserTask
- **Notice that the LET will now always display the dynamic ui modal**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just …
=> 🐛 Fix Displaying Dynamic UI Modal

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
---
**Changes:**
1. Fixes a bug which leads to two highlighted diagrams when a diagram had the same name in each Solution.
**Issues:**
Closes #1212 
PR: #1218
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> 🐛 Fix duplicate highlight when two diagrams in two different solution had the same name

src/modules/dynamic-ui-number-element/dynamic-ui-number-element.html, src/modules/dynamic-ui-number-element/dynamic-ui-number-element.ts
**Changes:**
1. Fix integer validation in dynamic ui
PR: #1216
- Create a diagram with a UserTask with a FormField of type Integer
- Click on the UserTask
- Try to enter any letter or `,`
- **Notice that you can only enter digits.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> 🐛 Fix Integer Validation in Dynamic UI

package.json
**Changes:**
1. Updates the bpmn-js-custom-bundle dependency to 2.3.0.
=> ⬆️Update bpmn-js-custom-bundle Dependency

src/app.ts
**Changes:**
1. Fix design and inspect route
2. Fix navigation after opening single diagrams
3. Fix navigation after deploying new diagrams
**Issues:**
Closes #1228 
Closes #1230 
PR: #1232
- Open a Single Diagram
- **Notice that it will open as it should.**
- Deploy a diagram for the first time
- **Note that it will open as it should.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this pull …
=> 🐛 Fix Design And Inspect Route

src/modules/design/design.html, src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.html, src/modules/design/diagram-detail/diagram-detail.ts
**Changes:**
1. Fix xlosing BPMN-Studio when changes exist
2. Fix 'Document Contains Changes'-Modal in diff and xml view
PR: #1234
- Go to diff-/xml-view
- Close the BPMN-Studio
- **Notice that the 'Document Contains Changes'-Modal will be displayed.**
- Go to diff-/xml-view
- Change the diagram via the solution explorer
- **Notice that the 'Document Contains Changes'-Modal will be displayed.**
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the …
=> 🐛 Fix Closing BPMN-Studio When Changes Exist

src/modules/status-bar/status-bar.ts
---
**Changes:**
1. Fix the wrong labeling of the status bar buttons when using the Back button twice.
**Issues:**
PR: #1238
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some …
=> 🐛 Fix Wrong Status Bar Buttons When Using the Back Button

src/modules/design/design.html, src/modules/design/design.ts
**Changes:**
1. Fix Bug With Where The Old Diagram Is New And Reversed
**Issues**
PR: #1237 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 🐛 Fix a Bug Where the Old Diagram Is New and Reversed

test/e2e/src/bpmnXmlView.spec.ts
**Changes:**
1. Fix e2e Tests for XML View
PR: #1240 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> 🐛:bug: Fix e2e Tests for XML View

src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html
**Changes:**
1. Fix Call Activities on File System
**Issues:**
Closes #1207 
PR: #1246
---
1) Start BPMN-Studio
2) Create two diagrams on the filesystem.
3) Create a call activity in one of them calling the other.
4) See that "Navigate to called process" now works.
5) Now Deploy them both and start the one with the call activity.
=> 🐛 Fix Call Activity on FileSystem

src/modules/design/bpmn-io/bpmn-io.html
**Changes:**
1. Clarifies a comment.
**Issues:**
Closes #461
=> ♻️Clarify Comment

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
---
**Changes:**
1. Fix a bug where a promise was rejected when initially starting bpmn studio.
**Issues:**
Closes #1243 
PR: #1244 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> 🐛 Fix uncaught exception when initially loading solutions

src/modules/design/bpmn-io/bpmn-io.ts
**Changes:**
1. Fix the generation of a random ID for form fields on the copied user task.
1. Start BPMN-Studio
2. Create a diagram and place a user task with a form field in it.
3. Make sure the form field has a type.
4. Copy it.
=> 🐛Fix ID Generation on copy of Usertasks

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Add diagram location to single diagrams
**Issues:**
Closes #944 
PR: #1250
- Open a Single Diagram
- **Notice that the location will be shown in the solution explorer**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> ✨ Add Diagram Location to Single Diagrams

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Don't open single diagram several times.
**Issues:**
Closes #1254 
=> 🐛 Don't Open Single Diagrams Several Times

src/modules/design/bpmn-diff-view/bpmn-diff-view.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.html, src/modules/design/design.scss, src/modules/design/design.ts
**Changes:**
1. Fix diff against deployed diagram
2. Prevent fitToViewport When Diagram is Not Displayed
3. Fix navigation between two diagrams with the same name
**Issues:**
Closes #1241
PR: #1252 
- Go to the Diff View
- Click on the icon
- Select a ProcessEngine
- **Notice that it will display the diff as it should.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the …
=> 🐛 Fix Diff Against Deployed Diagram

src/contracts/bpmnmodeler/IShape.ts, src/modules/design/diagram-detail/diagram-detail.html, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/inspect/process-list/process-list.html
**Changes:**
1. Adjust IShape Interface
2. Add Custom Start Button To StartEvent Modal
3. Use The StartEvent Annotation as Default Token On The Custom Start Modal
PR: #1253 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> ✨InitialToken From StartEvent Annotation

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
---
**Changes:**
1. Navigates the user away from the detail view, if he closes the associated Solution
**Issues:**
PR: #1257 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some …
=> ✨ Navigate away, if the user closes the Solution, on whose detail view he is currently on

src/modules/config-panel/config-panel.ts, src/modules/design/design.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.ts
**Changes:**
1. Remove Unused Variable
2. Remove Unused Interface
3. Remove Unused Activate Method And Set SolutionUri From Router
4. Add a Fallback If No SolutionUri
5. Use Identity of the ActiveSolution instead of AuthenticationService
6. Adjust Route Param
PR: #1264
=> 🐛Fix Bug Where SolutionUri is Undefined

aurelia_project/environments/dev.ts, src/app.ts, src/modules/inspect/inspect.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/status-bar/status-bar.ts, src/modules/think/think.scss, test/e2e/src/pages/navBar.ts, test/e2e/src/pages/statusBar.ts
**Changes:**
1. Adjust Router Config for Navbar
2. Use Aurelia Router To Generate The Navbar Entries
3. Add routerNavigate Method
4. Remove navigateToInspect, navigateToDesigner and navigateToThink Methods
5. Add navigate Method
6. Use routerNavigate instead of navigateToRoute
PR: #1275 
---
- check whether the studio works as expected 
note: you should specially check for the navigation between the think design inspect and their child views (xml, diff, detail, inspect-correlation, heatmap, dashboard)
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge …
=> ♻️Refactor Navbar And Router Usage

aurelia_project/environments/dev.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.ts
**Changes:**
1. Add Keyboard Variable
2. Bind/Unbind The Keyboard Dependent on Which View You Are
**Issues:**
Closes #1280 
PR: #1283 
---
- open a diagram
- switch to xml view
- select some lines of xml 
- click cmd + c
- switch to an place where you like to paste the copied part
- paste it
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre> …
=> 🐛Fix Copy on Xml

aurelia_project/aurelia.json, aurelia_project/environments/dev.ts, aurelia_project/native/os.js, electron_app/electron.js, src/app.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/start-page/start-page.html, src/modules/start-page/start-page.scss, src/modules/start-page/start-page.ts
**Changes:**
1. Add Open Solution Shortcut to Welcome Page.
2. Add Open File Shortcut to Welcome Page.
3. Add Create Diagram Functionality out of Welcome Page. 
(This will default to the "Desktop" but if you select a Solution the diagram will be created there instead.)
4. Add Create new Diagram Shortcut to Welcome Page.
**Issues:**
Closes #942 
Closes #1076
Go through the shortcuts now mentioned on the start-page.
=> ✨Improve Welcome Page

src/contracts/bpmnmodeler/IInternalEvent.ts, src/modules/design/bpmn-io/bpmn-io.ts
**Changes:**
1. Add Element Property to IInternalEvent Interface
2. Add DiagramHasChanges Subscription And Its Variable
3. Correct Type and Variable Naming From EventBus Subscripton
4. Add Event Parameter And Return Statement
5. Save The Process ModdleElement Temporarily While Removing It
6. Remove Unused Import
7. Fix Bug Where Participant ID Gets Changed and Occus Errors At The Backend
**Issues:**
Closes #1248
PR: #1284 
---
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the …
=> 🐛Fix Participant ID Bug

src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.ts
**Changes:**
1. Moves the publish of the corresponding event to the correct place
1. Open a diagram on a remote solution.
2. Now open a different diagram on another remote solution.
3. Start Process.
=> 🐛Fix Setting of PE Route in Management API

src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.ts, src/modules/inspect/dashboard/dashboard.ts, src/modules/inspect/heatmap/contracts/IHeatmap.Repository.ts, src/modules/inspect/heatmap/contracts/IHeatmap.Service.ts, src/modules/inspect/heatmap/heatmap.ts, src/modules/inspect/heatmap/repositories/heatmap.mock.repository.ts, src/modules/inspect/heatmap/repositories/heatmap.repository.ts, src/modules/inspect/heatmap/services/heatmap.service.ts, src/modules/inspect/inspect.html, src/modules/inspect/inspect.ts, src/modules/live-execution-tracker/live-execution-tracker.html, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts, src/modules/task-list-container/task-list-container.ts, test/e2e/src/dashboard.spec.ts, test/e2e/src/pages/dashboard.ts
**Changes:**
1. Remove getIdentity Method From Dynamic-Ui-Wrapper
2. Remove getIdentity Method From Dashboard
3. Add setIdentity Method to Heatmap Repository Contracts
4. Add setIdentity Method to Heatmap Service Contracts
5. Set Identity If activeSolutionEntry has Changed On Heatmap
6. Remove getIdentity Method From Heatmap Mock rRepository
7. Remove getIdentity Method From Heatmap Repository
8. Add setIdentity Method to Heatmap Service
9. Bind activeSolutionEntry to Heatmap
10 Make activeSolutionEntry Public and Pass it to Dashboard's canActivate
11. Remove getIdentity Method From Live Execution Tracker
12. Remove getIdentity Method From Task Dynamic Ui
13. Remove getIdentity Method From Task List Container
**Issues:**
Closes #1267 
PR: #1278 
---
See the [examples](#example) for …
=> 🔥♻️Remove getIdentity Method

src/modules/design/design.html
**Changes:**
1. Fix Binding on Multiple Solutions Modal.
PR: #1297 
1. Open more than one remote solution.
2. Deploy a diagram to any of them.
=> 🐛 Fix Deploy on Multiple Connected Solutions

aurelia_project/environments/dev.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.ts
**Changes:**
1. Open LogViewer on Double Click.
**Issues:**
Closes #1268 
2. Start a process.
3. Open Inspect Correlation.
4. Double click on an entry of the correlation list. 
=> ✨Open LogViewer on Double Click

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Add a RegEx to check URI for validity.
2. Get rid of slashes at the end of an URI to avoid error.
**Issues:**
Closes #1300 
2. Open a remote Solution.
=> ✨Solidify URI Check When Opening a Remote Solution

src/modules/think/think.ts
**Changes:**
1. Reload Think When Changing Diagram With SolutionExplorer
PR: #1315 
---
- open some solutions
- open the think view
- change the diagram (diagram from another solution)
- see that the think view gets reloaded directly
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> 🐛💄 Reload Think When Changing Diagram With SolutionExplorer

electron_app/electron.js, package.json
**Changes:**
1. Update Process Engine Runtime
2. Fix Bug With Platform-Folders and Start Runtime Correctly
**Issues:**
Closes #https://github.com/process-engine/process_engine_runtime/issues/208
PR: #1317 
---
- start a process with an usertask
- do not finish the task
- goto the design view
- change the startevents ID
- save
- close the studio and open again
- goto the inspect view and continue the previous started process 
- finish the task
- see that it works
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
=> 🐛Fix Resuming Processes

Jenkinsfile, aurelia_project/aurelia.json, package.json, src/app.html
**Changes:**
1. Adds necessary configuration to BPMN-Studio to use FontAwesome Pro.
**Issues:**
Closes #878 
PR: #1303 
---
Get test builds from: https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/feature%2Fuse_fontawesome_pro/20/artifacts
Tested on:
=> :sparkles: Use FontAwesome Pro

Jenkinsfile, aurelia_project/aurelia.json, package.json, src/app.html
This reverts commit fe60b56a26c26f8af9140d6ba98d731857704fe2, reversing changes made to 41877d64f766cc4b975646ed6a3375b5c92f9fbd.
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> :rewind: Revert ":twisted_rightwards_arrows: :sparkles: Use FontAwesome Pro

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Fix RegEx for URLs
Tested my RegEx with https://www.regextester.com/?fam=107448
**Issues:**
Closes #1326 
---
- try to reproduce #1326 
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> 🐛Fix RegEx for URLs

src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts
**Changes:**
1. Delete the correct ExtensionElement upon deleting the last property of a task.
**Issues:**
Closes #1318 
- Follow the Instructions in #1318. 
- See that the error doesn't occur anymore.
=> 🐛Delete Correct ExtensionElement

package.json, src/modules/design/bpmn-io/bpmn-io.ts
**Changes:**
1. Add Resize Functionality to Design
**Issues:**
Closes #1320
PR: #1329
- Click on any element
- **Notice that the elements can now be resized**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨ Add Resize Functionality to Design

src/modules/inspect/heatmap/heatmap.ts
**Changes:**
1. Fit Diagram To Viewport On Heatmap
PR: #1325 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> ✨Fit Diagram To Viewport On Heatmap

src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.html, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.scss, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Add a modal that prompts if the user is sure to delete the diagram.
**Issues:**
Closes #1321
PR: #1324
1. Open a local Solution.
2. Create a diagram.
3. Delete it.
=> ✨Add Delete Diagram Modal

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
This adds a sorting mechanism to the opened Solutions, the order is:
1. Single Diagrams
2. The internal PE
3. All other remote Solutions
4. All local Solutions
**Changes:**
1. Add sorting the opened Solutions.
**Issues:**
Closes #1242
PR: #1304
2. Open some different Types of Solutions.
3. Restart the Studio, see that the Solutions stay in order.
=> ✨Sort Opened Solution in Specific Order

Jenkinsfile, Jenkinsfile-node-v7
**Changes:**
1. Adds a clean step to prepare step.
=> 🐛Fix NPM Cache Problem on Jenkins

Jenkinsfile, Jenkinsfile-node-v7
**Changes:**
1. Reverts process-engine/bpmn-studio#1337
PR: #1339
=> ⏪ Revert "🐛Fix NPM Cache Problem on Jenkins"

src/modules/live-execution-tracker/live-execution-tracker.html, src/modules/live-execution-tracker/live-execution-tracker.scss, src/modules/live-execution-tracker/live-execution-tracker.ts
**Changes:**
1. Remove back button
2. Move 'Back to previous process' button
3. Fix 'Back to previous process' navigation
**Issues:**
Closes #1282
PR: #1343
- Run a diagram with a call activity
- Click on the Call Activity
- **Have a look at the LET.**
- Click on the 'Navigate back to previous process'
- **Notice that the navigation will work.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2: …
=> ♻️ Improve Navigation Buttons in LET; 🐛 Fix 'Back to previous process' Navigation

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
**Changes:**
1. Add the correct binding to the uri when opening a new remote solution. 
1. Open a remote Solution.
=> 🐛 Fix Binding on Remote Solution Uri

package.json
**Changes:**
1. Fix Selecting SequeceFlows
**Issues:**
Closes #1345
PR: #1347
- Click on any SequenceFlow
- **Notice that the data of the SequnceFlow will be shown in the PropertyPanel**
=> 🐛 Fix Selecting SequeceFlows

src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts
Deletes null assignments and fixes a bug where you could not copy usertasks with unset formfieldtypes.
Camunda expects unset variable types to be `undefined`, not `null`.
A problem appeared here(where `propertyElement['type']` was `null` and caused an error, see #1156 )
```js
if (propertyElement[propName] !== undefined &&
(propertyElement[propName].$type || isArray(propertyElement[propName]))) {
```
---
**Changes:**
1. Delete null assignments
**Issues:**
Closes #1156
---
See #1156 and test whether it still occurs.
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at …
=> 🐛 Delete null Assignments to Formfield Types

package.json
**Changes:**
1. Update bpmn-lint dependencies.
=> 🐛 Fix Forgotten Dependencies

package.json
**Changes:**
1. Update Lint Rules Dependency
=> ⬆️Update Lint Rules Dependency

package.json
**Changes:**
1. Fix Style of Minimap Toggle Button
PR: #1358
- Have a look at the Minimap Button
- **Notice that the style is the same as the style of the lint button.**
=> 💄 Fix Style of Minimap Toggle Button

package.json
**Changes:**
1. Add Correct StartEvent Required Rule
2. Add Correct EndEvent Required Rule
1. Open BPMN-Studio
2. Go to design view
3. Activate Linting
4. Delete the StartEvent of a diagram
5. See that the Error now gets correctly reported at the participant.
=> ⬆️ Update Lint Rules Dependency

src/services/solution-explorer-services/SingleDiagramsSolutionExplorerService.ts
**Changes:**
1. Add a check to see if the file is a .bpmn file.
**Issues:**
Closes #1294
1. Follow the instructions in the Issue.
2. See that a new Error is coming up.
=> 🐛Fix Opening Single Diagrams on Drag and Drop

src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/design/property-panel/indextabs/extensions/sections/process/process.html, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/conditional-event/conditional-event.html, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/design/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/design/property-panel/indextabs/general/sections/flow/flow.html, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/design/property-panel/indextabs/general/sections/message-task/message-task.html, src/modules/design/property-panel/indextabs/general/sections/pool/pool.html, src/modules/design/property-panel/indextabs/general/sections/process/process.html, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.html, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.html, test/e2e/src/bpmns/PPTest.bpmn, test/e2e/src/contracts/IRequestHeaders.ts, test/e2e/src/contracts/IRequestPayload.ts, test/e2e/src/contracts/index.ts, test/e2e/src/diagrams/diagramWithUserTask.ts, test/e2e/src/diagrams/propertyPanelTestDiagram.ts, test/e2e/src/diagrams/simpleDiagram.ts, test/e2e/src/pages/diagramDetail.ts, test/e2e/src/pages/propertyPanel.ts, test/e2e/src/propertyPanel.spec.ts
This PR adds around 25 tests that test the basic functionality of the Property Panel. 
**Changes:**
1. Add Property Panel Test Diagram
2. Add new Property Panel Test Page
3. Add new Property Panel Tests
1. Run `npm run test-init` in one terminal.
2. Run `npm test` in another terminal.
=> ✅✨Add Basic Property Panel E2E Tests

package.json
**Changes:**
1. Update `bpmn-lint_rules` Dependency
**Related PRs**
https://github.com/process-engine/bpmn-lint_plugin/pull/3
https://github.com/process-engine/bpmn-lint_rules/pull/4
2. Open any diagram.
3. Add a not supported Element.
https://github.com/process-engine/process_engine_runtime/issues/163
4. Activate Linter.
=> ✨Add Rules for not Supported Elements

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Add a refactored version of the diagram name validation.
**Issues:**
Closes #1142 
Closes #1291
Follow the instructions of the linked issue.
Notice that the faulty behavior wont occur on either Windows or macOS.
=> 🐛Fix Diagram Name Validation

src/modules/design/diagram-detail/diagram-detail.ts
**Changes:**
1. Fix deployment of a process.
**Issues:**
Closes #1376
2. Try to deploy a invalid diagram.
3. Try to save it afterwards.
See that the described behavior doesn't occur anymore.
=> 🐛 Fix Deployment of a Process

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/SingleDiagramsSolutionExplorerService.ts
**Changes:**
1. Only display solution name instead of full path
2. Display full path next to solution name
3. Add Tooltips with the full path
4. Refactor CSS class naming of SolutionExplorer
**Issues:**
Closes #1330
PR: #1360
- Open up local solutions
- **Notice that it is now easier to distinguish local solutions**
=> 🚸 Improve Displaying of Solutions

src/modules/custom_elements/modal/modal.html, src/modules/custom_elements/modal/modal.scss, src/modules/live-execution-tracker/live-execution-tracker.html, src/modules/live-execution-tracker/live-execution-tracker.scss, src/modules/live-execution-tracker/live-execution-tracker.ts, test/e2e/src/diagrams/diagramWithCallActivityAndTasks.ts, test/e2e/src/liveExecutionTracker.spec.ts, test/e2e/src/pages/liveExecutionTracker.ts
**Changes:**
1. Always display overlays for CallActivities
2. Refactor LET
3. Fix checking if active elements changed
4. Fix checking if overlays exist
4. Add diagram preview modal
**Issues:**
Closes #1366
PR: #1370
- Run a diagram with a CallActivity
- **Notice that if CallActivity is not active, there is a button for previewing the process model.**
=> 🚸 Always Display Overlays for CallActivities

test/e2e/src/pages/xmlView.ts, test/e2e/src/xmlView.spec.ts
**Changes:**
1. Add Appropriate Tests for XML View
Run the E2E-Tests.
=> ✅✨Add  Appropriate E2E-Tests for XML View

src/contracts/solution-explorer/ISolutionEntry.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
**Changes:**
1. Get PE Version
2. Add PE Version to SolutionEntry Interface
3. Add PE Version to SolutionEntry
4. Show Version of PE on Solutions Title
PR: #1389 
- check the screenshot 
=> ✨Add PE Version to Solution's Title

LICENSE, electron_app/electron.js
**Changes:**
1. Change copyright in electron.js from 2018 to 2019
1. Change copyright in LICENSE from 2017 to 2019
PR: #1388
---
=> ♻️ Change Copyright to 2019

package-lock.json, package.json, src/contracts/bpmnmodeler/ILinting.ts, src/modules/design/bpmn-io/bpmn-io.scss, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/property-panel/indextabs/general/sections/conditional-event/conditional-event.ts, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-task/message-task.ts, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.ts, src/modules/inspect/heatmap/heatmap.ts, src/modules/inspect/inspect.html, src/modules/live-execution-tracker/live-execution-tracker.ts
Waits on:
https://github.com/process-engine/bpmn-elements_contracts/pull/3 
https://github.com/process-engine/bpmn-lint_plugin/pull/4
https://github.com/process-engine/bpmn-js-bpmnlint/pull/2
https://github.com/process-engine/bpmn-io_custom-bundle/pull/16
https://github.com/process-engine/bpmn-lint_rules/pull/5
**Changes:**
1. Update `bpmn-lint_rules` Dependency to use new Rules
2. Update `bpmn-io_custom-bundle` Dependency to use Forked Version of `bpmn-js-bpmnlint` 
3. Refactor TimerEvent Section in PropertyPanel
**Issues:**
Closes #1383 
PR: #1387
1. Start BPMN-Studio
2. Open any Diagram
3. Add an Signal Event
4. Activate the Linter
4.1. There should be an Error on the Undefined SignalEvent
5. Define the Event by Adding a Signal
5.1. The Error should be gone now
(Repeat this for timer, …
=> ✨Add Undefined Rules to Linter

src/contracts/solution-explorer/ISolutionService.ts, src/modules/design/bpmn-diff-view/bpmn-diff-view.html, src/modules/design/bpmn-diff-view/bpmn-diff-view.scss, src/modules/design/bpmn-diff-view/bpmn-diff-view.ts, src/modules/design/design.html, src/modules/design/design.scss, src/modules/design/design.ts, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss, src/services/solution-service/SolutionService.ts, test/e2e/src/diffView.spec.ts, test/e2e/src/pages/diffView.ts
**Changes:**
1. Add getAllSolutions Method
2. Adjust Contracts
3. Add Modal To Select Other Diagrams For Diff View
4. Add openSelectDiagramModal Method
5. Adjust setDiffDestination Method
6. Adjust Diff View
PR: #1331 
- goto the diff view of a process
- click on the second button on the right toolbar
- choose another diagram with the dropdown
- click on compare
=>  ✨Diff Against Other Diagrams

Jenkinsfile
**Changes:**
1. Require `snapcraft-2.41` label for electron builds
**Issues:**
PR: #1409 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> :sparkles: Require Snapcraft Label for Linux Build

package-lock.json, package.json, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.ts
**Changes:**
1. Update `@process-engine/bpmn-lint_rules` Dependency
2. Update Linter on Timer Definition Change
**Issues:**
Closes #1408
1. Open a diagram.
2. Activate the linter.
3. Create a TimerEvent.
4. Select a type.
5. See the new rule in action.
=> ✨Add Timer Defintion Rule

Jenkinsfile, package.json, test/e2e/src/diagrams/diagramWithUserTask.ts, test/e2e/src/diagrams/letTestDiagram.ts, test/e2e/src/diagrams/propertyPanelTestDiagram.ts, test/e2e/src/diagrams/simpleDiagram.ts, test/protractor.conf.js
**Changes:**
1. Run E2E Tests on Dedicated Slave
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/feature%2Flet_e2e_runs_on_other_agent/6/pipeline
=> :construction_worker: Add Agent to E2E Tests

src/modules/design/bpmn-io/bpmn-io.html, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts
**Changes:**
1. The icon of the linter button changes dependent on the lint results.
2. The start-/save-/deploy-button now got correct tooltips.
**Issues:**
Part of: #1405 
1. Open a diagram.
2. Delete the start event.
2.1 Notice that the linter button now shows a cross.
2.2. Notice that the deploy-/start-/save-buttons now have other tooltips.
=> ✨Make Linter More Interactive

src/modules/navbar/navbar.html, src/modules/navbar/navbar.scss, test/protractor.conf.js
**Changes:**
1. Give the center part way more room to show the name of diagram.
2. Show and hide the diagram name correctly.
3. Add a tooltip.
**Issues:**
Closes #1418
1. Open a diagram with a very long name.
1.1. See the new behavior of the navbar.
=> 🐛Fix NavBar Spacing

src/main.ts
**Changes:**
Remove some unused settings that relate to the old ProcessEngine implementation.
PR: #1428
All should work as before.
=> 🔥 Remove unused settings from old PE implementation

package-lock.json, package.json
**Changes:**
Add a linter rule that prohibits the use of gateways with mixed Split- and Join- purpose.
**Issues:**
Closes #1429 
PR: #1431
Try creating a gateway with multiple incoming and multiple outgoing SequenceFlows. This should now cause a linter error.
=> ✨ Add no mixed gateways rule

.github/ISSUE_TEMPLATE.md
**Changes:**
1. Fix Typos in the Issue Template
=> ✏️ Fix Typos in Issue Template

src/modules/live-execution-tracker/live-execution-tracker.html
**Changes:**
1. `Back to previous process` -> `Back to parent process`
1. Start a process with a CallActivitiy.
2. Click on CallActivity in LET.
=> ♻️Rename Navigation Button in LET

src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.ts, src/modules/navbar/navbar.ts
To get myself familiarized with the BPMN Studio, I went ahead and sorted a little through the TaskList and ProcessList of the Dashboard feature and refactored a few things.
I didn't touch any functionality. All refactorings are cosmetic in nature.
---
**Changes:**
1. Refactor ProcessList: 
- Move Properties before functions
- Remove unused public variables `status` and `selectedState`
- Rename `succesfullRequested` to `requestSuccessful`
- Remove unused `getCorrelationsForProcessModel`
- Remove unnecessary `_getCorrelations` wrapper and use `getAllActiveCorrelations` directly
2. Refactor TaskList:
- Rename `succesfullyRequested` to `requestSuccessful`
- Move internal types to the top -> All internal types and interface are now at the same location
- Remove some `try/catch` blocks für …
=> ♻️ Refactor the Dashboards ProcessList and TaskList

dev_tooling/scripts/reinstall_clean_setup.bash, package-lock.json, package.json, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, test/protractor.conf.js
**Changes:**
1. Move the `logged in as` indicator to the left.
2. Make it always visible.
3. Add a clean reinstall script that accounts for the package-lock.
PR: #1435
2. Notice the lock icon is now always visible.
=> ✨ Make Logged In Indicator Always Visible

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Sorts the diagrams of a Solution alphabetically.
**Issues:**
Closes #1424  
PR: #1430
* Create a Diagram with the name _zeta_
* Create a Diagram with the name _alpha_
* Create a Diagram with the name _beta_
* See, that the Diagram names are sorted.
=> ✨Sort the Diagrams in all Opened Solutions

package-lock.json, package.json, src/modules/design/diagram-detail/diagram-detail.ts
**Changes:**
Apply a fix for the ProcessEngineRuntime, which prevented the use of the `inputValues` property for events that use signals and messages.
PR: #1440
- Create a ProcessModel that has a StartEvent that waits for a message or signal.
- Create a ProcessModel that uses  an `EndEvent` or `IntermediateThrowEvent` that sends the expected mesage or a signal.
- Attach an `inputValues` property to the triggering event that performs some kind of token mapping.
- Run the ProcessModel that uses the triggering event.
- When the ProcessModel with the StartEvent gets run, see that it received the correct payload.
=> ✨ Allow for customized event payloads

src/modules/design/bpmn-io/bpmn-io.ts
**Changes:**
1. Fix Bug Where Linter Summary is Not Updated Automatically
**Issues:**
Closes #1441 
PR: #1442 
- see #1441
- also fixes the bug where the linter button is white after switching to another diagram 
=> 🐛 Fix Bug Where Linter Summary is Not Updated Automatically

package-lock.json, package.json
**Changes:**
1. Disable Timer Validation
PR: #1453
- Open a diagram with a TimerEvent
- **Notice that the timer definition will no longer be validated.**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre> …
=> 🐛 Disable Timer Validation

package-lock.json, package.json
Fix an issue with the ProcessEngineRuntime, which prevented a user from stopping ProcessInstances that start with a `TimerStartEvent`.
Closes #1461
PR: #1465
1. Try starting ProcessModels that contain the various types of TimerStartEvents (Duration, Date, Cyclic)
2. The following UseCases should produce an error right at the beginning:
- A cyclic timer is used (these are currently not supported)
- A past date is used with a Date-timer
- An invalid format is used for a Duration-timer
3. Try stopping a ProcessInstance that started successfully
4. You'll see that the ProcessInstance gets finished properly now
=> 🐛 Fix handling of TimerStartEvents

Jenkinsfile
Manual cherry-pick of
https://github.com/process-engine/process_engine_runtime/commit/c2f60e57d821388971a46d7de57846a6fdf0cbba#diff-58231b16fdee45a03a4ee3cf94a9f2c3
=> Fix Wrong Usage of Credential Store

src/contracts/bpmnmodeler/ICanvas.ts, src/modules/design/bpmn-diff-view/bpmn-diff-view.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-tools-right/diagram-tools-right.ts, src/modules/inspect/heatmap/heatmap.ts, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/live-execution-tracker/live-execution-tracker.ts
Fixes a call to BPMN.io's canvas.zoom() to fit the diagram as intended.
---
**Changes:**
1. Fix zoom when opening diagrams
**Issues:**
Closes #Issue
Closes #Issue
Closes (...)
---
1. Diagramm öffnen
2. Freude
<details>
<summary>
:warning: Before merging please click here to expand …
=> Fix zoom when opening diagrams

package.json, test/jenkins_e2e.sh
1. Pin Webdriver-Manager
2. Update Webdriver-Manager
3. Pin Chrome Version Used by 'Webdriver-Manager'
PR: #1475 
Look at the Jenkins build
=> :twisted_rightwards_arrows: :bug: Fix E2E Tests

src/modules/design/diagram-detail/diagram-detail.ts
1. Navigate to Remote Diagram After Deploy.
Closes #1469 
PR: #1468 
- open diagram from file system
- deploy it to a remote process engine
- realize that you are now able to click on the play button
=> ✨ Navigate to Remote Diagram After Deploy

Jenkinsfile, package-lock.json, package.json
Update the Runtime to apply a fix for resuming FlowNodes with multiple FlowNodeInstances in a single ProcessInstance.
Part of https://github.com/process-engine/process_engine_runtime/issues/332
PR: #1478
Follow the steps described in the referenced issue.
=> 🐛 Fix resumption of FlowNodes with multiple FlowNodeInstances

package-lock.json, package.json
Fixes the resumption of `ParallelJoinGateways`.
See [here](https://github.com/process-engine/process_engine_runtime/pull/342) for full changelog.
Part of https://github.com/process-engine/process_engine_runtime/issues/245
PR: #1481
Resuming a ProcessInstance that got interrupted while executing parallel branches should now be possible.
=> 🐛 Apply fix for ParallelJoinGateway resumption

src/modules/design/property-panel/indextabs/general/sections/pool/pool.html, src/modules/design/property-panel/indextabs/general/sections/pool/pool.scss, src/modules/design/property-panel/indextabs/general/sections/pool/pool.ts
1. Add Checkbox to ID Input
2. Add Modal to Show Information
Closes #1480 
PR: #1479 
- open a diagram
- select the pool
- try to edit the ID
=> ✨Make Process ID Editable

package.json, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/process-list/process-list.ts
1. Add Created At Column to Correlation Table
2. Fix Bug Where The Polling did not Work
3. Sort Correlations By Created At
Closes #1452
PR: #1484 
=> ✨Add createdAt Column and Sort Correlation-List

src/modules/design/design.ts
1. Fix Bug Where Starting Processes is Not Possible
Closes #1488 
PR: #1487 
look at the referenced issue
=> 🐛 Fix Bug Where Starting Processes is Not Possible

package-lock.json, package.json, src/main.ts, src/modules/inspect/inspect-correlation/contracts/IInspect-correlation.repository.ts, src/modules/inspect/inspect-correlation/contracts/IInspect-correlation.service.ts, src/modules/inspect/inspect-correlation/inspect-correlation.html, src/modules/inspect/inspect-correlation/repositories/inspect-correlation.repository.ts, src/modules/inspect/inspect-correlation/services/inspect-correlation.service.ts, src/modules/inspect/token-viewer/contracts/ITokenViewerRepository.ts, src/modules/inspect/token-viewer/contracts/ITokenViewerService.ts, src/modules/inspect/token-viewer/contracts/index.ts, src/modules/inspect/token-viewer/index.ts, src/modules/inspect/token-viewer/repository/token-viewer.repository.ts, src/modules/inspect/token-viewer/service/token-viewer.service.ts, src/modules/inspect/token-viewer/token-viewer.ts, src/modules/live-execution-tracker/live-execution-tracker.html
**Changes:**
1. Updates Interfaces
2. Use the Correct Method to Fetch Tokens 
3. Fix Showing all Tokens of a Process Instance ID
**Issues:**
Closes #1464 
PR: #1450 
look at the linked issue.
you can use this example process for testing:
[test_tokenviewer.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/3182571/test_tokenviewer.bpmn.zip)
=> 🐛Token Viewer Fix

src/contracts/dynamic-ui/IDynamicUiService.ts, src/modules/live-execution-tracker/contracts/ILiveExecutionTracker.Repository.ts, src/modules/live-execution-tracker/contracts/ILiveExecutionTracker.Service.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/repositories/live-execution-tracker.repository.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts, src/services/dynamic-ui-service/dynamic-ui.service.ts
1. Fix Initialization of Events
2. Fix Getting Tasks in Dynamic UI
Closes #1449 
PR: #1479 
- Run a diagram with a custom correlation ID
- Run the same diagram with the same custom correlation ID
- **Notice that the LET is still working correctly**
- Run a diagram with a user task with a custom correlation ID (Don't finish the user task)
- Run the same diagram with the same custom correlation ID
- Finish the user task
- **Notice that the user tasks will be finished in the LET**
=> 🐛Fix LET Event Initialization; 🐛 Fix Getting Tasks in Dynamic UI

src/app.scss, src/modules/config-panel/config-panel.html, src/modules/design/design.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/pool/pool.html, src/modules/inspect/task-list/task-list.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.html, src/modules/status-bar/status-bar.html
1. Primary buttons are now marked by color
Closes #334 
PR: #1504
=> Mark primary buttons with btn-primary

src/modules/design/bpmn-io/bpmn-io.ts
1. Remove Wrench of Pool Contextpad
Closes #699
PR: #1494 
- select a pool of a diagram
- try to collapse the pool
- see that there is no option to collapse it
=> ✨ Remove Wrench of Pool Contextpad

src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/design/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.ts
1. Fix edited bug for ErrorEvents.
2. Fix edited bug for EscalationEvents.
3. Fix edited bug for SignalEvents.
Closes #1483 
PR: #1508 
=> 🐛Fix Edited Bug

src/modules/navbar/navbar.html, src/modules/navbar/navbar.scss, src/modules/navbar/navbar.ts
1. Fix navbar on windows and fullscreen
Closes #YourIssueNumber
PR: #1509
=> Fix navbar on windows and fullscreen

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/services/solution-service/SolutionService.ts
1. Find the correct index of a diagram
2. Fix bug where the opened diagram has been removed from local storage
Closes #1473 
PR: #1511 
- try to reproduce the behaviour of #1473
=> 🐛Fix File Association

src/modules/design/property-panel/indextabs/general/sections/basics/basics.html
1. Fix bug where editing docs of a diagram is possible on remote solutions
Closes #1521 
PR: #1519 
Have a look at the issue
=> 🐛 Fix bug where editing docs of a diagram is possible on remote solutions

electron_app/electron.js, package-lock.json, src/modules/live-execution-tracker/contracts/ILiveExecutionTracker.Repository.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Show loading spinner on solution if ProcessEngine is not available
Closes #1129
PR: #1506 
=> ✨ Start the studio only when the internal process engine is started

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix opening diagrams in browser
Closes #1523
PR: #1524
- Try to open a diagram
- **Notice that the diagram will be opened**
=> 🐛 Fix Opening Diagrams in Browser

src/modules/design/bpmn-io/bpmn-io.ts, src/services/diagram-creation-service/DiagramCreationService.ts
1. Update the XML which is used to create new diagrams.
Closes #1527 
PR: #1526 
=> 🐛 Diagram Creation XML

package-lock.json, src/main.ts, src/modules/design/bpmn-io/repositories/DiagramExportRepository.ts, src/modules/inspect/process-list/process-list.ts, src/services/notification-service/notification.service.ts, tsconfig.json
1. Add esModuleInterop flag to tsconfig
2. Fix web version
3. Fix moment import statement
4. Fix downloadjs import statement
5. Fix toastr import statement
Closes #1530 
PR: #1513 
- the BPMN-Studio should work as expected
=> 🐛Fix web version

src/contracts/solution-explorer/ISolutionEntry.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
1. Add button to collapse/expand the opened solutions
Closes #1512 
PR: #1529 
=> ✨Make Solutions Collapsible

src/contracts/bpmnmodeler/IBpmnModeler.ts, src/modules/live-execution-tracker/live-execution-tracker.ts
1. Fixes initial zoom bug in LET
Closes #1515 
PR: #1517
* open LET
* rejoice
=> 🐛Fix initial zoom on diagram in LET

electron_app/electron.js, src/contracts/diagram/IDiagramStateList.ts, src/contracts/diagram/IDiagramStateListEntry.ts, src/contracts/diagram/index.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/inspect/inspect.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/start-page/start-page.ts, src/modules/think/think.ts, src/services/solution-explorer-services/OpenDiagramStateService.ts
1. Improve file menu
2. Disable Save As on Remote Solution
PR: #1522
- Use the file menu
- Test the shortcuts displayed in the file menu.
=> ✨ Improve File Menu

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/design/property-panel/property-panel.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts
1. Add Untitled Diagram Functionality
2. Fix 'Save As' When Replacing An Open Diagram
3. Fix an Error Message in the Solution Explorer List
Closes #1401 
PR: #1535
- Hit CMD/CTRL+N
- **Notice that a new diagram will be created in the 'Open Diagrams' Solution**
- Save the file
- **Notice that the 'Save As' functionality will be used to save the diagram**
=> ✨ Add Untitled Diagram Functionality

src/modules/live-execution-tracker/live-execution-tracker.ts
1. Fix Continuing Tasks
Closes #1543
PR: #1544
- Start a process with an `User Task` or `Manual Task`
- Go to `Inspect`
- Click on the "Continue"-button of the task
- **Notice that the LET will open with the DynamicUI with the data of the continued task**
=> 🐛 Fix Continuing Tasks

src/modules/design/bpmn-io/bpmn-io.html, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/property-panel/property-panel.ts
1. Fix Changing Diagram in Modeler
2. Fix Changing Diagram in PropertyPanel
PR: #1547
- Switch between diagrams
- Deploy a diagram
- Switch between the deployed version and the local version
- Change something in the local version
- Switch between the deployed version and the local version
- Deploy the changed diagram
- Switch between the deployed version and the local version
- **Notice that the diagrams should be displayed correctly, the state of the local version gets loaded correctly and the correct element will be displayed in the property panek**
=> 🐛 Fix Changing Diagram

package-lock.json, package.json
1. Update the custom bundle to get the latest version of bpmn-js and diagram-js.
PR: #1545
- test whether the design view works as expected
=> ⬆️Update custom bundle

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Move Selecting Protocol to Dropdown
PR: #1540
- Try to add a remote solution
- **Notice that there is a dropdown, which has to be used to define the protocol**
=> ✨ Move Selecting Protocol to Dropdown

src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.ts
1. Fix Process List
Closes #1436
Closes #1548 
PR: #1549
- Run many processes with the same correlation id
- Go to dashboard (Inspect)
- **Notice that there are only 10 entries in the process list**
=> 🐛 Fix Process List

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html
1. Hide Diagrams of Disconnected Remote Solution
PR: #1552
- Connect to a remote solution
- Shut down the remote solution
- **Notice that the diagrams of the remote solution are no longer displayed.**
=> 🐛 Hide Diagrams of Disconnected Remote Solution

aurelia_project/aurelia.json, package-lock.json, package.json
1. Remove aurelia-fetch-client
2. Remove fetch-ponyfill
3. Remove whatwg-fetch
Closes #1314 
PR: #1557
- check whether the studio can make requests like before (browser and electron)
=> 🔥Remove unused fetch clients

src/modules/inspect/dashboard/dashboard.scss, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.scss, src/modules/inspect/task-list/task-list.ts
1. Fix style of pagination on process-list
2. Fix style of pagination on task-list
Closes #1555 
PR: #1559
look at #1555 
now the pagination should look like:
=> 💄Fix Pagination Style

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix highlighting diagrams name on SolutionExplorer
Closes #1568 
PR: #1569 
look at #1568
=> 🐛 Fix highlighting diagrams name on SolutionExplorer

Jenkinsfile
Move versioning to `find_available_version_for_publish`. 
This function will keep trying `npm version`, until a version is found that is available on npm. 
Note that this is only done on `develop` and `feature` branches. The master is not affected.
PR: #1572
Kinda hard to test, as this error only happened sporadically. 
We'll just have to see how this will perform in the long run.
=> 👷 Fix "you cannot publish over existing version" issue

src/modules/design/diagram-detail/diagram-detail.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Closing All Diagrams
Closes #1570
PR: #1571
- Open some unsaved diagrams
- Hit CMD/CTRL+Alt+W
- **Notice that all diagrams should be closed correctly.**
=> 🐛 Fix Close All Diagrams

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Add some improvements for #1567
Closes #1573 
PR: #1573 
=> 👌🏼Add some improvements for #1567

fixtures/Heatmap Test.bpmn, fixtures/boundary_event_timer_test.bpmn, fixtures/call_activity_subprocess.bpmn, fixtures/call_activity_subprocess_error.bpmn, fixtures/call_activity_subprocess_nested.bpmn, fixtures/call_activity_test.bpmn, fixtures/call_activity_test_error.bpmn, fixtures/error_end_event_call_activity_called_process.bpmn, fixtures/error_end_event_subprocess_call_activity_test.bpmn, fixtures/intermediate_event_link_test.bpmn, fixtures/receive_task_wait_test.bpmn, fixtures/send_task_throw_test.bpmn, fixtures/user_task_parralel_test.bpmn
1. Add some test diagrams
Closes #391 
PR: #1583 
For some diagrams, you must start them with an initial StartEvent token to run them correctly
=> ✨Add first fixtures

Jenkinsfile, package-lock.json, package.json
Fix an issue with the internal ProcessEngine, which could cause it to be unavailable, when a TimerEvent was misconfigured.
See: 
https://github.com/process-engine/process_engine_runtime/releases/tag/v8.4.1
PR: #1585
- Upload a ProcessModel with any kind of TimerEvent that is missing a CamundaProperty `enabled`
- Restart the Studio
- See that you'll get a list of your ProcessModels
=> 🐛 Fix timer event parsing

Jenkinsfile, azure-pipelines.yml, package-lock.json, package.json
Interner Test zur Umstellung von `npm install` auf `ci_tools npm-ci-except @process-engine/ @essential-projects/`
PR: #1587
=> Add ci_tools in Jenkinsfile

src/modules/inspect/cronjob-list/cronjob-list.html, src/modules/inspect/cronjob-list/cronjob-list.scss, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.scss
1. Add total count to cronjob list
2. Add total count to process list
3. Add total count to task-list
Closes #1597 
PR: #1602 
- Navigiere zur Inspect Ansicht
Positionierungs- und Stylevorschläge sind erwünscht.
=> ✨Add total count to dashboard

src/modules/inspect/cronjob-list/cronjob-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.scss, src/modules/inspect/process-list/process-list.html, src/modules/inspect/task-list/task-list.html
1. Decrease headlines on dashboard
2. Decrease headline on inspect-correlation tables
Closes #1072 
PR: #1610 
- look at the tables on inspect-correlation (correlation list and log viewer)
- look at the dashboard
=> 💄Reworking unify font size

aurelia_project/environments/dev.ts, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.html, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.scss, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/inspect/inspect-correlation/inspect-correlation.html, src/modules/inspect/inspect-correlation/inspect-correlation.ts
1. Add loading spinner
Closes #1595 
PR: #1604 
- create a large database
- goto the inspect correlation view
- switch between some diagrams
=> ✨Loading spinner Inspect-Correlation

electron_app/electron.js, package-lock.json, package.json
1. Set default ports for "dev", "alpha", "beta", "stable" bpmn-studio versions
Closes #1625 
PR: #1624 
=> ✨Set default ProcessEngine ports

Jenkinsfile, electron-builder/alpha/electron-builder.yml, electron-builder/set-name-in-package-json.js, electron-builder/stable/electron-builder.yml
1. Set artefact name for stable and alpha
2. Adjust Jenkinsfile for uploading artefacts
Closes #YourIssueNumber
PR: #1634 
=> 🐛Fix latest yaml

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Add Default Remote Solution Discovery
PR: #1636
- Start some versions of the BPMN-Studio
- Click on the 'Open remote solution' Button
- **Notice that the remote solutions of the other BPMN-Studio versions will be displayed.**
=> ✨ Add Default Remote Solution Discovery

aurelia_project/aurelia.json, package-lock.json, package.json
1. Update Runtime
PR: #1639
- Check if the runtime related stuff is still working
=> ⬆️ Update Runtime to 8.5.0-alpha.5

package.json
1. Move the postinstall script to electron-prepare
Closes #1612 
PR: #1645 
- `npm i -g bpmn-studio@feature~fix_npm-package`
- `bpmn-studio`
=> 🐛 Fix installing the npm package

package-lock.json, package.json, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
1. Add semver package
2. Add tooltips to expand and collapse icon
3. Add information icons to the solutions
4. Add modals for the information icons
Closes #1400 
PR: #1643 
- start a pe runtime with an older major package version than 8 and one newer than 8
- connect to the runtimes
- see the information icons
- click on the information icons
=> ✨Check the runtime version and display information icons

src/modules/design/bpmn-diff-view/bpmn-diff-view.html, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/inspect/heatmap/heatmap.html, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.html, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/live-execution-tracker/live-execution-tracker.html
1. Select Flow Nodes via Bpmnjs in Inspect Correlation
2. Fix Displaying Selection for Viewer
PR: #1659
- Go to inspect-correlation
- Select any element
- **Notice that the element is no longer colored, but the default selection marker is displayed.**
=> ♻️ Select Flow Nodes via Bpmnjs in Inspect Correlation

src/modules/design/diagram-detail/diagram-detail.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Closing Unsaved Diagrams
Closes #1664  
PR: #1665
- Close the diagram via the SolutionExplorer
- Click on "Save"
- **Notice that the diagram is closed.**
=> 🐛 Fix Closing Unsaved Diagrams

src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Refactor Error Handling in 'Open Remote Solution' Modal
2. Display Error if Remote Solution is Not Responding
Closes #1651 
PR: #1656
- Connect to a uri that is not responding.
- **Notice that the modal won't close and an error message appears in the modal after a few seconds.**
- Connect to a remote solution that is responding
- **Notice that the modal will close and the remote solution is connected.**
=> ♻️ Refactor Error Handling in 'Open Remote Solution' Modal

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix SolutionExplorer performance bug
Before:
After:
Closes #1671 
PR: #1673 
- open several diagrams (at least 50)
- scroll through the SolutionExplorer
- open a diagram and move it
=> 🐛Fix solution explorer performance

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Fix Opening Persisted Diagrams
PR: #1672
- Remove the diagram from the filesystem
- Reload/Restart the Studio
- **Notice that no error will be logged anymore.**
=> 🐛 Fix Opening Persisted Diagrams

src/modules/live-execution-tracker/contracts/ILiveExecutionTracker.Service.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts
1. Fix Colorizing Diagrams via LiveExecutionTrackerService
2. Refactor Usage of Modeler in LiveExecutionTrackerService
Closes #1598
PR: #1669
- Open [this](https://github.com/process-engine/bpmn-studio/files/3524065/bug.bpmn.zip) diagram
- Deploy it
- Start it
- **Notice that there is no error notification.**
=> 🐛 Fix Colorizing Diagrams via LiveExecutionTrackerService

src/modules/design/bpmn-diff-view/bpmn-diff-view.ts, src/modules/design/design.ts, src/modules/status-bar/status-bar.ts
1. Fix Switching Diagrams in Diff View
2. Fix Setting Diff Buttons
3. Improve Code Quality of Diff Viewer
Closes #1674 
PR: #1683
- Go to the Diff View
- Switch between diagrams via solution explorer
- Switch between diff modes
- Switch between target diagrams via 'diff against other diagrams'
- **Notice that the diagram viewer get always updated correctly and the lower diagram is always correctly colored**
=> 🐛 Fix Diff View

src/modules/design/property-panel/property-panel.ts
1. Fix bug where PropertyPanel shows wrong tabs
Closes #1675 
PR: #1679 
- look at the referenced issue
=> 🐛Fix property panel bug

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss
1. Fix style bug where the last solution is not displayed correctly
Closes #1677 
PR: #1678 
- look at the referenced issue
=> 🐛 Fix style bug where last solution is not displayed correctly

src/modules/design/bpmn-io/bpmn-io.ts
1. Fix bug where all participants have the same process id which occurs XML errors
Closes #1701
PR: #1700 
=> 🐛Fix multiple participant bug

src/modules/design/bpmn-io/bpmn-io.scss
1. Fix Scrolling in Property Panel
Closes #1698 
PR: #1699 
- Increase the size of the docs input untill it is bigger than the property panel
- **Notice that the property panel can be scrolled.**
=> 🐛 Fix Scrolling in Proprety Panel

src/contracts/diagram/IDiagramState.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.html, src/modules/design/diagram-detail/diagram-detail.html, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/design/property-panel/property-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/OpenDiagramStateService.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts
1. Fix Saving Viewbox State When in Diff View
2. Update Viewbox State on Viewbox Change
Closes #1686
PR: #1687
- Go to diff view
- Switch between diagrams
- Go back to modeler
- **Notice that the diagram will now be displayed correctly.**
=> 🐛 Fix Saving Viewbox State When in Diff View

src/app.ts
1. Add Migrations for DiagramState
PR: #1702 
- Open the Studio with old diagram states
- **Notice that open diagrams will still work.**
=> ✨ Add Migrations for DiagramState

aurelia_project/environments/dev.ts, src/contracts/diagram/DiagramStateChange.ts, src/contracts/diagram/IDiagramState.ts, src/contracts/diagram/index.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/OpenDiagramStateService.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts
1. Use LocalStorage to Detect if BPMN Studio Changed Files
2. Refactor Saving of DiagramState
PR: #1704
- Open a diagram from a remote solution
- Hold down CMD/CTRL + S for a few seconds
- **Notice that no notification will be displayed anymore.**
=> 🐛 Improve Detection of Diagram Changes

src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html
1. Avoid Navigating after Deleting Inactive Diagram
Closes #1703
PR: #1705
- Remove another diagram
- **Notice that the diagram won't change**
- Remove the opened diagram
- **Notice that diagram will change.**
=> 🐛Avoid Navigating after Deleting Inactive Diagram

src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts
1. Select Previously Selected FlowNode or StartEvent
2. Add FlowNode Selection Via Arrow Keys
Closes #1071
PR: #1657
- Go to the inspect correlation
- Select an element
- Switch to another process instance with the same element
- **Notice that the element will still be selected.**
- Switch to another process instance without the same element
- **Notice that the start element will be selected.**
- Use the arrow keys
- **Note that the selected element changes depending on which arrow key is pressed.**
=> ✨ Improve FlowNode Selection in Inspect Correlation

electron_app/electron.ts, src/app.ts, src/main.ts, src/modules/design/bpmn-io/bpmn-io.html, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/user-preferences/user-preferences.html, src/modules/user-preferences/user-preferences.scss, src/modules/user-preferences/user-preferences.ts, src/services/user-config-service/index.ts, src/services/user-config-service/userconfig.service.ts
Changes
1. Add UserConfigService
2. Add user-preferences page
3. Use UserConfigService to disable/enable linter
Closes #1690 
PR: #1689 
- open a diagram on the design view
- see that the linter is active 
- open the preferences
- paste `{ "activateLinter": false }` into the input 
- save
- open another diagram on the design view 
- see that there is no linter button
=> ✨Add first draft of user config

electron_app/electron.ts, package-lock.json, package.json
1. Use Own Electron Updater
2. Fix Updating Beta and Alpha
Closes #1640
PR: #1707
-  Run:
```
gco 12d0e50
npm i
npm run build
npm run electron-start-dev
```
- **Notice that the autoupdater will try to update to `beta.2`**
=> ✨ Use Own Electron Updater

src/modules/inspect/inspect-correlation/inspect-correlation.scss
1. Fix TokenViewer style bug
Closes #1713 
PR: #1714 
- reproduce the described steps in #1713
=> 🐛 Fix TokenViewer style bug

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/OpenDiagramStateService.ts
1.  Fix Diagram Changes Indicator
Closes #1718 
PR: #1720
- Create two new diagrams in a local solution with names like "test" and "test a" or "abc" and "abc def"
> It is important that the names are the same up to the first space.
> You can also create only one diagram and duplicate it using the context menu.
- Make sure they are not opened as open diagrams
- Open one of them
- Add some changes
- Open the other one
- **Notice that the diagram indicator from the changed diagram will disappear.** 
or
- Add some changes
- Deploy the diagram (without saving)
- **Notice that the diagram indicator from the local diagram will disappear.**
=> 🐛 Fix Diagram Changes Indicator

package.json
1. Set Version to '5.8.0'
PR: #1722
=> 🔖 Set Version to '5.8.0'

src/app.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/services/expose-functionality-module/expose-functionality-module.ts, test/integration/TestClient.ts, test/integration/smoke.spec.ts
1. Add a module which exports two functions. One function to expose functions for the test client and one function to call the exposed function with the test client.
2. Fix the test (paths)
PR: #1719 
- check whether the open a solution and save diagram tests are working
=> ✨Add expose functionality module

package.json, test/integration/get-path-and-run-tests.ts
1. Change from JS to TS
PR: #1721 
- all should work as before
=> ✨ Use TS instead of JS on get-path-and-run-tests

aurelia_project/environments/dev.ts, src/modules/deploy-modals/deploy-modals.html, src/modules/deploy-modals/deploy-modals.ts, src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/services/deploy-diagram-service/deploy-diagram.service.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts
1. Stop Closing Open Diagram on Delete
Closes #1694
PR: #1724
- Open some diagrams (you need open diagrams)
- Delete a diagram that is not opened
- **Notice that the last open diagram will no longer get closed.**
=> 🐛 Stop Closing Open Diagram on Delete

src/modules/design/design.ts
1. Fix Showing Diff View on Remote Solution
Closes #1726 
PR: #1727
- Open a diagram from a remote solution
- Click on 'Show Diff'
-  **Notice that the diff view will be displayed.**
=> 🐛 Fix Showing Diff View on Remote Solution

src/modules/inspect/cronjob-list/cronjob-list.html, src/modules/inspect/cronjob-list/cronjob-list.scss, src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/dashboard/dashboard.html, src/modules/inspect/dashboard/dashboard.ts, src/modules/inspect/inspect.ts, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.scss, src/modules/inspect/task-list/task-list.ts
The first step to improve the performance of the inspect/dashboard view
1. Refactor cronjob-list
2. Refactor process-list
3. Refactor task-list
4. Remove unnecessary claim checks from the dashboard
Part of #1594 
PR: #1733 
- create a large database
- navigate to inspect
- see that there is no white window for some seconds
=> ♻️ Improve performance of inspect/dashboard

package-lock.json, package.json
> **Please ensure you have followed this guide, _before_ submitting your PR!**
>
> - Prefix the PR title according to the [gitmoji guide](https://gitmoji.carloscuesta.me/).
> - Reference all PRs and issues relevant for this PR.
> - **Be sure that you have reviewed and tested every change you made here!**
>     - If you're not sure how you can test your changes, don't hesitate to contact us!
> - List all fixed/closed issues here with `Closes #123` or `Fixes #123`.
>     - **If no issue for this PR exists, please consider creating one!**
>     - Of course, if this just fixes a typo, linter error or is something equally simple, no issue is required.
> - Add the number of this PR to this PRs body, so you can add it to the commit message.
> This will allow us to create a nice changelog for the …
=> Update ci_tools to 2.0.0

aurelia_project/environments/dev.ts, src/app.ts, src/modules/design/bpmn-io/bpmn-io.scss, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.ts
1. Fix Style of DJS-Palette
Closes #1734
PR: #1737
- Go to detail view
- Toggle the SolutionExplorer
- **Notice that the djs-palette will be displayed correctly.**
=> 🐛 Fix Style of DJS-Palette

src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.scss, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html
1. Add Enlarge Button for Script Task
Closes #1661
PR: #1738
- Open a diagram with a script task
- Select the script task
- Click on the enlarge button
=> ✨ Add Enlarge Button for Script Task

electron_app/electron.ts, package-lock.json, package.json, src/app.ts
1. Add Database Export
PR: #1746
- Click on the `help` entry in the electron menubar
- Click on `Export Databases`
- Select a path where the databases should be saved
- **Notice that the databases get zipped and saved to the selected path.**
=> ✨ Add Database Export

electron_app/electron.ts
Ordnet Menüeinträge neu und fügt einen Menüeintrag hinzu, mit dem man leicht zu dem Ordner navigieren kann, in den man die exportierten Datenbanken hineinkopieren muss.
=> ✨ Add menu entry for opening database folder

src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts
1. Fix bug where the default-value of boolean form-fields is not displayed correctly
Closes #1759 
PR: #1763 
- try to reproduce #1759
=> 🐛Fix default boolean value bug

package.json, src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/dashboard/contracts/IDashboardRepository.ts, src/modules/inspect/dashboard/contracts/IDashboardService.ts, src/modules/inspect/dashboard/contracts/TaskListEntry.ts, src/modules/inspect/dashboard/contracts/TaskSource.ts, src/modules/inspect/dashboard/contracts/constants.ts, src/modules/inspect/dashboard/contracts/index.ts, src/modules/inspect/dashboard/dashboard-repositories/IDashboardRepository.ts, src/modules/inspect/dashboard/dashboard-repositories/dashboard-pagination-repository.ts, src/modules/inspect/dashboard/dashboard-repositories/dashboard-repository.ts, src/modules/inspect/dashboard/dashboard-service/dashboard-service.ts, src/modules/inspect/dashboard/index.ts, src/modules/inspect/heatmap/repositories/heatmap.mock.repository.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts, src/modules/management-api_client/index.ts, src/modules/task-list-container/task-list-container.ts, src/services/dynamic-ui-service/dynamic-ui.service.ts
1. Use getAllSuspendedTasks
Related to #1594
Related to https://github.com/process-engine/process_engine_runtime/issues/380
PR: #1744
- Go to the inspect view
- **Notice that the task list still get displayed correctly.**
> Do the same with the current ProcessEngine version
=> ⚡️Use getAllSuspendedTasks

electron_app/electron.ts
1. Fix Usage of Auto Updater
Closes #1776 
PR: #1777
- Change the version to 5.8.0 in 'package.json'
- Build  & install the BPMN Studio
- Run the BPMN Studio
- **Notice that no update message will be displayed.**
=> 🐛 Fix Usage of AutoUpdater

package-lock.json, src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/dashboard/contracts/IDashboardRepository.ts, src/modules/inspect/dashboard/contracts/IDashboardService.ts, src/modules/inspect/dashboard/dashboard-repositories/dashboard-repository.ts, src/modules/inspect/dashboard/dashboard-service/dashboard-service.ts, src/services/process-engine-version-module/process-engine-version-module.ts
1. Use events to update cronjobs
Part of https://github.com/process-engine/process_engine_runtime/issues/390
Part of #1594 
PR: #1739 
- open the dashboard view where you can see the cronjob list
- now the cronjob list should get updated when you create, update, stop, execute or remove a cronjob/diagram with a cycle timer start event
=> ✨Add cronjob events

src/modules/design/bpmn-io/bpmn-io.html, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/property-panel/property-panel.ts
1. Fix Updating Selected Element
Closes #1787 
PR: #1792
- Switch between a deployed diagram and the local version of the same diagram
- **Notice that the property panel gets updated correctly.**
=> 🐛Fix Updating Selected Element

.github/workflows/continuous-integration-workflow.yml, src/modules/navbar/navbar.ts
1. Fix bug where the wrong active solution is set when navigating to preferences
PR: #1794 
- open a diagram from the filesystem on design view
- navigate to preferences
- click on design 
- see that it works
=> 🐛Fix bug where the wrong active solution is set when navigating to preferences

src/modules/inspect/inspect-correlation/inspect-correlation.html, src/modules/inspect/token-viewer/token-viewer.ts, src/modules/live-execution-tracker/live-execution-tracker.html
1. Fix Token Viewer
Closes #1797
PR: #1798
- Start a diagram
- Click on the StartEvent
- **Notice that the Token Viewer will work correctly.**
=> 🐛 Fix Token Viewer

package-lock.json, package.json, src/modules/design/property-panel/indextabs/general/repository/general.repository.ts, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.scss, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/design/property-panel/indextabs/general/service/general.service.ts
1. Allow to select startevents of callactivity
Closes #1764 
PR: #1795 
- Open a diagram with a CallActivity
- Click on the CallActivity
- Select a Process
- Select a Start Event
- Enter a payload
=>  ✨Allow startevent selection for callactivities

src/modules/design/diagram-detail/repository/diagram-detail.repository.ts, src/modules/inspect/inspect-correlation/repositories/inspect-correlation.repository.ts
1. Rename ManagementApiService to ManagementApiClient
Closes #1767 
PR: #1782
=> ♻️ Rename ManagementApiService to ManagementApiClient

electron_app/electron.ts, package-lock.json, package.json
1. Persist Window State
Closes #1793 
PR: #1802
- Open the BPMN Studio
- Resize the window
- Close the BPMN Studio
- Open the BPMN Studio
- **Notice that the previous window state will be recovered.**
=> ✨ Persist Window State

src/modules/inspect/cronjob-list/cronjob-list.html, src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.ts, src/modules/pagination/pagination.html, src/modules/pagination/pagination.scss, src/modules/pagination/pagination.ts
1. Create Own Pagination
Closes #1791 
PR: #1805
- Check if the pagination is still working for the `process-list` (dashboard), `task-list` (dashboard), `cronjob-list` (dashboard) and `correlation-list` (inspect-correlation).
=> ✨ Create Own Pagination

package-lock.json, package.json
1. Update the ProcessEngine Runtime to fix a bug in the post migrations script
PR: #1809
=> 🐛Fix postmigrations

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
1. Fix Connecting Remote Solution to Studio without Internal Solution
Closes #1814 
PR: #1816
- Run the BPMN Studio via `npm run start_dev`
- Go to `localhost:9000`
- Try to connect a remote solution
- **Notice that connecting a remote solution works.**
=> 🐛 Fix Connecting Remote Solution to Studio without Internal Solution

src/modules/live-execution-tracker/live-execution-tracker.scss, src/modules/live-execution-tracker/live-execution-tracker.ts
1. Fix LET Overlay Placement
Closes #1812 
PR: #1813
- Open a diagram with a task that creates an error, with an User-/ManualTask or with an EmptyActivity
- Resize the task
- **Notice that the overlays are still centered.**
=> 💄 Fix LET Overlay Placement

package-lock.json, package.json, src/modules/fetch-http-client/http-fetch-client.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Set `Content-Type` for Requests
Related to https://github.com/process-engine/process_engine_runtime/pull/447
PR: #1796
- The internal ProcessEngine should be loaded.
=> ♻️ Set `Content-Type` for Requests

src/modules/config-panel/config-panel.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Support Connecting Embedded Runtimes
Closes #1785
PR: #1821
- Connect a runtime >= v9.1.0-beta.2 or >= v9.1.0-beta.6 (e.g. internal PE of latest BPMN Studio Beta or latest BPMN Studio Alpha)
- **Notice that it works & the PE version gets displayed correctly when hovering above its name.**
- Connect a runtime < v9.1.0-beta.2 or < v9.1.0-beta.6 (e.g. internal PE of latest BPMN Studio Stable)
- **Notice that it works & the PE version gets displayed correctly when hovering above its name.**
=> ✨ Support Connecting Embedded Runtimes

electron_app/electron.ts, src/modules/navbar/navbar.ts
1. Fix Navbar When Switching Fullscreen Mode
2. Fix Navbar in Browser On Mac 
Closes #1823 
PR: #1826
- Enter fullscreen mode
- Close fullscreen mode
- **Notice that the navbar content is placed correctly.**
- Open the web version of the BPMN Studio on macOS
- **Notice that the navbar content is placed  .**
=> 🐛 Fix Navbar When Switching Fullscreen Mode

src/modules/config-panel/config-panel.ts, src/modules/fetch-http-client/http-fetch-client.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Setting Headers
2. Fix HttpFetchClient Usage
PR: #1827
- Try to connect to a external ProcessEngine
=> 🐛 Fix Setting Headers

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Add the internal solution only for the electron app
Closes #1817 
PR: #1824 
=> 🐛 Add internal solution only in the Electron app

package-lock.json, package.json, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.ts, src/modules/inspect/heatmap/heatmap.ts, src/modules/inspect/inspect.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/save-diagram-service/save-diagram.service.ts, src/services/solution-is-remote-solution-module/solution-is-remote-solution.module.ts, src/services/solution-service/solution.service.ts
1. Add SolutionIsRemoteSolutionModule
2. Use SolutionIsRemoteSolutionModule to Check if Solution is RemoteSolution
Closes #1835 
PR: #1838
- Everything should work as before
=> ✨ Use SolutionIsRemoteSolutionModule to Check if Solution is RemoteSolution

src/app.ts, src/main.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/inspect/inspect.ts, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/start-page/start-page.html, src/modules/start-page/start-page.ts, src/modules/status-bar/status-bar.ts, src/modules/think/think.ts, src/services/authentication-service/index.ts, src/services/is-running-in-electron-module/is-running-in-electron.module.ts, src/services/save-diagram-service/save-diagram.service.ts, src/services/solution-explorer-services/index.ts
1. Add isRunningInElectronModule
2. Use isRunningInElectronModule to Check if Studio is Running in Electron
Closes #1834 
PR: #1839
- Everything should work as before
=> ✨ Use isRunningInElectronModule to Check if Studio is Running in Electron

Dockerfile, Jenkinsfile, dev_tooling/scripts/exec_async.js, dev_tooling/scripts/pack_to_tarball.js, package.json
1. Improve Docker Builds
PR: #1841
- Run `npm i && npm run build && npm run create-tarball`
- Run `docker build --build-arg NODE_IMAGE_VERSION='10-alpine'  --build-arg PROCESS_ENGINE_VERSION='' --build-arg BPMN_STUDIO_VERSION='' --build-arg BUILD_DATE='' --no-cache --tag 'bpmn-studio-test' .`
- Run `docker run -p 8000:8000 -p 9000:9000 bpmn-studio-test`
- Open `localhost:8000` & `localhost:9000` in your browser
- **Notice that `localhost:8000` shows the SwaggerUI of the ProcessEngine and `localhost:9000` shows the BPMN Studio**
=> ♻️ Improve Docker Builds

src/modules/inspect/inspect-correlation/inspect-correlation.scss
1. Fix Resizing the Inspect Panel
Closes #1849 
PR: #1850
- Go to the InspectCorrelation View
- Resize the Inspect Panel
- **Notice that the resizing works correctly.**
=> 🐛 Fix Resizing the Inspect Panel

src/modules/user-preferences/user-preferences.ts
1. Navigate Back After Saving Preferences
Closes #1857
Closes #1858
PR: #1863
- Open the BPMN Studio
- Go to Preferences
- Click Save
- **Notice that the BPMN Studio navigates back.**
=> ✨ Preferences: Navigate Back After Saving

electron_app/electron.ts
1. Use Async SaveDialog Instead of Sync
Closes #1836 
PR: #1870
- Overwrite some diagrams
- **Notice that the Studio won't crash.**
=> 🐛 Fix Overwriting Files on macOS Catalina

aurelia_project/environments/dev.ts, src/contracts/solution-explorer/ISolutionEntry.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Add Close All Diagrams Button
2. Fix Typo
Closes #1806
PR: #1866
- Open some diagrams
- Click on the x button next to 'Open Diagrams'
=> ✨Add Close All Diagrams Button

package-lock.json, package.json, src/services/save-diagram-service/save-diagram.service.ts
1. Create Folder on Save if it Does Not Exist
2. Remove Unneeded Dot in Error Message
Closes #1873
PR: #1875
- Open a diagram from a local solution
- Remove the local solution (via the filesystem)
- Save the diagram (via the BPMN Studio)
- **Notice that the solution gets recreated when saving.**
=> ✨ Create Folder on Save if it Does Not Exist

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Updating Diagrams in Local Solution
Closes #1627
PR: #1877
- Open a local solution
- Rename a diagram in the opened solution without using the BPMN Studio
- **Notice that the diagram name gets updated in the BPMN Studio.**
- Change a diagram in the opened solution without using the BPMN Studio
- Open the changed diagram via the SolutionExplorer from the opened solution
- **Notice that the changes get displayed.**
=> 🐛 Fix Updating Diagrams in Local Solution

build/builder-effective-config.yaml, electron-builder/alpha/electron-builder.yml, electron-builder/beta/electron-builder.yml, electron-builder/stable/electron-builder.yml, electron_app/electron.ts, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html, src/services/is-running-in-electron-module/is-running-in-electron.module.ts
1. Fix Setting Authority
2. Add Restart Modal
3. Move ProcessEngine Configs Outside of 'app.asar'
4. Add Restart Mechanism
5. Fix Typo in Correlation List
Closes #1859 
PR: #1867
- Build the electron app via `npm run electron-build-macos`
- Install the created electron app
- Start the Studio
- Change the authority of the internal Solution via the settings
- **Notice that a modal appears and asks if you want to restart the studio now or later.**
- Click `Restart now`
- **Notice that the Studio restarts**
- Go back to the settings
- **Notice that the authority is still changed.**
- Change the authority again
- Click `Restart later (manually)`
- **Notice that the Studio navigates back without restarting**
- Close the BPMN Studio
- Start the BPMN Studio
- Go back to the settings
- **Notice …
=> 🐛 Fix Setting Authority

package-lock.json, package.json, src/app.scss, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts
1. Add Text Input for Default Value of BooleanFormField
Closes #1680 
PR: #1840
- Create a Diagram
- Add a UserTask
- Add a Boolean FormField
- **Use the text input for the default value.**
=> ✨ Add Text Input for Default Value of BooleanFormField

src/contracts/solution-explorer/ISolutionEntry.ts, src/modules/design/design.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Improve Displaying Removed Local Solutions
2. Rename 'fontAwesomeIconClass' to 'cssIconClass'
3. Use Variable to Determine Tooltip Text
Closes #1851 
PR: #1864
- Open a solution via the BPMN Studio
- Remove the solution outside of the BPMN Studio
- **Notice that the icon of the solution changes and when hovering above the solution icon the tooltip will say: 'Solution was removed!'**
=> ✨ Improve Displaying Removed Local Solutions

src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts
1. Update ProcessLists on Solution Change
2. Update TaskLists on Solution Change
3. Update CronjobLists on Solution Change
Closes #1876 
PR: #1880 
- Deploy a process
- Run it a few times (but it has to stay active)
- Go to the Dashboard
- Undeploy the process
- **Notice that the lists get updated.**
=> ✨ Update Dashboard Lists on Solution Change

src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.scss
1. Add Error Message to Authority Input
Closes #1882
PR: #1884
=> ✨ Add Error Message to Authority Input

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss
1. Add Error Message to Remote Solution Input
PR: #1886
=> ✨ Add Error Message to Remote Solution Input

aurelia_project/environments/dev.ts, src/contracts/inspect-correlation/inspect-panel/constants.ts, src/contracts/inspect-correlation/inspect-panel/correlation-list/ICorrelationTableEntry.ts, src/contracts/inspect-correlation/inspect-panel/correlation-list/constants.ts, src/contracts/inspect-correlation/inspect-panel/index.ts, src/contracts/inspect-correlation/inspect-panel/process-instance-list/ProcessInstanceListSortSettings.ts, src/contracts/inspect-correlation/inspect-panel/process-instance-list/ProcessInstanceTableEntry.ts, src/contracts/inspect-correlation/inspect-panel/process-instance-list/constants.ts, src/contracts/inspect-correlation/inspect-panel/process-instance-list/index.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.html, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.ts, src/modules/inspect/inspect-correlation/contracts/IInspect-correlation.repository.ts, src/modules/inspect/inspect-correlation/contracts/IInspect-correlation.service.ts, src/modules/inspect/inspect-correlation/inspect-correlation.html, src/modules/inspect/inspect-correlation/inspect-correlation.ts, src/modules/inspect/inspect-correlation/repositories/inspect-correlation.pagination-repository.ts, src/modules/inspect/inspect-correlation/repositories/inspect-correlation.repository.ts, src/modules/inspect/inspect-correlation/services/inspect-correlation.service.ts
1. Add Correlation List
2. Use ProcessInstance List for Process Instances from Selected Correlation
Closes #1769 
PR: #1888
- Open the Inspect Correlation View
- **Notice that there is a Correlation List containing all correlations for the active diagram.**
- Click on a correlation
- Change to the Process Instance List
- **Notice that the Process Instance List contains all process instances for the selected correlation.**
=> ✨ Distinction between ProcessList and Correlation List

.github/workflows/continuous-integration-workflow.yml, package-lock.json, package.json
1. Implement Releasenote Announcing
PR: #1891
- **Have a look at the slack channel `#bpmn-studio_test-announcement-channel`**
=> ✨ Implement Releasenote Announcing

src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.ts
1.  Refactor Sorting of CorrelationList
2. Refactor Sorting of ProcessInstanceList
3. Refactor Sorting of LogViewer
PR: #1894
1. Go to the Inspect Correlation View
1. **Notice that the CorrelationList should be sorted by the start date in ascending order..**
1. Switch between some ProcessModels
1. **Notice that the CorrelationList should still be sorted by the start date in ascending order.**
1. Click on the 'Started at' headline of the table
1. **Notice that the CorrelationList should be sorted by the start date in descending order.**
1. Switch between some ProcessModels
1. **Notice that the CorrelationList should still be sorted by the start date in descending order.**
1. Click on the 'Correlation ID' heading of the table
1. **Notice that the CorrelationList should be sorted by the …
=> ♻️ Refactor Sorting of New Inspect Correlation Lists

.github/workflows/continuous-integration-workflow.yml
1. Trigger Deployment of ProcessEngine.io after GitHub Release
PR: #1904 
=> ✨ Trigger Deployment of ProcessEngine.io after GitHub Release

src/modules/fetch-http-client/http-fetch-client.ts
1. The client is now able to correctly handle responses with string- and json- bodies
2. Use type inference
3. Reduce code duplications 
Closes #1907
PR: #1906
- Try starting a ProcessModel that is not executable
- Notice that the received error message looks correct
=> ♻️ Robustify internal http fetch client

electron_app/electron.ts, index-styles.css, index.html
1. Improve initial loading
Before:
After:
PR: #1905 
=> ✨ Improve initial loading

src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/repositories/live-execution-tracker.repository.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts
1. Fix using the wrong process instance
2. Fix inactive CallActivity preview
Closes #1908 
PR: #1909 
have a look at #1908
=> 🐛Fix showing wrong CallActivity instance

electron_app/electron.ts, package-lock.json, package.json, src/main.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, test/integration/design.spec.ts, test/integration/test-classes/design-view.ts
1. Run the ProcessEngine Runtime as own Node process
2. Improve displaying the startup error on the solution explorer.
PR: #1914 
=> ✨Run process engine as own process

Dockerfile
1. Install python2 to rebuild electron native dependencies
Closes #1918 
PR: #1924 
Look at this run:
https://github.com/process-engine/bpmn-studio/runs/386641295
=> 🐛Fix Docker Build

package-lock.json, package.json
1. Fix Watching Solutions
Closes #1887
PR: #1938
- Create a local solution
- Add some diagrams to the solution
- Open the solution with the BPMN Studio
- Remove the solution from the filesystem
- **Notice that the BPMN Studio displays the solution as removed.**
- Recover the solution
- **Notice that the BPMN Studio displays the solution with its diagrams.**
=> 🐛 Fix Watching Solutions

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss
1. Add Max Height to Open Diagrams
Closes #1936 
PR: #1940
- Open more than 10 diagrams
- **Notice that the Open Diagrams Section is now scrollable.**
=> ✨ Add Max Height to Open Diagrams

package-lock.json, package.json
1. Add Element Id to Lint Overlays
Closes #1501 
PR: #1939
- Create some lint errors
- Activate the linter
- Have a look at the lint overlay
- **Notice that the ElementId is displayed in the heading.**
=> ✨ Add Element Id to Lint Overlays

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Scroll down to a New Diagram after Creation
Related to #1936
PR: #1945
- Create some new diagrams
- **Notice that the newly created diagram is always visible in the solution explorer.**
=> ✨ Scroll down to a New Diagram after Creation

src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/pool/pool.html, src/modules/design/property-panel/indextabs/general/sections/pool/pool.ts
1. Fix Process ID Check in ID Validation
Closes #1948 
PR: #1949
- Copy the pool id
- Use the pool id as id for any other element
- Change the diagram (without clicking anywhere else first)
- Change back to the previous diagram
- **Notice that the diagram is still completely visible.**
- Copy the collaboration id
- Use the collaboration id as process id
- Change the diagram (without clicking anywhere else first)
- Change back to the previous diagram
- **Notice that the diagram is still completely visible.**
=> 🐛 Fix Process ID Check in ID Validation

src/modules/inspect/inspect-process-instance/inspect-process-instance.scss
1. Fix Scrolling of TokenViewer
2. Fix Resizing of Inspect Panel
Closes #1947
PR: #1951
- Deploy [this](https://github.com/process-engine/bpmn-studio/files/4101930/Hello.World.zip) diagram
- Go to the Inspect View
- Click on the UserTask
- Open up the Inspect Panel
- **Notice that the Inspect Panel is still resizeable and the TokenViewer is scrollable.**
=> 🐛 Fix TokenViewer InspectPanel Bug

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Hide the contextmenu on remote solutions
Closes #1954 
PR: #1964
- right-click on a diagram of a remote solution
=> ✨ Hide the contextmenu on remote solutions

src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts
1. Fix bug where the inspect view cannot detach
Closes #1960 
PR: #1963 
look at the referenced issue
=> 🐛 Fix bug where the inspect view cannot detach

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss
1. Add angle-down to the dropdown
Closes #1970 
PR: #1971
=> ✨Add angle down to dropdown

package-lock.json, package.json, src/modules/inspect/cronjob-list/cronjob-list.scss, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/task-list/task-list.scss, src/modules/navbar/navbar.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/authentication-service/electron.oidc-authentication-service.ts
1. Improve displaying authority issues for a solution
2. Fix bug where the studio is still polling a solution with unauthorized or forbidden responses
First draft:
Second draft:
Third draft:
Closes #1967 
PR: #1968
=> ♻️Improve UI authority issues

aurelia_project/aurelia.json, package-lock.json, package.json, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/correlation-list/correlation-list.scss, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.html, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.scss, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.ts, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/process-instance-list/process-instance-list.scss
1. Set user-select to text
2. Stop copying to log entry message to clipboard on left-click
3. Remove clipboard-polyfill package
Closes #1969 
PR: #1972
=> ♻️ Refactor copying table entries

.github/workflows/continuous-integration-workflow.yml
1. Tag the Docker Image with latest and major studio version
Closes #1959 
PR: #1965
look at https://github.com/process-engine/bpmn-studio/runs/417399361?check_suite_focus=true
https://github.com/process-engine/bpmn-studio/runs/418870487
=> 🐳 Tag the Docker Image with latest and major studio version

package-lock.json, package.json, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.ts, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/process-instance-list/process-instance-list.html, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/process-instance-list/process-instance-list.ts
1. Fix sorting process-list
2. Fix sorting correlation-list
3. Fix sorting log-viewer
4. Fix sorting process-instance-list
PR: #1978 
- open each list and see that the first entry is the "newest"
=> 🐛 Fix sorting inspect tables

src/contracts/help-text/help-text-id.ts, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts, src/services/help-modal-service/help-text-service.ts, src/services/help-modal-service/help-texts/external-task-token-usage.ts, src/services/help-modal-service/help-texts/script-task-token-usage.ts, src/services/help-modal-service/help-texts/usertask-usage.ts
1. Add help text for ExternalTasks
2. Add help text for UserTask usage
PR: #1984 
- open a diagram with a user task/service task(external task)
- click on the info icon on the property panel
- read the text
=> ✨Add help text for usertask and externaltask

aurelia_project/aurelia.json, package-lock.json, package.json, src/services/help-modal-service/help-modal-service.ts, src/services/help-modal-service/help-texts/external-task-token-usage.ts, src/services/help-modal-service/help-texts/script-task-token-usage.ts, src/services/help-modal-service/help-texts/usertask-usage.ts, src/services/help-modal-service/remove-multiline-indent.ts
1. Use marked to render markdown
2. Add removeMultilineIndent function
3. Adjust ExternalTask Help text for MD
4. Adjust ScriptTask Help text for MD
5. Adjust UserTask Help text for MD
Closes #1985 
PR: #1988 
- open the helptext for ScriptTask, UserTask and ServiceTask(ExternalTask)
=> ✨Add markdown renderer for helptexts

package-lock.json, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix ProcessEngine Online Check
Closes #1998  
PR: #2001
=> 🐛 Fix ProcessEngine Online Check

src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts
1. Fix Displaying Element Types
Closes #2002 
PR: #2003
- Open [this](https://github.com/process-engine/bpmn-studio/files/4414609/Elements.bpmn.zip) diagram
- Click on the elements
- **Notice that every element type get displayed correctly in the PropertyPanel**
=> 🐛 Fix Displaying Element Types

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Multiple Error Messages Bug
PR: #2004
- Log in to the BPMN Studio with a user who does not has the permission to read process models
- Log out
- **Notice that only one error message is displayed.**
=> 🐛 Fix Multiple Error Messages Bug

src/services/help-modal-service/help-texts/external-task-token-usage.ts
1. Improve the custom topic description
PR: #2006 
- open a diagram with an external task or add one
- click on the information icon in the property panel
=> 📝Improve Custom Topic description

package.json, src/contracts/authentication/constants.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/authentication-service/electron.oidc-authentication-service.ts
1. Fix Silent Refresh Bug
PR: #2008
- Open the BPMN Studio
- Connect to multiple engines
- Log in to the engines
- Wait some time
- Notice that you're still logged in to the engines  and the login button is still working
- Close the Studio
- Wait some time
- Notice that you're still logged in to the engines  and the login button is still working
=> 🐛 Fix Silent Refresh Bug

package-lock.json, package.json, src/modules/design/design.html
1. Update the AtlasEngine to apply some bugfixes.
2. Fix disabling the Start Process button if no StartEvent is selected.
Closes #2016 
PR: #2015 
=> 🐛Update the AtlasEngine to apply some bugfixes

src/modules/deploy-modals/deploy-modals.html, test/integration/design.spec.ts, test/integration/test-classes/design-view.ts, test/integration/test-classes/solution-explorer.ts
1. Add a test which deploys a diagram and overwrites the existing diagram on the process engine
PR: #2009 
- run the tests
=> ✨Add second deploy diagram test

package-lock.json, package.json
1. Update the AtlasEngine to fix a bug where a wrong log path was used
PR: #2022
=> 🐛Update AtlasEngine to fix wrong logpath

src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.scss, src/modules/inspect/task-list/task-list.ts
1. Display the task name as default and use the ID as a fallback
2. Add a task information modal
PR: #2018 
- open the task-list
- click on the info button on the table entry
=> ✨Add task info modal

package-lock.json, package.json, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts
1. Update element contracts
2. Save the error message at the correct place
Closes #2017
PR: #2024 
- add an error and fill the properties
- look at the XML and see that the error message is saved at the error object now
- see that old diagrams with errors now get the message saved also at the error object
=> 🐛Save error message in error object

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/open-diagrams-solution-explorer.service.ts
1. Allow renaming the selected/opened diagram
2. Fix the renaming workflow
Closes #2020 
Closes #2019 
PR: #2025 
try to reproduce the referenced issues
=> 🐛Fix renaming diagrams

package-lock.json, package.json, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/extensions/sections/process/process.ts, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/design/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-task/message-task.ts, src/modules/design/property-panel/indextabs/general/sections/pool/pool.html, src/modules/design/property-panel/indextabs/general/sections/pool/pool.ts, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/design/property-panel/indextabs/general/service/general.service.ts, src/modules/design/property-panel/styles/sections.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/generate-random-id-module/generate-random-id-module.ts, src/services/save-diagram-service/save-diagram.service.ts
1. Update custom-bundle and elements-contracts
2. Adjust PropertyPanel for Group Elements
3. Add method to update group element values
4. Add QName validation
5. Display error message on validation error
6. Remove obsolete stuff
Closes #1977 
Closes #2012 
PR: #1638 
**Wichtig: Diagramme die IDs beinahlten, welche nicht QName konform sind können nicht mehr richtig dargestellt werden.**
Bitte ausführlich testen ob das modellieren der Diagramme funktioniert wie erwartet und ob funktionen die mit den Diagrammen zu tun haben noch funktionieren. (Copy/Paste, Exportieren etc.)
=>  ⬆️Update bpmn-js and add QName validation

src/modules/form-widget/form-widget.html, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.ts
1. Remove unprofitable logic in HTML part for displaying information
PR: #2028
- check that the task information modal is like before this PR
=> ♻️ Refactor displaying information

src/modules/inspect/inspect-process-instance/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/correlation-list/correlation-list.scss, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/process-instance-list/process-instance-list.html, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/process-instance-list/process-instance-list.scss
1. Refactor CSS flex for tables
PR: #2029 
- check whether the inspect tables work as before
=> ♻️ Refactor flex using on tables

package-lock.json, src/services/help-modal-service/help-texts/intermediate-timer-event-usage.ts, src/services/help-modal-service/help-texts/timer-boundary-event-usage.ts, src/services/help-modal-service/help-texts/timer-start-event-usage.ts
1. Add examples to TimerEvent help texts
Closes #2013 
PR: #2031
=> 📝 Add examples to TimerEvent help texts

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Stops the event propagation to avoid selecting the deleted entry.
Closes #2032 
PR: #2033
try to reproduce the referenced issue
=> 🐛 Fix bug where the deleted item gets selected

package-lock.json, package.json, src/contracts/bpmnmodeler/IBpmnModdle.ts, src/contracts/bpmnmodeler/IBpmnModeler.ts, src/modules/design/bpmn-diff-view/bpmn-diff-view.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/property-panel/indextabs/general/repository/general.repository.ts, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/design/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-task/message-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.ts, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/design/property-panel/property-panel.ts, src/modules/inspect/heatmap/heatmap.ts, src/modules/inspect/heatmap/services/heatmap.service.ts, src/modules/inspect/inspect-process-instance/components/diagram-viewer/diagram-viewer.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts, src/services/deploy-diagram-service/deploy-diagram.service.ts, src/services/diagram-creation-service/diagram-creation.service.ts
1. Use async await on importXML saveXML saveSVG toXML fromXML
2. Update bpmn-js-custom-bundle to update bpmn-js
PR: #2038 
all should work as before
=> ⬆️Update bpmn js

package-lock.json, package.json
1. Fix handling UserTasks with preferredControl confirm without boolean FormField
PR: #2043
=> 🐛 Fix handling UserTasks with preferredControl confirm without boolean FormField

package-lock.json, src/modules/design/property-panel/indextabs/general/general.ts, src/modules/design/property-panel/indextabs/general/sections/manual-task/manual-task.html, src/modules/design/property-panel/indextabs/general/sections/manual-task/manual-task.ts, src/modules/design/property-panel/indextabs/general/sections/untyped-task/untyped-task.html, src/modules/design/property-panel/indextabs/general/sections/untyped-task/untyped-task.ts
1. Add untyped task section and enabled property for breakpoint behavior
2. Add manual task section and requires confirmation property
3. Update AtlasEngine for testing
Closes #2040 
PR: #2041
Step by Step: https://github.com/atlas-engine/AtlasEngine.FullstackServer/pull/110
Waits for the migrations fix from the fullstack server
=> ✨Add requires confirmation switch

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix bug where diagramState was undefined
2. Fix executing closeAllDiagrams for every solution
Closes #2037 
PR: #2045 
try to reproduce the referenced issue
=> 🐛Fix close all opened diagrams

package-lock.json, package.json
1. Update the dependency to remove formField wrapper property from UserTask payloads
PR: #2047 
=> ⬆️ Update AtlasEngine Fullstackserver to remove formField wrapper property from UserTask payloads

aurelia_project/aurelia.json, package-lock.json, package.json, src/services/diagram-creation-service/diagram-creation.service.ts, src/services/solution-explorer-services/open-diagram-state.service.ts
1. Replace node-uuid with uuid
PR: #2046 
Should work as before
=> ♻️Replace node-uuid with uuid

src/modules/design/property-panel/indextabs/general/sections/process/process.ts, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.html, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.ts
1. Fix adding enabled property automatically on timer start events
Closes #1937 
PR: #2051 
=> 🐛Fix adding enabled property automatically on timer start events

src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts
1. Refactor fillVariablesFromParam method 
2. Refactor getParamsFromInput
3. Fix the parsing for the params of a HTTP Service Task
Closes #2056 
PR: #2057
Try to reproduce the referenced issue.
=> 🐛Refactor and fix parsing the params of http service tasks

src/services/diagram-creation-service/diagram-creation.service.ts
1. Fix bug where duplicate a diagram does not work if the diagram to duplicate is an invalid ID diagram
PR: #2064 
try to duplicate a diagram which contains an invalid ID at an element
=> 🐛  Fix duplicate diagram if the diagram contains invalid IDs

package-lock.json, package.json, src/modules/design/property-panel/indextabs/general/sections/manual-task/manual-task.html, src/modules/design/property-panel/indextabs/general/sections/manual-task/manual-task.ts, src/modules/design/property-panel/indextabs/general/sections/untyped-task/untyped-task.html, src/modules/design/property-panel/indextabs/general/sections/untyped-task/untyped-task.ts
1. Fix initializing checkbox for manual and untyped tasks
2. Update Atlas Engine
PR: #2065 
=> ⬆️🐛Fix setting correct checkbox value and update Atlas Engine

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Refactor and improve the error message for illegal characters while creating or renaming diagrams
Closes #2066 
PR: #2069 
=> ♻️ Refactor and improve the error message for illegal characters while creating or renaming diagrams

package-lock.json, package.json, src/modules/design/diagram-detail/diagram-detail.ts
1. Use JSON5 package to parse JS objects
Closes https://github.com/process-engine/bpmn-studio/issues/2072
PR: #2074 
branch auschecken, bauen, testen wie im referenzierten Issue beschrieben
=> Parse JS objects for start token

package-lock.json, package.json
1. Update DynamicUI to apply empty enum value bugfix.
Closes #2077 
PR: #2079
=> ⬆️🐛 Update DynamicUI to apply empty enum value bugfix

src/modules/design/property-panel/indextabs/extensions/extensions.ts, src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/extensions/sections/process/process.ts, src/modules/design/property-panel/indextabs/forms/forms.ts, src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/general.ts, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.ts, src/modules/design/property-panel/indextabs/general/sections/conditional-event/conditional-event.ts, src/modules/design/property-panel/indextabs/general/sections/data-objects/data-output-association/data-output-association.ts, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts, src/modules/design/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts, src/modules/design/property-panel/indextabs/general/sections/flow/flow.ts, src/modules/design/property-panel/indextabs/general/sections/link-event/link-event.ts, src/modules/design/property-panel/indextabs/general/sections/manual-task/manual-task.ts, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.ts, src/modules/design/property-panel/indextabs/general/sections/message-task/message-task.ts, src/modules/design/property-panel/indextabs/general/sections/pool/pool.ts, src/modules/design/property-panel/indextabs/general/sections/process/process.ts, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.ts, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.ts, src/modules/design/property-panel/indextabs/general/sections/untyped-task/untyped-task.ts, src/modules/design/property-panel/property-panel.ts
1. Hopefully fix the property panel freezing bug.
Closes #2076 
PR: #2080
=> 🐛♻️ Robustify property panel to hopefully fix the freezing bug

package-lock.json, package.json
1. Enable resizing of Group elements
Closes #2082 
PR: #2084 
try to reproduce the referenced issue
=> 🐛 Enable resizing of Group elements

src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/service-task-service/service-task.service.ts
1. Adjust reading and writing param properties like in atlas studio
PR: #2090 
Be sure that the HTTP service task section works as expected.
=> ♻️ Adjust handling http service task params

package-lock.json, package.json
1. Update the Atlas Engine to v10.2.0
PR: #2092  
=> ⬆️Update Atlas Engine to v10.2.0

package-lock.json, package.json
1. Update Atlas Engine to v11.0.0-beta.2
PR: #2093 
=> ⬆️ Update Atlas Engine to v11.0.0-beta.2

package-lock.json, package.json
1. Update Atlas Engine to v11.0.0-beta.3
PR: #2094 
=> ⬆️ Update Atlas Engine to v11.0.0-beta.3

package-lock.json, package.json
1. Update bpmn-lint_rules package to apply new `no-undefined-message-task` rule.
PR: #2096 
add a SendTask and a ReceiveTask to a diagram and activate the linter.
=> ⬆️  Update bpmn-lint_rules to add no-undefined-message-task rule

electron_app/electron.ts, package-lock.json, package.json
1. Update Atlas Engine to v11.0.0 beta.8
PR: #2097 
=> ⬆️ Update Atlas Engine to v11.0.0 beta.8

package-lock.json, package.json
1. Update Atlas Engine to v11.0.0 beta.10
PR: #2098
=> ⬆️  Update Atlas Engine to v11.0.0 beta.10

package-lock.json, package.json
1. Update bpmn-lint_rules to apply "no undefined message tasks" rule
PR: #2099
=> ⬆️ Update bpmn-lint_rules to apply "no undefined message tasks" rule

package-lock.json, package.json
1. Update Atlas Engine to v11.0.0
PR: #2100
=> ⬆️ Update Atlas Engine to v11.0.0

package-lock.json, package.json
1. Hotfix: Apply Atlas Engine Hotfix https://github.com/atlas-engine/AtlasEngine/pull/270
PR: #2101 
=> Hotfix: Apply Atlas Engine hotfix for metadata collections

package-lock.json, package.json
1. Update Atlas Engine to v11.1.0-beta.1
PR: #2102 
=> ⬆️ Update Atlas Engine to v11.1.0-beta.1

package-lock.json, package.json
1. Update Atlas Engine to v11.1.0-beta.2
PR: #2104 
=> ⬆️ Update Atlas Engine to v11.1.0-beta.2

package-lock.json, package.json
1. Update Atlas Engine to v11.1.0-beta.5
PR: #2105 
=> ⬆️ Update Atlas Engine to v11.1.0 beta.5

package-lock.json, package.json
1. Update Atlas Engine to v11.1.0
PR: #2106 
=> ⬆️ Update Atlas Engine to v11.1.0

package-lock.json, package.json
1. Update Atlas Engine to v11.2.0-beta.1
PR: #2109 
=> ⬆️ Update Atlas Engine to v11.2.0-beta.1

package-lock.json, package.json
1. Apply Atlas Engine fix for too long paths on Windows
PR: #2111
=> 🐛 Apply Atlas Engine fix for too long paths on Windows

.github/workflows/continuous-integration-workflow.yml, build/code-signing/mac/notarize.js, electron-builder/alpha/electron-builder.yml, electron-builder/beta/electron-builder.yml, electron-builder/stable/electron-builder.yml, package-lock.json, package.json
1. Update Atlas Engine to v11.2.0-beta.3
=> ⬆️ Update Atlas Engine to v11.2.0-beta.3

src/modules/design/property-panel/indextabs/forms/sections/basics/basics.ts
1. Fix displaying "Truth Value" form field default value
Closes #2114 
PR: #2117
Try to reproduce the described behavior of the referenced issue
=> 🐛 Fix displaying form field default value

package-lock.json, package.json
1. Update Atlas Engine to v11.2.0-beta.5
PR: #2119
=> ⬆️ Update Atlas Engine to v11.2.0 beta.5

package-lock.json, package.json, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts
1. Add "Trust unauthorized certificates" switch to internal engine settings. 
2. Update Atlas Engine 
PR: #2122
=> Hotfix: Allow unauthorized certificates switch

package-lock.json, package.json
1. Update Atlas Engine to v11.3.0-beta.3
PR: #2124 
=> ⬆️ Update Atlas Engine to v11.3.0-beta.3

package-lock.json, package.json
1. Update Atlas Engine to v11.3.0-beta.4
PR: #2125 
=> ⬆️ Update Atlas Engine to v11.3.0-beta.4

package-lock.json, package.json, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts
1. Update Atlas Engine Version
2. Add TLS Use Windows Trust Store switch on Windows
PR: #2128 
=> Hotfix: Add windows trust store switch

electron_app/electron.ts, package-lock.json, package.json
1. Update Atlas Engine to v12.0.0-beta-1
2. Adjust the startup arguments
Closes #2120 
PR: #2129 
=> ⬆️ Update Atlas Engine to v12.0.0-beta-1

package-lock.json, package.json
1. Update Atlas Engine to v12.0.0-beta.4
PR: #2130 
=> ⬆️ Update Atlas Engine to v12.0.0-beta.4

package-lock.json, package.json
1. Update Atlas Engine to v12.0.0-beta.6
PR: #2131 
=> ⬆️ Update Atlas Engine to v12.0.0-beta.6

package-lock.json, package.json
1. Update Atlas Engine to v12.0.1
PR: #2133 
=> ⬆️ Update Atlas Engine to v12.0.1

package-lock.json, package.json
1. Update the Atlas Engine to apply some hotfixes.
PR: #2136 
=> Hotfix Release v6.7.1
