aurelia_project/aurelia.json, package.json, src/modules/processdef-detail/processdef-detail.ts
I replaced the manual file-export to use [download.js](https://www.npmjs.com/package/downloadjs) instead. This fixes #25 
You should (with this fix) be able to export diagrams with special characters using Firefox
=> 🐛 fix export for firefox

src/modules/processdef-detail/processdef-detail.ts
When exporting a BPMN Diagram now the name of the process is used as file name.
- run charon
- export a diagram
=> ✨ Use process name as file name when exporting

src/modules/processdef-list/processdef-list.ts, src/modules/task-list/task-list.ts
The consumer_client exports all Interfaces that are needed to use it. This means that the consumer_client imports some interfaces from essential-projects and process-engine and reexports them.
Charon used some interfaces from essential-projects and process-engine packets directly that were also exported from the consumer_client, but the version charon used was not necessarily identical to the interface-versions that are used by the consumer_client. This lead to build-errors, because multiple differing types of the same name were used within a single class.
This Branch fixes these build-errors
When checking out charon on this branch, you should be able to successfully build it without warnings or errors
=> 🐛 fix usage of incompatible types

src/modules/dynamic-ui-radiobutton-element/dynamic-ui-radiobutton-element.html, src/modules/dynamic-ui-radiobutton-element/dynamic-ui-radiobutton-element.ts
Fixes #51, this pr just _adds_ support for rendering radiobuttons but this is never used currently.
Currently we can only know what _type_ the field to render is, e.g. `enum` in this case. We need a second flag for the prefered control to use. This need to be added into the consumer client. See https://github.com/process-engine/consumer_client/issues/7.
Change `dropdown` to `radiobutton` in `src/modules/form-widget/form-widget.ts`, when try to render some enum field. It will be rendered using checkboxes instead of a dropbown.
=> ✨ Add radiobuttons for dynamic ui

src/modules/confirm-widget/confirm-widget.html
This branch enables the confirm widget ALL html that is passed into it by the "message" property.
Example:
In:
```
First Line.<br>Second Line.
```
Out:
```
First Line.
Second Line.
```
Closes #70 
Create a new process with one user task with properties:
uiName
`Confirm`
uiConfig
`${ "message": "First Line.<br>Second Line.", "layout": [ { "key": "confirm", "label": "Confirm"}] };`
=> Enable Confirm Widget to render html in message

src/modules/process-list/process-list.html, src/modules/process-list/process-list.ts
This branch deletes the disabled button for stopping process instances in the Process-List view.
Closes #34 
Switch to this branch and start Charon with `npm install`and `npm start`.
Navigate to `localhost:9000` and click on "Process Instance List" in the navbar.
You will see, there is no stop button anymore.
=> 🔥Delete "Stop Process"-Button

bin/charon.js, package.json
This was needed because http-server would always serve the current working directory.
With our own script we can customize the root directory used to serve content.
- clone charon
- run `npm install`
- run `npm run build`
- run `npm install -g`
- run `charon` in _any_ folder
=> 🐛 Instead of Relying on http-server, we now use our own Start Script

bin/charon.js, package.json
This PR adds the glyphicon-config for the node-http-server and removes minimist from the package.json.
Minimist is no longer needed, because node-http-server checks the command line arguments by itself.
Checkout the branch and start charon with `npm start`. Now the glyphicons are shown correctly.
=> :bug: Fix glyphicons and change start script

src/modules/processdef-detail/processdef-detail.ts
When deleting a processdef, charon now navigates back to the main page.
Closes #104
- Delete a processdef
- Main page should be displayed and the processdef deleted
=> 🚸 :children_crossing: After Deleting a ProcessDef Navigate to Main Page

aurelia_project/aurelia.json, package.json, src/contracts/bpmnmodeler/IBpmnModeler.ts, src/modules/bpmn-io/bpmn-io.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
This PR adds the option to export a diagram as SVG, PNG or JPEG.
Closes #118 
- Checkout the branch
- Start bpmn-studio and navigate to the details page of a processdef
- Export the diagram as SVG, PNG or JPEG
=> ✨ :sparkles: Add SVG, PNG and JPEG as export option

dev-app-update.yml, electron_app/electron.js, package.json
This branch adds the autoupdate functionallity for electron apps.
Closes #77 
Closes #126 
Closes #124 
Closes #122
1. checkout bpmn-studio
2. run `npm install`
3. downgrade version to rc8
4. get an apple macos developer certificate
5. run `npm run electron-build`
6. open ...-mac.zip file in /dist folder
7. run the app
=> Add Electron Autoupdate Functionality

src/modules/form-widget/form-widget.ts
Adds a error message when a unsupported field is used in dynamic ui
- Use long type as field type
- start process with dynamic ui
- see error
=> 🔊 :loud_sound: Add warning when unsupported form field type is used

src/modules/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html, src/modules/property-panel/indextabs/general/sections/flow/flow.html, src/modules/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html
This PR removes the no longer existing `section__border` class from all HTML files it was still in.
=> 🔥 Delete Section Border Class from HTML Files

src/contracts/bpmnmodeler/bpmnElements/IModdleElement.ts, src/contracts/bpmnmodeler/bpmnElements/IProcessRef.ts, src/modules/property-panel/property-panel.ts
This PR selects now always an element (after import or first attach of detailview).
- first try to set the startevent
- then try to set another element
- if that fails, it selects the process 
- import a diagram with a startevent and other elements => startevent is selected
- import a diagram without a startevent => another element is selected
- import a diagram without any elements => process is selected
=> 🐛 :bug: Fix setFirstElement function

src/modules/property-panel/property-panel.html, src/modules/property-panel/property-panel.ts
I fixed a warning caused by the selected-element-id-label.
- open up BPMN-Studio
- have a look at the console and see no more warnings
=> 🐛:bug: Fix Warning when Changing Element

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/environment.ts, src/modules/processdef-detail/processdef-detail.html, src/modules/processdef-detail/processdef-detail.ts
The Colorpicker now gets displayed correctly also when the ProcessDef gets changed.
1. Open up the BPMN-Studio
2. Open up the Detail-View of any ProcessDef
3. Have a look at the Colorpicker
4. Go back to the ProcessDefList
5. Repeat Step 2 and 3 and see that it is still working
=> 🐛:bug: Fix Colorpicker When the ProcessDef gets Changed

src/modules/property-panel/property-panel.html
There is this 8 y/o Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=488725
Button has css property `white-space: nowrap`, which causes a bug in
Firefox in combination with floats(such as the chevron).
Causes a linebreak, when both text and the chevron should be in same line.
Swapping text and chevron makes it work.
Another solution would be setting whitespace to normal on the button-element.
Swapped two lines of HTML in order to fix a firefox specific bug.
- checkout this branch
- `au build`
- `npm run`
- open localhost:8080, open details of a diagram, look at dropdownbutton in property panel with firefox.
=> Fix firefox-specific css bug.

electron_app/electron.js
I increased the minimum height of the electron app, so that the left bar of the BPMN-Studio is fully accessible.
- Build the electron app
- Resize it as small as possible
=> :lipstick: Fix Minimum Height of Electron

electron_app/electron.js
I readded the 'bpmn-studio', because otherwise the 'edit' menu was used as 'bpmn-studio' menu.
- Build the electron app
- Have a look at the menu bar and the 'edit' and 'bpmn-studio' menu
=> :bug: Readd Main Menu

electron_app/electron.js, package.json, src/app.html, src/app.scss, src/app.ts, src/main.ts
**SEE [THIS DIFF](https://github.com/process-engine/bpmn-studio/pull/221/files?w=1) FOR A BETTER OVERVIEW!**
(in this diff, the lines where only the indentation changed are not shown)
I made the electron-version of the bpmn-studio automatically choose a free port to run the backend on, if 8000 is already in use.
This however overrides the "last used server"-functionality we currently have, because it works by setting the new backend-location as last used server before the bpm-studio starts.
I also added the current baseRoute as absolute-positioned label to the bottom-left of the application
Something like a server-history would be nice to improve this situation.
A lot of stuff in the electron.js was just inendet, because it needs to happen after the port was found to not create a …
=> ✨ Automatic detection of free port

bin/bpmn-studio.js
'image/svg' is no valid contenttype. This bug broke svgs.
Fixes #223 
Changed contenttype of svgs
Start application with 'npm start' without processengine running. With this fix you will see the gears svg, without it you won't.
=> Fix svg contentType.

bin/bpmn-studio.js, package.json
This PR adds the possibility to change the default start port of bpmn-studio-web.
Also you can start the BPMN-Studio with a custom port:
`npm start -- --port=4444`
alternative:
`npm start -- --port 4444`
We use `minimist` to parse the argv.
Closes #285 
- `npm start` (should use port 17290)
- `npm start port="CUSTOM_PORT"`
=> :sparkles: Change Default Port and Check for Port Argument

electron_app/electron.js
Behandelt #387 und fügt ein "Window"-Menü hinzu, dass die in #387 beschriebene Reload-Funktion beinhaltet.
- Electron App starten.
- Das Menü erscheint in der nativen Menüleiste.
=> :recycle: Add window-reload to window menu in Electron app

src/modules/bpmn-xml-view/bpmn-xml-view.scss, src/modules/process-solution-panel/process-solution-panel.scss
This PR fixes the xml-view problem when loading large diagrams.
Closes #306  
- build the app
- open the app and navigate to the xml-view of a large process like `Reservierungsprozess.bpmn`
=> 🐛 Fix XML-View on large diagrams

Jenkinsfile
Add the `--allow-same-version` Flag to `npm version` command.
This fixes a problem when Jenkins tries to set the version in the package.json, but its already set to the same version.
=> :construction_worker: Add '--allow-same-version' Flag to npm version Command

src/contracts/bpmnmodeler/IBpmnModeler.ts, src/modules/bpmn-io/bpmn-io.ts
Destory the bpmn-js Modeler on unbind
- Open BPMN-Studio electron
- copy/paste works on the processdef list
- open detail view
- copy/paste only works inside bpmn-js
- open processdef list
- copy/paste should now work with text again
=> :bug: Fix Copy/Paste Function

src/modules/navbar/navbar.scss, src/modules/process-solution-panel/process-solution-panel.scss, src/modules/property-panel/indextabs/extensions/extensions.html, src/modules/property-panel/indextabs/forms/forms.html, src/modules/property-panel/styles/registers.scss, src/modules/property-panel/styles/sections.scss
This branch:
- Makes the texts in the navbar NOT selectable, makes the details selectable.
- Makes only the properties of the property-panel selectable.
- Makes so process-solution-panel not selectable.
Open a diagram in the detail-view and try to select the name of the index-tab of the property-panel for example.
Closes #360
=> ♻️Make Texts (Not) Selectable

src/modules/bpmn-io/bpmn-io.ts
I implemented the requested `ctrl + s` (on mac `cmd + s`) hotkey for saving a diagramm to the database. 
I wonder if I also should implement a "quick export" to a bpmn file like the camunda modeler uses (which is way more convenient for my personal use). 
* Open or create a new process
* Hit `ctrl + s` (or `cmd + s` on mac). 
=> Implement ctrl + s hotkey for saving

src/modules/form-widget/form-widget.html, src/modules/import-process-button/import-process-button.html, src/modules/navbar/navbar.html, src/modules/process-list/process-list.html, src/modules/processdef-list/processdef-list.html, src/modules/processdef-start/processdef-start.html, src/modules/property-panel/indextabs/forms/forms.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/general/general.html, src/modules/property-panel/indextabs/general/sections/basics/basics.html, src/modules/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/property-panel/indextabs/general/sections/pool/pool.html, src/modules/property-panel/property-panel.html, src/modules/status-bar/status-bar.html, src/modules/task-dynamic-ui/task-dynamic-ui.html, src/modules/task-list/task-list.html
This PR fixes #457 and removes unused tooltips from html.
Also it uses "template" instead of "div" for if.bind.
=> ♻️Use template instead of div for repeaters

src/modules/diagram-tools-right/diagram-tools-right.html, src/modules/diagram-tools-right/diagram-tools-right.scss
This PR fixes #441 and improves color picker button-style.
before:
after:
- open detail view of a process
- open the color dropdown
=> Add default cursor to color dropdown and improve color picker buttons

package.json
This fixes the bug, which occurs with @process-engine/process_engine v6.0.0 when saving a diagram.
- `rm -rf node_modules/`
- `npm i`
- start a process and see that it works
- edit a diagram and save it => see that it works
=> ⬆️ Update @process-engine/skeleton-electron to 4.0.0

Jenkinsfile
- Replace `npm` with `pnpm`
This speeds up the installation time to ~2 Minutes, before this change the time was ~12 Minutes.
| before | after |
|--------|------|
| <img width="304" alt="grafik" src="https://user-images.githubusercontent.com/4148404/41402492-b877293a-6fc2-11e8-92e6-b89dbbdd552b.png"> | <img width="413" alt="grafik" src="https://user-images.githubusercontent.com/4148404/41402544-d56f3ab4-6fc2-11e8-9854-ae3ad0976a52.png"> |
See https://github.com/5minds/process_engine_infrastructure/issues/14
Checkout the builds
=> 👷⚡️ Use pnpm for Faster Installs

src/modules/processdef-start/processdef-start.ts
BPMN-Studio will:
- Return to list-view if process was started from list-view.
- Return to detail-view if process was started from detail-view.
Refactored some codestyle.
Fixes #318
Start the "Create Process"-Process.
=> :sparkles: Navigate to the Starting View After Process Execution Ends

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/environment.ts, src/modules/bpmn-io/bpmn-io.ts
When returning to the view/diagram, the width of the property panel is restored.
- Go to the "Detail View"
- Resize the property panel
- Go to the "Plan View"
- Go back to the "Detail View"
- Notice that the property panel still has the resized size
=> ✨ Persist and Load Last Property Panel Width in Local Storage

src/modules/bpmn-io/bpmn-io.ts
This PR Fixes the bug, where you can save an invalid diagram while pressing `cmd + s` while the property pane was active. 
Fixes: #501 
* Create a diagram
* Create two elements with the same id
* See, that the saving is no longer possible
=> 🐛 Fix saving of an invalid diagram via cmd + s

src/modules/bpmn-io/bpmn-io.ts
This PR moves the check, if the current Plattform is a mac, to a dedicated method. 
Since three methods use the same method to ask for the current platform, I thought that its a good idea to move the duplicated lines of code to a dedicated method.
This may also become handy, if we want to implement more features, that uses the meta key since we don't have to copy the same regex for the platform check over and over. 
Also, this PR fixes a few typos in the word _platform_ and change the name of the `_addKeyboardListener()` Method, since the only purpose of this method was to bind an event to the backspace key, if the current platform is a mac.
=> ♻️Refactor the Plattform check

package.json
This temporarily fixes the bug which occurs when you start the bpmn-studio as electron app.
Triggered by the latest electron-builder release.
- clear you node modules
- `npm i`
- `npm run electron-build-macos`
- start the generated app and see that it works
=> 🐛📌 Pins electron-builder to 20.14.7

src/modules/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.ts, src/modules/process-solution-panel/process-solution-panel.ts
When reloading the diagram/view or changing the diagram via the plan view, the hide state of the property panel is restored.
When reloading the BPMN-Studio, the hide state of the process solution explorer is restored.
- Go to any diagram
- Toggle the property panel
- Change the diagram via the plan view or reload the page
- Notice that the property panel is still hidden/shown
- Toggle the process solution explorer
- Reload the page
- Notice that the process solution explorer is still hidden/shown
=> ✨Persist Hide States When Reloading

src/modules/processdef-detail/processdef-detail.ts
Fixes #510 
In the old implementation, the quality when export a png file depends on the resolution of the used monitor. 
Also the pixel density was way to low to produce a quality print of a diagram. 
This PR adds printing of the native SVG vector graphic, so that that browser can handle the rasterisation itself. 
We are still locked to a DIN A4 format. The problem is that we cant really obtain the correct paper format before the user gets prompted with the printing dialogue. 
* Print a diagram
* Look at the printed diagram
=> Improve the resolution when printing or exporting a diagram as an image

Jenkinsfile
This PR adds the `--prefer-offline` flag that forces npm to use the cache. 
Maybe see the improved build speed here: https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/activity/?branch=feature%2Fadd_prefer_offline_flag
**Builds 1-3:** without electron
**Builds 4-6:** with electron (you can compare their speed with master or develop)
=> 👷⚡️ :construction_worker: Add Prefer Offline Flag

src/modules/process-solution-panel/process-solution-panel.html
This branch readds the binds that hides the FileSystem SolutionExplorer Indexcard when in web and shows it when in electron.
Open BPMN-Studio in web. -> Check SolutionExplorer if there is a folder icon.
Open BPMN-Studio in electron. ->Check if there is a folder icon now.
=> 💄Hide FileSystem SolutionExplorer when in web

src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts
The BPMN-Studio no longer adds extensionElements to the Start Event when its extensionElements is undefined.
Fixes: #546 
- Import [this](https://github.com/process-engine/bpmn-studio/files/2191579/Email.Senden.Bug.bpmn.zip) diagram (or any other diagram that has never been saved in the BPMN-Studio)
- Have a look at the diff view
- Notice that there are no changes
=> 🐛 Fix Creating Unneeded ExtensionElements

src/modules/bpmn-diff-view/bpmn-diff-view.ts
When there are no changes the diff view checks if the diagrams are the same or incomparable.
When only one of the two xml string was formatted, but the other one was not, the diff view thought that the diagrams are incomparable, even if they were the same.
This has been fixed.
- Import [this](https://github.com/process-engine/bpmn-studio/files/2191579/Email.Senden.Bug.bpmn.zip) diagram (or any other diagram that has never been saved in the BPMN-Studio)
- Have a look at the diff view
- Notice that there change list now says "The two diagrams are identical." instead of "The two diagrams are incomparable."
=> 🐛 Fix Incomparable Check

src/modules/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/property-panel/indextabs/extensions/sections/process/process.html, src/modules/property-panel/indextabs/extensions/sections/process/process.scss, src/modules/property-panel/styles/sections.scss
This PR improves the style for the process section and also improves the add- and remove buttons for all sections.
- Uses an icon instead of an simple x for the remove button on the process-section
- Adds a hover effect for the add-context-button and for the remove-context-button
Before:
After:
=> 💄Improve Style for Process Section and other Sections

src/contracts/bpmnmodeler/IModeling.ts, src/contracts/bpmnmodeler/IShape.ts, src/contracts/bpmnmodeler/bpmnElements/IPropertiesElement.ts, src/contracts/bpmnmodeler/bpmnElements/IPropertyElement.ts, src/contracts/bpmnmodeler/bpmnElements/index.ts, src/contracts/propertypanel/ISection.ts, src/modules/processengine/processengine.service.ts, src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/property-panel/indextabs/extensions/sections/process/process.ts, src/modules/task-list/task-list.ts
This PR fixes the bug when trying to create properties on a usertask before creating formfields.
Fixes #528 correctly.
Closes #565 
- `au run`
- check if you can create properties on (user)tasks und other elements 
=> 🐛Fix unable to create property on usertask bug

src/modules/navbar/navbar.scss, src/modules/processdef-list/processdef-list.html, src/modules/processdef-list/processdef-list.scss, src/modules/processdef-start/processdef-start.html, src/modules/processdef-start/processdef-start.scss
This PR fixes 3 issues:
1. Adds a maximum width for the diagram title in the navbar (#561)
1. Fixes the maximum width of the start-process-container (#562)
1. Fixes the style of the process-def-list for long diagram names (#566)
This also removes the process id from the process-def-list, since it was not really helpful.
Fixes: #561 
Fixes: #562 
Fixes: #566 
1. Issue
- Go to the detail view of any diagram with a really long name
- Notice that the navbar can no longer become too long
2. Issue
- Click on the 'Create Process Definition'-button
- Resize the browser/electron window
- Notice that the text boxes will no longer become too long
3. Issue
- Add a process diagram with a really long name
- Go to the process-def-list
- Notice that the layout of the table will …
=> 🐛 Fix Width Style Issues

src/contracts/file-input-event/IFile.ts, src/contracts/file-input-event/IInputEvent.ts, src/contracts/file-input-event/IInputTarget.ts, src/contracts/file-input-event/index.ts, src/contracts/index.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-list/processdef-list.ts
This branch:
- Adds a check for double solutions and diagrams.
- Shows a notification when the solution or diagram is already open.
Closes #545
Try to open the same diagram or solution twice with the SolutionExplorer.
=> ✨ Prevent Solution Explorer from Adding Solutions/Diagrams Multiple Times

src/modules/process-solution-panel/process-solution-panel.ts
This PR adds functionality to prevent the BPMN-Studio from adding existing diagramsto the Solution Explorer via file association.
- Fix adding existing diagram via file association
- Add diagram via file association
- (Change View)
- Add same diagram via file association
- Notice that it will no longer be added twice, but the detail view will still be shown after adding the same diagram a second time
=> 🐛 Fix Adding Existing Diagram Via File Association

electron_app/electron.js, package.json
This PR updates electron to 2.0.0.
This fixes the accept attribute of the file input so that one can no longer add files other than .xml or .bpmn.
- Open up the BPMN-Studio application
- Click on the "Import BPMN"-Button
- Notice that only .xml and .bpmn files can be added
- The whole BPMN-Studio application should be tested
- You may use the [test form](https://goo.gl/forms/83UtLkkIIePkAoWI2)
=> ⬆️ Update Electron

src/modules/bpmn-io/bpmn-io.ts, src/modules/property-panel/property-panel.ts
This PR fixes the XML and diff view for firefox.
The change handler was needed for the process solution explorer, but since changing the process via process  solution explorer reloads the detail view, this is no longer needed.
Fixes #568
- Open up the BPMN-Studio (FIREFOX)
- Go to the xml view and the diff view
- Go back to the diagram view
- Notice that the diagram is still there and editable
=> 🐛 Fix Diff And Xml View (Firefox)

aurelia_project/aurelia.json, package.json, src/main.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/solution-explorer-services/index.ts
~~⏰ Waiting on https://github.com/process-engine/solutionexplorer.repository.management_api/pull/1~~
**Changes**:
- Extract solution explorer instantiation into own class.
- Use the management solution explorer in panel. 
Build and link https://github.com/process-engine/solutionexplorer.repository.management_api/tree/feature/intial_setup
=> :sparkles: Use Management Api for SolutionExplorer

electron_app/electron.js, src/main.ts, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.scss, src/modules/config-panel/config-panel.ts
**Changes**:
- Display a info if the internal processengine is unused.
- Fix creating of main window.
PR: #664 
=> :sparkles: Display Info if the Internal ProcessEngine is Unused

src/app.ts, src/contracts/authentication/IAuthenticationService.ts, src/modules/authentication/authentication.service.ts, src/modules/authentication/index.ts, src/modules/config-panel/config-panel.ts, src/modules/dashboard/dashboard.ts, src/modules/diagram-detail/diagram-detail.ts, src/modules/process-list/process-list.ts, src/modules/process-solution-panel/process-solution-panel.ts, src/modules/processdef-detail/processdef-detail.ts, src/modules/processdef-list/processdef-list.ts, src/modules/task-list/task-list.ts, src/modules/user-login/user-login.ts
This PR cleans up all the leftovers from the `AuthenticationService` duplicates.
* renamed `NewAuthenticationService` to `AuthenticationService`
* renamed `hasToken()` to `isLoggedIn()`
=> Cleanup leftovers from the `AuthenticationService` duplicates.

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/diagram-detail/diagram-detail.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts
**Changes**:
- Add events to hide and show digram upload button in navbar.
- Fire new events when opening or closing diagram detail view.
- Listen in navbar for events and hide or show button accordingly.
PR: #670 
- Checkout + build electron
- Goto detail view of a process on the file system
- Click upload button (should be shown)
- Goto the uploaded process on the processengine
- Upload button is hidden, only start button is shown.
=> :bug: Only Show Diagram Upload Button on Diagram Detail View

package.json, src/modules/authentication/authentication.service.ts, src/modules/process-solution-panel/process-solution-panel.ts
Depends on:
* https://github.com/process-engine/iam/pull/8
* if not logged in, `getAccessToken()` will provide a dummy token that can be used to bypass authorization in the backend
* run the `process-engine-server` from https://github.com/process-engine/skeleton/pull/70
* run the BPMN-Studio and make sure it uses the previously started server
* if you can view deployed processes, deploy processes, etc. without being logged in, everything should work fine
=> 🔓Add dummy token fallback to authentication service

Jenkinsfile
This PR should fixes the jenkins windows build.
The npm package `windows-build-tools` is now globally installed on the slave and the python path is configured correctly.
- check this https://ci.process-engine.io/job/process-engine_node-lts/job/bpmn-studio/job/feature%252Ftest_windows_build/2/display/redirect
=> 🐛 Fix Windows Builds

src/modules/waiting-room/waiting-room.ts
This PR fixes stopping the polling in case that setTimeout does not cancel the timeout.
- Go to the Detail View of any diagram with user tasks
- Run the task and cancel the user task
- Repeat this multiple times
- Notice that the user task will never be rendered again after canceling it
=> 🐛 Fix Stopping Polling

src/app.ts, src/modules/processdef-detail/processdef-detail.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts, src/modules/waiting-room/waiting-room.html, src/modules/waiting-room/waiting-room.ts
This PR lets the user navigate to the process detail view from the waiting-room.
- npm run electron-start-dev
- start a process with an usertask
- if you are in the waiting-room, click on the `navigate to process` button
- goto the dashboard and click on the `UserTask` link of a correlation
- click on the continue button of a task
- click on the `navigate to process` button again
=> ✨Leave waiting-room and navigate to process detail view

src/modules/process-solution-panel/process-solution-panel.ts
This PR refreshes the identity after a user gets logged in/out, before the solution explorer gets refreshed. 
Maybe fixes the sync bug between the plan view and the solutionexplorer
=> 🐛Use Correct Identity Before Refreshing ProcessList

src/modules/dynamic-ui-checkbox-element/dynamic-ui-checkbox-element.ts, src/modules/property-panel/indextabs/forms/sections/basics/basics.html, src/modules/property-panel/indextabs/forms/sections/basics/basics.ts
- Fix Setting Default Value of Boolean Form Fields
- Make Default Value of Boolean Formfield Editable via Checkbox
Fixes #631
- Click on a user task
- Add a form field with type boolean
- Notice the checkbox when changing the default value
=> 🐛Fix Dynamic Ui Checkbox

package.json
This PR lets the reset bash script execute directly with `bash` when using `npm run reset`. 
This is necessary to use this command under Windows using Gitbash. 
*Keep in mind that you **have to use gitbash** when you run `npm run reset`* 
We maybe should think about a native Windows Batch/Powershell alternative for this. 
* Run `npm run reset` with gitbash
=> Make the reset script usable with windows

src/modules/process-solution-panel/process-solution-panel.scss
This PR makes the close button for single diagrams opened with the solution explorer filesystem black when hovering.
- open a single diagram with the solutiojn explorer
- move the mouse to the `x` button on the right of the process name
- see that it gets blacked
=> 🎨 Make the diagram close button black when hovering

electron_app/electron.js, src/app.html
This branch readds the lost feature of double clicking while BPMN-Studio is open.
Fixes #736
Open BPMN-Studio and double click a .bpmn-file.
=> ✨Readd double click feature while BPMN-Studio is open

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/main.ts, src/modules/config-panel/config-panel.ts
This PR fixes setting the base route for the non electron version.
This bug only occurs when the localStorage is cleared.
- Have a look at the base route in the status bar (lower left corner). This should no longer say "null"
=> 🐛 Fix Setting Default Base Route for Non Electron

src/modules/bpmn-io/bpmn-io.scss
This PR hides the scrollbar of the property panel, because it breaks the layout.
Fixes #744
- Open the Property Panel
- Add some Properties until the property panel is scrollable or open up the color selection
- Notice that there will no longer be a scrollbar that breaks the layout
=> 💄 Hide Scrollbar Of Property Panel

src/app.ts
Currently drag and drop is not supported.
For that reason, dragging a file to the BPMN-Studio would cause electron/the browser to open the file.
This PR simply prevents the BPMN-Studio from opening the file.
Fixes #724
- Drag and Drop a File to the BPMN-Studio
- Notice that nothing happens
=> ✨ Prevent Drag and Drop from Redirecting

src/modules/property-panel/indextabs/forms/sections/basics/basics.ts
Fixes #731 
This is more a _quickfix_. 
IMO we should discuss, if it should be possible for the user to save the diagram, if it contains a UserTask with a FormField, that has no associated type. 
* Create a UserTask
* Add a FormField
* Dont specify a form type
* Save the diagram
* Leave the Detail view
* Open the Diagram again
* The FormType of your added FormField should not be _custom type_. 
=> 🐛 Fix UserTask FormField type defaults to CustomType

README.md
This PR adds a documentation for the predefined scripts in the _package.json_ file which are callable via `npm run script`. 
The idea was to give a kind of overview of maybe helpful scripts. 
* Look at the readme
=> Add documentation for the scripts defined in the package.json

electron_app/electron.js, package.json, src/main.ts
Currently the 'Run BPMN-Studio'-Checkbox is disabled, because there is a bug when running the BPMN-Studio that way.
**Changes:**
1. Enable Auto Updater on Windows
2. Make Installation Directory Customisable
3. Disable 'Run BPMN-Studio'-Checkbox
**Issues:**
Closes #715
Closes #739
PR: #1018
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration …
=> 🐛 Fix Auto Update on Windows

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
**Changes:**
1. Adds a check to validate if the diagram name hasn't changed yet when renaming.
This won't show the error message "Diagram with same name already exists" when the user didn't type anything yet.
**Issues:**
Closes #1062 
PR: #1063
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the …
=> 🐛Check for Same Diagram Name

aurelia_project/environments/dev.ts, aurelia_project/environments/prod.ts, aurelia_project/environments/stage.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/status-bar/status-bar.ts
---
**Changes:**
1. Fixes the appearance of the _Save unsaved changes_ modal when trying to navigate to the XML- or Diff - View.
**Issues:**
Closes #1229 
PR: #1233 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …
=> 🐛 Fix Unsaved Change Modal When Switching to the Diff- or XML View

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-tools-right/diagram-tools-right.html, src/modules/design/diagram-tools-right/diagram-tools-right.ts
> If you find a better icon, just let me know.
**Changes:**
1. Add fit to viewport functionality
2. Fit diagram to viewport on import
**Issues:**
Closes #1075 
PR: #1224
- **Notice that the diagram should now fit the viewport**
- Move the viewbox/ change the zoom level
- Click on the <img width="20" src="https://user-images.githubusercontent.com/20394992/50589835-7f901180-0e88-11e9-858f-267def095bb8.png"> icon
- **Notice that the diagram should now fit the viewport**
<details>
<summary>
</summary>
<br> …
=> ✨ Add Functionality to Set The Viewbox

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
---
**Changes:**
1. Adds the cause to the error message when the user tries to open a remote Solution which is already opened.
**Issues:**
Closes #1260 
PR: #1261
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
=> 🚸 Improve error message when trying to open an already opened remote Solution

src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts
**Changes:**
1. Add fit to viewport functionality to inspect correlation.
**Issues:**
Closes #1288
1. Start BPMN-Studio
2. Start a process
3. Check the inspect correlation feature, see that the diagram now fits the viewport on opening.
=> ✨Fit Diagram to Viewport on Inspect Correlation

aurelia_project/native/fs.js, aurelia_project/native/os.js, aurelia_project/native/path.js, aurelia_project/native/util.js
With the update of the aurelia-cli the dev web version sadly broke.
The error seems to be that Aurelia tries to get the native modules but can't since they are not defined in the web version.
This Branch adds a simple else block to define the native modules anyway.
**Changes:**
1. Add else block for each native dependency.
1. Start BPMN-Studio with `npm run start_dev`.
2. Navigate to `localhost:9000`.
=> 🐛Fix Dev Web Version

electron_app/electron.js
With Version 4.0.0 the developers of Electron introduced some new functions that make the handling of instances in Windows much easier. This PR adds all changes needed to use the new Functions and therefore fix the double click feature on Windows.
**Changes:**
1. Add the correct functionality to handle instances and the double click on windows.
**Issues:**
Closes #1310 
Closes #646 
1. Build BPMN-Studio on Windows.
2. Install it.
3. Start it via double click on a .bpmn file.
4. Double click on another file.
=> 🐛Fix Double Click / Instance Handling on Windows

src/contracts/bpmnmodeler/ILinting.ts, src/contracts/bpmnmodeler/IValidateIssue.ts, src/contracts/bpmnmodeler/IValidateIssueCategory.ts, src/contracts/bpmnmodeler/IValidateResult.ts, src/contracts/bpmnmodeler/index.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts
**Changes:**
1. Refactor the validation of the diagram with help of the bpmn-linter.
2. Make it possible to save on the file system even if the diagram is not valid.
3. Make it possible to print even if the diagram is not valid.
**Issues:**
Closes #1348
2. Open a file system Solution.
3. Make the diagram invalid by, for example delete the end event.
4. See that you still can save it but not deploy it.
5. Now switch to a diagram on a remote solution.
6. Make it invalid.
7. Try to save/start it.
=> ♻️Refactor Diagram Validation

src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.ts
This PRs aims to solve the sporadic appearance of a "diagram change" when the user is just clicking around the diagram and not really changing anything.
**Changes:**
1. Solidify Diagram Change Handling in Service Tasks
2. Open any diagram.
3. Create a Service Task.
4. Save the diagram.
5. Reload BPMN-Studio (Cmd+R).
6. Now Click around the diagram without changing anything.
7. There should be no "edited" appearing the navbar.
=> ♻️Solidify Diagram Change Handling in Service Tasks

src/modules/inspect/heatmap/heatmap.ts
**Changes:**
1. Fix a Warning/Error in the heatmap
**Issues:**
Closes #1402 
1. Start BPMN-Studio
2. Produce a Process Instance
3. Navigate to Heatmap
4. Navigate to Inspect Correlation
4.1. See that the described behavior doesn't appear anymore. 
=> 🐛 Dont Attach Viewer When Container is not Present

electron_app/electron.js, src/main.ts
**Changes:**
1. Add version to update message.
2. Add possibility to Show release notes before updating.
PR: #1423
1. Change the version in the `package.json` to `4.23.1`.
2. Build it with `npm run electron-build-macos`.
3. Start BPMN-Studio from newly created `dist` folder.
=> ✨Show Version and Release Notes in Auto Updater

package-lock.json, package.json, src/app.scss, src/modules/design/bpmn-io/bpmn-io.html, src/modules/design/bpmn-io/bpmn-io.scss
**Changes:**
Change the background of the linter button to red, if the diagram has linter errors.
This was done to make the linter button more prominent, in case the user makes errors and has the linter disabled.
**Issues:**
Closes #1405 
PR: #1438
- Create a diagram
- Keep the linter messages hidden
- Provoke a linter error
- See that the deploy button is disabled and the linter button is red.
Should look something like this:
=> ♻️ Make linter errors more prominent

Jenkinsfile, package-lock.json, package.json, test/e2e/src/dashboard.spec.ts, test/protractor.conf.js
**Changes:**
1. Adds the `jasemine-spec-reporter` to view the current running test instead of just dots.
**Issues:**
PR: #1437
When running the e2e tests, you will now get a far more detailed log output.
=> 🔧 Improve e2e Test Log

src/modules/design/bpmn-io/bpmn-io.ts
**Changes:**
1. Add an early exit when there are no FormFields specified yet.
**Issues:**
Closes #1445
Follow the instructions in the mentioned Issue.
See that the faulty behavior doesn't occur anymore.
=> 🐛 Fix Copy of UserTasks When no Fields are Specified

.github/ISSUE_TEMPLATE.md, Jenkinsfile, README.md, electron_app/electron.js, package.json, src/modules/start-page/start-page.html, src/modules/start-page/start-page.ts
We do not have any need for building a Linux version at the moment.
Should the need arise, we will revisit this decision. :+1:
=> Remove linux build from Jenkinsfile, README, et al.

src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/think/diagram-list/diagram-list.ts
This PR avoids an HTTP request overload what breaks the studio.
1. Use setTimeout instead of setInterval on ProcessList
2. Use setTimeout instead of setInterval on TaskList
3. Use setTimeout instead of setInterval on SolutionExplorer
4. Use setTimeout instead of setInterval on DiagramList
Closes #1471 
PR: #1470 
=> :twisted_rightwards_arrows: :recycle: Use setTimeout instead of setInterval

package-lock.json, package.json
The Runtime now supports a `can_manage_process_instances` claim, which indicates a super admin. 
These types of admins are always allowed to see any Correlation and ProcessModel of any user.
Part of https://github.com/process-engine/process_engine_runtime/issues/336
PR: #1474
Best use our IdentityServer for this
- Start a ProcessInstance as User `alice` (has the super admin claim)
- Start a ProcessInstance as User `bob` (is a normal user)
- Login as `alice` and look at the Correlation list
- The user can see two process instances
- Login as `bob` and look at the Correlation list
- The user can only see his own process instance
=> ✨Add super admin claim to ProcessEngine-Runtime

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/navbar/navbar.html, src/modules/navbar/navbar.ts
1. Remove unnecessary titles from the navbar
2. Allow saving diagrams with linter errors
Closes #1482 
PR: #1485 
Follow the steps from the referenced issue.
=> ✨Allow Saving Diagrams With Linter Errors

src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts
1. Add modal to edit an element's documentation on double click
PR: #1486 
- open a diagram from the file system
- double click on the docu input on the property panel
- see the modal
- edit the text
- close the modal
- save the diagram
=> ✨Add Docu Modal

src/contracts/inspect-correlation/inspect-panel/log-viewer/constants.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.ts
1. Add the columns `FlowNodeId` and `FlowNodeInstanceId` to the LogViewer.
2. Enhance the LogViewer's sorting, so that it can deal with `undefined` values.
Closes #1491
PR: #1492
- Run a ProcessModel
- After it is finished, go to the `Inspect` view and select the logs for the executed ProcessInstance
- See that the logs will now contain the `FlowNodeId` and `FlowNodeInstanceId` for each entry.
- Note that ProcessInstance logs will not have any of those IDs associated with them.
The view should look like this:
=> ✨ Add FlowNodeIds to LogViewer

Jenkinsfile, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.html, src/modules/design/property-panel/indextabs/general/sections/timer-event/timer-event.ts
Remove the `Cyclic` Timer Option from the Property Panel, when modelling BoundaryEvents or IntermediateEvents. 
See issue for more details.
Closes #1493
PR: #1495
When modelling IntermediateTimerCatchEvents and TimerBoundaryEvents, it will no longer be possible to select `cyclic`, when opening the DropDown Menu inside the Property-Panel.
The Option is still available for StartEvents.
=> 🔥 Prevent use of cyclic timers

src/app.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/task-list/task-list.scss, src/modules/navbar/navbar.scss
1. Remove dblclick EventListener
2. Improve discoverability of docs modal
Before:
After:
Closes #1499 
PR: #1503 
=> Improve Discoverability of Docs Modal

aurelia_project/environments/dev.ts, electron_app/electron.js, src/contracts/diagram/IDiagramState.ts, src/contracts/diagram/index.ts, src/contracts/index.ts, src/contracts/solution-explorer/ISolutionEntry.ts, src/contracts/solution-explorer/ISolutionService.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.html, src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/design/property-panel/property-panel.ts, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/inspect/inspect.ts, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/start-page/start-page.html, src/modules/start-page/start-page.ts, src/modules/status-bar/status-bar.ts, src/services/solution-explorer-services/OpenDiagramStateService.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts, src/services/solution-explorer-services/OpenDiagramsStateService.ts, src/services/solution-explorer-services/index.ts, src/services/solution-service/SolutionService.ts
1. Add Open Diagrams Functionality
1.1 Save diagrams in local storage (diagrams don't have to be saved anymore when changing the diagram)
1.2 Remove "Quit"- and "Leave"-modal
1.3 Save viewbox of open diagrams
1.4. Save selected element
2. Move Remote Solutions to the Bottom of the SolutionExplorer
3. Remove "Single Diagrams"
Closes #374 
PR: #1516
- Open Diagram from Filesystem
- **Notice that they will be opened as "Open Diagrams"**
- Change the diagram
- **Notice that the diagram will be marked with a circle in the solution explorer**
- Close the unsaved diagram
- **Notice that a modal will appear**
- Click Save
- **Notice that the diagram will be saved.**
- Click Don't Save
- **Notice that the diagram wont be saved**
- Click Cancel
- Make some …
=> ✨ Add Open Diagrams Functionality

src/modules/design/bpmn-io/bpmn-io.ts
1. Prevent Saving Diagram State of Remote Diagrams
PR: #1533 
- Open some remote diagrams
- Have a look at the localStorage
- **Notice that remote diagrams will no longer be saved in localStorage**
=> 🐛 Prevent Saving Diagram State of Remote Diagrams

src/modules/design/design.html, src/modules/design/diagram-detail/diagram-detail.ts
1. Show a warning modal if a diagram with same id and name already exists on the target remote solution where the user is going to deploy.
Closes #1050 
PR: #1532
- deploy a diagram which does not exist on the remote solution
- deploy a diagram which does exist on the remote solution
=> 💄Add deploy warning modal

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Displaying Diagram Location for Untitled Diagrams
PR: #1550 
- Hit CMD+N
- **Notice that the diagram location will be empty instead of 's'**
=> 🐛 Fix Displaying Diagram Location for Untitled Diagrams

src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/service-task-service/service-task-service.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.ts
1. Fix the new generation of a `<camunda:Properties>` element, if a ServiceTask already has an empty PropertiesElement.
2. Remove empty ExtensionElements and PropertieElements when last Property gets deleted.
3. Fix generating an empty Property when initializing a ServiceTask.
4. Refactor ExternalTask, HTTP-Service-Task and ServiceTask component and add ServiceTaskService.
Closes #1525 
Closes #1553 
PR: #1534
- Add a ServiceTask
- Configure a HTTP ServiceTask and run the process
- be sure that all works as expected
- repeat these steps with an ExternalTask
- Check that the XML does not contain empty Properties/PropertiesElement or ExtensionElements, only if a HTTP ServiceTask or ExternalTask is configured.
=> ♻️🐛 Do not Generate a New Camunda Property Objects 

src/contracts/notification/INotification.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/notification-service/notification.service.ts
1. Allow optional ToastrOptions 
2. Fix style of notifications
Closes #1558 
PR: #1563 
checkout the branch and check whether the notification described in #1558 looks now like:
=> 💄Fix notification style

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.html, src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Always enable delete diagram button
2. Remove `not supported `notification
3. Add custom modal message if diagram contains changes
4. Handle deleting diagram if it is open
Closes #1564 
PR: #1565 
- open a diagram
- click on the trash icon which shows up when hovering over the selected diagram entry
- use the modal to delete the diagram
- see that it has been deleted.
If you are on a remote solution you get navigated to the start-page after deletion has finished.
If you are on a file system solution you get navigated to the next diagram which is opened as Open Diagram. When there is no other diagram opened you will get also navigated to the start-page.
You have not the possibility to save a file with unsaved changed while deleting it. The behaviour is inspired by VSCode.
=> ✨Allow delete opened diagrams

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1. Add try/catch while loading the internal process engine
2. Fix bug where the internal solution does not get added to the solution explorer if its HTTP server isn't ready
Closes #1566 
PR: #1567 
- generate a DB with more than 500 running process instances
- build the electron app of the studio
- start it
- see that all solutions get opened
=> 🐛Fix initial loading of solutions

src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss, src/modules/status-bar/status-bar.ts
1. Disable buttons if the update has been started
2. Improve the `Abort Download` button
Closes #YourIssueNumber
PR: #1578 
- download and install the studio version from [here](https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/feature%2Favoid_update-error_on_double-click/4/artifacts)
- If you have already installed version 5.6.0, you must first delete it from the updater cache
```
macOS: ~/Library/Application Support/Caches/bpmn-studio-updater/pending
Windows: C:\Users\<user>\AppData\Local\bpmn-studio-updater\pending
```
- start the studio and update it
=> Avoid update error on double click

src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts
1. Fix still open delete-diagram modal on web version
Closes #1579 
PR: #1580 
- look at #1579
=> 🐛 Fix bug where the delete diagram modal is still open after deletion

src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.ts, src/modules/live-execution-tracker/live-execution-tracker.ts
1. Refactor types and interfaces and rename _userTasks to _tasks
2. Add emptyActivities to task-list
3. Fix bug where the LET tries to open a dynamicUiModal after navigate to it with an empty activity
Closes #YourIssueNumber
PR: #1581 
- start some processes containing empty activities
- switch to the inspect view and see that they are on the task-list
=> ✨Add empty activities to task list

src/modules/design/bpmn-io/bpmn-io.scss, src/modules/design/bpmn-xml-view/bpmn-xml-view.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/property-panel.scss, src/modules/inspect/heatmap/heatmap.html, src/modules/inspect/heatmap/heatmap.scss, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.html, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.scss, src/modules/inspect/token-viewer/token-viewer.scss, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss, src/modules/start-page/start-page.html, src/modules/start-page/start-page.scss, src/modules/status-bar/status-bar.scss
Now we have the following font-sizes:
12px: for the PropertyPanel content, diagram/solution path at the SE, status-bar
14px: normal
16px: middle
20px: large
1. Unify font-size
2. Remove unused CSS classes
3. Use h3 as HTML element for empty_messages on the views and for the start-page title
Closes #1072 
PR: #1582 
- start the studio and look at it
=> 💄Unify font size

src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.scss, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts
1. Add enlarge button to external task payload
2. Remove unneeded CSS
Closes #1592 
PR: #1603
- Click on an External Task
- **Notice that there is a enlarge button under 'Payload' which opens a modal in which one can change the payload of the external task.**
=> ✨ Add Enlarge Button to External Task Payload

src/modules/inspect/task-list/task-list.html, src/modules/task-dynamic-ui/task-dynamic-ui.ts
1. Fix the empty modal when working off tasks
2. Fix _updateTasks is not a function bug when using the task-list pagination
Closes #1613 
Closes #1614 
PR: #1615 
- look at #1614
=> 🐛Fix empty modal and updating tasks when using the pagination

src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.html, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.scss, src/modules/inspect/task-list/task-list.ts
1. Update the task-list only if a task is waiting or has been finished
First part of #1594 
PR: #1619 
- open the studio and navigate to the inspect view
- see that the task-list gets updated when switching to another remote solution
- open up the studio for a second time (e.g. web version) and connect to the same remote solution
- start a process with user/manual task or empty activity
- see that the task-list gets updated on the first studio instance
- it should get updated also when finishing a task.
=> ✨ Update the task-list only if a task is waiting or has been finished

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/services/solution-service/SolutionService.ts
1. Remove unused CSS class
2. Use solution-entry__header class for open-diagram solution too
4. Show collapse icon also on open-diagrams solution
5. Persist the open-diagram solution collapse state on local storage
6. Allow to click on open-diagrams header
7. Get the hidden/collapse state for open-diagrams solution while open it
Closes #1616 
PR: #1617 
- try to collapse the open-diagrams solution 
- also have a look whether the solution has the same state after reload/reopen the studio
=> ✨Collapse open diagrams

src/modules/inspect/dashboard/dashboard.ts, src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.ts
1. Use process instance instead of processInstanceId as parameter
2. Add event listener to update the processlist
3. Use onProcessError event listener to handle stopped correlation/processinstance
4. Fix bug where stopped entries get increased when using the pagination
Part two of #1594
Closes #1620
PR: #1621 
- try to reproduce the #1620 
- open the inspect view
- switch between some remote solutions
- see that the process-list gets updated
=> ✨Use events on process list

src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.scss, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.ts
1. Fix target process selection for call activities
2. Add an input field to select a process from another solution
Closes #1588
PR: #1606
- Add a call activity to a diagram
- Select a process from the current solution
- Change the solution and open the same process
- **Notice that the correct process will be displayed in the 'Call Activity' section of the property panel.**
> This fix could be improved by using a [datalist](https://developer.mozilla.org/de/docs/Web/HTML/Element/datalist), which is not working in the electron version that we are using, or by using a [input group](https://getbootstrap.com/docs/4.3/components/input-group/#buttons-with-dropdowns), which leads to style issues when used in the property panel.
=> 🐛 Fix Target Process Selection for Call Activities

src/modules/design/design.html, src/modules/design/diagram-detail/diagram-detail.ts
1. Persist Selected Remote Solution for 'Multiple Connected Process Engines Found' modal
Closes #1608 
PR: #1609
- Connect multiple ProcessEngines
- Deploy a process to a ProcessEngine
- Deploy another process
- **Notice that the previously selected ProcessEngine will already be selected**
=> ✨ Persist Selected Remote Solution for 'Multiple Connected Process Engines Found' Modal

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix diagram creation
2. Fix focus on 'renameDiagramInput'
3. Stop validating when create diagram input gets displayed
4. Fix validating 'createDiagramInput' after one diagram was created
5. Fix validating 'renameDiagramInput' after one diagram was renamed
Closes #1631 
PR: #1633
- Create new diagram
- **Notice that the diagram creation works.**
- Rename a diagram
- **Notice that the rename input is directly focused.**
- Create a second diagram
- **Notice that the diagram creation still works.**
- Rename a second diagram
- **Notice that the renaming of diagrams still works.**
=> 🐛 Fix Diagram Creation

electron-builder/alpha/electron-builder.yml, electron-builder/beta/electron-builder.yml
1. Remove file associations for alpha releases
2. Remove file associations for beta releases
PR: #1635 
- build the app for macOS or Windows
- install the app and recognize whether the file association is still set to the stable studio version
=> 🔥Remove file associations for alpha and beta

src/modules/inspect/inspect-correlation/inspect-correlation.ts, src/modules/inspect/inspect.ts, src/modules/live-execution-tracker/live-execution-tracker.ts
1. Save and load the TokenViewer's collapse state
Closes #1647 
PR: #1641 
- open the LET or inspect-correlation view
- expand the tokenviewer 
- reload/restart the studio
- see that is is still expanded
=> Save tokenviewer collapse state

src/contracts/bpmnmodeler/IOverlayManager.ts, src/contracts/bpmnmodeler/IOverlays.ts, src/contracts/bpmnmodeler/index.ts, src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.html, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.ts, src/modules/inspect/inspect-correlation/inspect-correlation.html, src/modules/inspect/inspect-correlation/inspect-correlation.ts, src/modules/inspect/inspect.html, src/modules/inspect/inspect.ts, src/modules/live-execution-tracker/contracts/ILiveExecutionTracker.Repository.ts, src/modules/live-execution-tracker/contracts/ILiveExecutionTracker.Service.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/repositories/live-execution-tracker.repository.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts
1. Add Overlays to Elements With Error
2. Refactor LiveExecutionTrackerService
3. Fix Displaying of Notification in Case of Incorrectly Configured CallActivity
4. Add Tooltips to Overlays
PR: #1642
- Run a process with at least one element that creates an error
- **Notice that there will be a button (<img width="20" src="https://user-images.githubusercontent.com/20394992/62776590-474e5280-baab-11e9-8ef2-03c5ebe86908.png">) to navigate to the inspect-correlation view**
- Click on the button
- **Notice that the inspect-correlation view will be opened with the correct processInstance and the error element already selected.**
- Run a process with a call activity with an invalid target process
- **Notice that the two overlays will be displayed next to each other**
=> ✨ Add Overlays to Elements With Error

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Diagram Creation When Diagram Called 'Untitled' Exists
PR: #1648
- Open a diagram called/starting with 'Untitled'
- Create a new diagram via CMD/CTRL + N
- **Notice that the new diagram will be created correctly.**
=> 🐛 Fix Diagram Creation When Diagram Called 'Untitled' Exists

electron_app/electron.js
1. Link to the Getting Started instead of outdated documentation
PR: #1655 
- start the electron app
- look at the electron context menu 
- click on `help`
- click on `Getting Started`
- realize that a new tab/window of your standard browser has opened the Getting Started page
=> 🚚 Link to the Getting Started instead of outdated documentation

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Avoid Displaying Notification When Creating Diagram
Closes #1663 
PR: #1662
- Click on the 'Create new diagram'-button next to a solution (<img width="20" src="https://user-images.githubusercontent.com/20394992/63252672-82514280-c270-11e9-863a-788c4bdf94de.png">)
- Enter a diagram name
- Hit enter or klick anywhere
- **Notice that no notification will be displayed.**
=> :twisted_rightwards_arrows: :bug: Avoid Displaying Notification When Creating Diagram

src/modules/inspect/inspect.ts
1. Fix Reloading Inspect After Diagram Was Removed
Closes #1653 
PR: #1668
- Go to Inspect
- Remove the diagram (outside the BPMN Studio).
- Reload the BPMN Studio
- **Notice that the BPMN Studio will still be displayed instead of a white screen.**
=> 🐛 Fix Reloading Inspect After Diagram Was Removed

src/modules/design/bpmn-io/bpmn-io.ts
1. Recover Diagram State After Modeler Was Attached
2. Fix Restoring Viewbox State
3. Fit Diagram to Viewport if Viewbox Was Not Persisted
Closes #1685 
PR: #1688
- Create a diagram.
- Deploy it to a PE.
- Switch to the Inspect tab of the PE.
- Switch back to the designer.
- Click on the same diagram but on the FS in the SolutionExplorer.
- Open a local diagram
- Move the diagram
- Change the diagram
- Change back to the previous diagram
- Reload
- **Notice that the viewbox will be restored.**
=> 🐛 Fix Setting Viewbox

src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.ts, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts
1. Save Input Height of ScriptTask Input Field
2. Save Input Height of ExternalTask Payload Input Field
3. Save Input Height of Docs Input Field
Closes #1681 
PR: #1697
- Open up a diagram
- Click on a ScriptTask/External Task/anything
- Resize the resizable inputs
- Reload or change the diagram
- **Notice that the inputs will keep their height.**
=> ✨ Persists Property Panel Input Heights

package-lock.json, package.json, src/modules/design/property-panel/indextabs/general/general.ts, src/modules/design/property-panel/indextabs/general/sections/link-event/link-event.html, src/modules/design/property-panel/indextabs/general/sections/link-event/link-event.ts
1. Update bpmn-elements_contracts
2. Add link event section
Closes #1644 
PR: #1684 
- create/open a diagram
- add an intermediate event
- change its type to `Link catch/throw event`
- see that the `Link Event `section is shown on the PropertyPanel
- change the `Link Name`
- save the diagram
- reload
- select the element
- see that the name is correct
=> ✨Add intermediate link events to property panel

electron_app/electron.ts
1. Open bpmn.io in browser instead in electron
Closes #1477 
PR: #1682 
- click on the bpmn.io icon on the modeler/viewer
- click on the bpmn.io link
- see that it opens up in a new browser tab
- open the about window
- see that it opens in an electron window
- same for the identity server login/logout
- the links on the dashboard view should open in the same electron window (BPMN Studio)
=> ✨ Open bpmn.io in browser instead in electron

src/contracts/diagram/IDiagramState.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/solution-explorer-services/OpenDiagramStateService.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts
1. Fix bug where a diagram has changed notification appears
PR: #1712 
- check that the `change`, `restore` or `rename` notification only appears if the changes were not made by the BPMN Studio
=> 🐛Fix diagram has changed notification bug 

electron_app/electron.ts
1. Fix Icon Path for About Window
PR: #1715 
- Open the About Window
- **Notice that the BPMN Studio icon will be displayed**
=> 🐛 Fix Icon Path for About Window

aurelia_project/environments/dev.ts, src/app.html, src/modules/deploy-modals/deploy-modals.html, src/modules/deploy-modals/deploy-modals.ts, src/modules/design/design.html, src/modules/design/design.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/deploy-diagram-service/deploy-diagram.service.ts, src/services/deploy-diagram-service/index.ts, src/services/save-diagram-service/index.ts, src/services/save-diagram-service/save-diagram.service.ts, src/services/solution-explorer-services/OpenDiagramsSolutionExplorerService.ts
1. Move Saving to Save Diagram Service
2. Move Deploying to Deploy Diagram Service
3. Add Context Menu Entry for Deploying
4. Fix Saving All Diagrams
5. Add 'Saving Diagrams' Modal
Closes #1395
Closes #1710 
PR: #1696
- Check if saving/save as is still possible via 'Design'
- Check if deploying is still possible via 'Design'
- Right click on a diagram from a local solution
- Click on Deploy
- **Notice that the diagram will be deployed.**
=> ✨ Make Diagrams Deployable via Solution Explorer

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Active Diagram Highlighting in SolutionExplorer
Closes #1695
PR: #1723
- Open multiple solutions that contain the same diagram
- Deploy the diagram
- **Notice that only the diagram entry of the remote solution is highlighted.**
=> 🐛 Fix Active Diagram Highlighting in SolutionExplorer

src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts
1. Fix displaying `No Correlations found` message
Closes #1745 
PR: #1750 
=> 🐛 Fix bug where no correlations found message was displayed after a reload

Jenkinsfile
1. Refactor CI Pipeline to keep only the last 20 builds
2. Add step `Check if build is required` to check if a commit was made by the CI user
3. Add `expression {buildIsRequired == true}` condition to all steps to skip builds for ci user commits
PR: #1760
Run some builds.
=> 👷 Prevent builds for automated commits

package-lock.json, package.json
Recently, a build error related to `aurelia-validation` came up.
See this build, for example:
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fbpmn-studio/detail/develop/261/pipeline/62#step-125-log-104
Updating the package to 1.5.0 solves this issue.
PR: #1761
- Build the application
- There should be no more errors
=> 🐛 Fix aurelia-validation build error

src/modules/design/design.html, src/modules/design/diagram-detail/diagram-detail.ts
1. Start a process with the modeled StartToken annotation as initial token payload
PR: #1779 
- start a process
- start a process with the custom start modal
- start a process which contains a start event with a text annotation starting with `StartToken:`
- start a process with the custom start modal and a start event with a start token
- see that the expected token is used for starting the process
=> ✨Start process with initial token

electron_app/electron.ts, src/main.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Update the runtime version and authority while fetching the processmodels.
2. Fix bug where the studio does not add solutions if the internal processengine is not running
Closes #1775 
Closes #1772 
Closes #1752 
PR: #1781 
=> 🐛Refresh solutionentries and open solutions without an internal pe

electron-builder/alpha/electron-builder.yml, electron-builder/beta/electron-builder.yml, electron-builder/stable/electron-builder.yml, package-lock.json, package.json, src/modules/live-execution-tracker/contracts/ILiveExecutionTrackerRepository.ts, src/modules/live-execution-tracker/contracts/ILiveExecutionTrackerService.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/repositories/live-execution-tracker.repository.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts
1. Fix colorization of `ErrorEndEvents`
2. Add `onProcessError` event listeners to LET
3. Fix some vulnerabilities through `npm audit`
4. Add `config` files to app resources (required for the runtime Post-Migrations)
Closes #1800 
Part of https://github.com/process-engine/process_engine_runtime/issues/400
PR: #1801
- Run a Process that uses an `ErrorEndEvent`
- See that everything is colorized correctly
=> 🐛 Fix ErrorEndEvent colorization

src/modules/design/design.ts
1. Fix Switching From Inspect to Design View
Closes #1807
PR: #1808
- Click on `Inspect`
- Click on `Design`
- **Notice that the BPMN Studio will navigate back to design**
=> 🐛 Fix Switching From Inspect to Design View

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix Renaming Unopened Diagrams
Closes #1810
PR: #1811
- Open a solution
- Rename a diagram that is not shown in `Open Diagrams`
- **Notice that the renaming was successful.**
=> 🐛 Fix Renaming Unopened Diagrams

src/modules/design/diagram-tools-right/diagram-tools-right.html
1. Fix Broken Icon
PR: #1822
- Click on any element
- Open the color selection
- **Notice that the color picker buttons have an eye dropper icon.**
=> 🐛 Fix Broken Icon

src/modules/inspect/inspect.html, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts
1. Fix Updating Lists in Dashboard
2. Clean up Code
3. Fix Removing No Longer Needed Subscriptions
Closes #1819 
PR: #1825
- Deploy a diagram with an enabled TimerStartEvent that creates an active task every few seconds
- Go to the Dashboard view.
- The total count of the process-list/task-list should change every time the process gets started.
- Switch to the Inspect Correlation view.
- Switch back to the Dashboard view.
- **Notice that the total count of the process-list/task-list still changes every time the process gets started.**
=> 🐛 Fix Updating Lists in Dashboard

src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/authentication-service/electron.oidc-authentication-service.ts
1. Fix Publishing Login Event
2. Clear Diagrams in SolutionExplorer When Not Authorized
3. Stop Polling When Unauthorized
Closes #1828 
PR: #1833
- Connect to a BPMN Studio with GodToken disabled
- Login
- Deploy some processes
- Logout
- **Notice that the SolutionExplorer will no longer show any diagrams.**
- **Notice that the 'You don't have the required permissions to list process models.' error message will no longer get spammed.**
=> 🐛 Fix Refreshing Diagrams in Solution Explorer on Login

src/modules/design/diagram-detail/diagram-detail.ts, src/services/save-diagram-service/save-diagram.service.ts
1. Fix Saving After Canceling Saving Dialog
PR: #1837
- Hit CMD+S
- Cancel the saving dialog
- Hit CMD+S
- **Notice that the saving dialog gets displayed.**
=> 🐛 Fix Saving After Canceling Saving Dialog

src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts, src/modules/think/diagram-list/diagram-list.ts
1. Fix Publishing Login Event
2.  Fix Updating Think after Login
3.  Fix Updating ProcessList after Login
4.  Fix Updating TaskList after Login
5.  Fix Updating CronjobList after Login
6. Fix Removing Subscriptions in TaskList
7. Fix Removing Subscriptions in ProcessList
8. Fix Removing Subscriptions in CronjobList
Closes #1829
PR: #1832
- Connect to a BPMN Studio with GodToken disabled
- Go to Inspect View
- Login
- **Notice that the ProcessList will show the active ProcessInstances**
> Same for TaskList, CronjobList & Think View
=> 🐛 Fix Updating Studio after Login

src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.ts
1. Avoid Setting Edited Flag When Selecting CallActivity
2. Fix Selecting CallActivity Without PropertiesElement
3. Fix Selecting CallActivity With Removed StartEventId
Closes #1842
Closes #1843
PR: #1844
#1842
- Select a CallActivity with a configured `StartEventId`
- Clear the `StartEventId` input
- Select another element
- Select the CallActivity
- **Notice that the CallActivity section will still appear in the PropertyPanel.**
#1843 
- Create a new diagram called `a.bpmn`
- Create a new diagram called `b.bpmn`
- Add a CallActivity to `b.bpmn` and select `a` as `Process`
- Save the diagram
- Click on another element
- Click on the CallActivity
- Click on another element
- Click on the CallActivity
- **Notice that the `edited` flag won't appear.**
=> 🐛 Fix Selecting CallActivities

src/modules/inspect/dashboard/services/dashboard.service.ts, src/modules/inspect/process-list/process-list.ts, src/modules/inspect/task-list/task-list.ts, src/services/deploy-diagram-service/deploy-diagram.service.ts
1.  Fix Updating TaskList After Reload
2. Update TaskList on ProcessTerminated
3. Only Update Dashboard Repository if ActiveSolutionEntry Changed
4. Remove Unnecessary Dot in Error Message
Closes #1846
Closes #1847
PR: #1848
- Deploy a Diagram with a TimerStartEvent that runs every few seconds
- Go to Dashboard View
- Reload
- **Notice that the TaskList gets updated.**
- Stop a ProcessInstance via the ProcessList
- **Notice that the TaskList gets updated.**
=> 🐛 Fix Updating TaskList

src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.scss
1. Add Tooltip to Disabled Navigation Button
PR: #1845
- Add a CallActivity
- Write the name of a process that does not exist in the `Process` input
- Hover over the disabled `Navigate to called process` button
=> ✨ Add Tooltip to Disabled Navigation Button

src/modules/inspect/cronjob-list/cronjob-list.ts, src/modules/inspect/dashboard/dashboard.ts
1. Show Cronjob List of InternalRemoteSolution if Active Solution is Local Solution
2. Avoid Updating Dashboard if Active Solution was Changed to Local Solution
Closes #1860 
PR: #1861
- Deploy a diagram with a TimerStartEvent to the InternalRemoteSolution
- Select a diagram from a local Solution
- Go to the Dashboard View
- **Notice that the CronjobList gets displayed and contains the deployed diagram.**
- Connect another RemoteSolution
- Deploy a diagram with a TimerStartEvent to the InternalRemoteSolution
- Select a diagram from that RemoteSolution
- Go to the Dashboard View
- Select a diagram from a local Solution
- **Notice that the CronjobList still gets displayed and contains the deployed diagram from the connected RemoteSolution.**
=> 🐛 Fix Displaying CronjobList

Jenkinsfile
1. Avoid Creating Tarball When Build is Not Required
PR: #1862
=> 🐛 Avoid Creating Tarball When Build is Not Required

src/contracts/diagram/DeployResult.ts, src/contracts/diagram/index.ts, src/modules/design/diagram-detail/diagram-detail.ts, src/services/deploy-diagram-service/deploy-diagram.service.ts
1. Avoid Navigating after Deploying via Context Menu
2. Remove Unneeded Code
Closes #1852 
PR: #1868
- Open a solution
- Right click any diagram
- Click 'Deploy'
- **Notice that the diagram gets deployed but not shown**
- Click on the deploy button
- **Notice that the BPMN Studio still navigates to the diagram when deploying via the deploy button.**
=> 🚸 Avoid Navigating after Deploying via Context Menu

src/modules/inspect/process-list/process-list.ts
1. Remove Old Sorting Mechanism
Closes #1871 
PR: #1872
- Have a look at the ProcessList
- **Notice that the oldest Process is the first entry instead of the 10th oldest.**
=> 🐛 Fix Order of Processes in ProcessList

src/modules/design/design.ts
1. Fix Opening Removed Open Diagrams
Closes #1876 
PR: #1880
- Open a diagram from a solution
- Open another diagram
- Remove the first opened diagram via the filesystem
- **Notice that the diagram can get opened via the solution explorer**
- **Notice that the removed diagram can get closed via the close button.**
=> 🐛 Fix Opening Removed Open Diagrams

src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.html, src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.scss, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.html, src/modules/design/property-panel/indextabs/general/sections/message-event/message-event.scss, src/modules/design/property-panel/indextabs/general/sections/pool/pool.scss, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.html, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.html, src/modules/design/property-panel/indextabs/general/sections/signal-event/signal-event.scss, src/modules/design/property-panel/styles/sections.scss
1. Remove Outline from 'props-input-textarea'
2. Unify Style of Textareas
3. Adjust Style of Property Inputs
4. Improve Readability
5. Remove Unneeded CSS
6. Adjust Style of Inputs with Datalist
7. Remove Unneeded Newlines
8. Improve Style of Navigate Button
9. Add Spacing Between Property Name & Value
PR: #1874
- Have a look at the property panel
=> 💄 Harmonize Style of PropertyPanel Elements

src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.ts
1. Use ProcessId Instead of Diagram Name for `Process` Input of CallActivities
2. Improve `Process ID` Input Label
Closes #1855 
PR: #1865
- Open a diagram with a CallActivity
- Click on the CallActivity
- Select a `called process` via the `Process ID` Input
- **Notice that the list includes the Process IDs instead of the filenames**
- **Notice that one can filter the Process IDs via the filenames by entering `Filename: `**
=> 🐛 Fix `Process` Input of Call Activities

aurelia_project/environments/dev.ts, src/modules/config-panel/config-panel.html, src/modules/config-panel/config-panel.ts
1. Remove Useless Default Authority Input Information
Closes #1883 
PR: #1885
- Go to the Config Panel of the internal Remote Solution
- Change the authority
- **Notice that no info box will appear.**
=> 🔥 Remove Useless Default Authority Input Information

src/modules/inspect/process-list/process-list.html, src/modules/inspect/process-list/process-list.scss, src/modules/inspect/process-list/process-list.ts
1. Set Constant Width for Last Table Column
2. Display Amount of Active ProcessInstances as Total Amount
Closes #1773 
PR: #1897
- Go to the Dashboard view
- Stop some processes
- **Notice that the 'Total' count will decrease.**
- Stop all processes on one page
- **Notice that the last column will keep its width.**
=> 💄 Improve displaying stopped processes

src/app.scss, src/modules/design/bpmn-io/bpmn-io.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.scss, src/modules/inspect/inspect.scss, src/modules/live-execution-tracker/live-execution-tracker.scss, src/modules/navbar/navbar.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss
1. Use Same Cursor Style for Icon Buttons
Closes #1893 
PR: #1895
- Hover over some icon buttons
- **Notice that the cursor should always look like this: <img width="40" alt="cursor-pointer" src="https://user-images.githubusercontent.com/20394992/70516996-32a4c880-1b38-11ea-992b-d010ffe3eb38.png">**
> For some reason, it is impossible to specify a cursor style for buttons in the navigation bar.
> This is caused by moving the electron title bar into the  BPMN Studio.
=> 💄Use Same Cursor Style for Icon Buttons

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
1.  Make Open Remote Solution Modal Protocol Sensitive
Closes #1756 
PR: #1896
- Open the 'Open Remote Solution Modal'
- Enter 'https://example.com' in the location text field
- **Notice that the 'https://' will disappear and the protocol dropdown will change to 'https://'**
- Enter 'http://example.com' in the location text field
- **Notice that the 'http://' will disappear and the protocol dropdown will change to 'http://'**
=> ✨ Make Open Remote Solution Modal Protocol Sensitive for Supported Protocols

src/modules/design/property-panel/indextabs/forms/forms.ts
> For some reason, the activate function of the form section is called one more time after detaching the form section. For this reason, an error was triggered which destroyed the PropertyPanel. This seems to be an issue with aurelia-templating-ressources.
> This fixes the updating of the PropertyPanel.
1. Fix Switching from UserTask to Another Element
PR: #1899
- Open any diagram with a UserTask
- Select the UserTask
- Select another Element
- **Notice that the PropertyPanel gets Updated correctly.**
=>  🐛 Fix Switching from UserTask to Another Element

electron_app/electron.ts, src/modules/design/design.ts
1. Add 'Export As' to Menubar
PR: #1898
- Open any diagram
- Use the menubar to export the diagram
- **Notice that the diagram can get exported as BPMN, SVG, PNG & JPEG via the menubar.**
=> ✨ Add 'Export As' to Menubar

.github/workflows/continuous-integration-workflow.yml
> This prevents GitHub Actions from publishing branches that only contain the word `master`, `develop` or `beta`, like `feature/develop_feature_xy` or `release/v5.11.0-beta.1`
1.  Fix Github Actions Workflow Conditions
PR: #1900
=> 🐛 Fix GitHub Actions Workflow Conditions

src/app.html, src/app.scss, src/app.ts, src/electron.scss, src/modules/config-panel/config-panel.scss, src/modules/design/bpmn-io/bpmn-io.scss, src/modules/design/design.scss, src/modules/design/diagram-tools-right/diagram-tools-right.scss, src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.scss, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.scss, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.scss, src/modules/design/property-panel/styles/sections.scss, src/modules/feedback-modal/feedback-modal.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.scss, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.scss, src/modules/inspect/inspect.scss, src/modules/inspect/token-viewer/token-viewer.scss, src/modules/live-execution-tracker/live-execution-tracker.scss, src/modules/navbar/navbar.scss, src/modules/pagination/pagination.scss, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss, src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss, src/modules/start-page/start-page.scss, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.scss, src/modules/think/diagram-list/diagram-list.scss
1. Undo Previous Cursor Style Changes
2. Remove Unused CSS Classes
3. Remove No Longer Needed Cursor Styles
4. Add Stylesheet for Electron
5. Avoid Using Pointer Style
PR: #1901
- Hover over any icon buttons you can find
- **Notice that the cursor should always look like the default cursor.**
=> ♻️ Refactor Cursor Styles

electron_app/electron.ts
1. Add BPMN Element Documentation to Menubar
PR: #1902
- Click on the `Help` button in the menubar
- Click on `BPMN Element Documentation`
- **Notice that the BPMN Element Documentation gets opened.**
=> ✨ Add BPMN Element Documentation to Menubar

electron_app/electron.ts, package.json, src/modules/status-bar/status-bar.html, src/modules/status-bar/status-bar.ts
1.  Show Update Dropdown When Notification was Clicked
Closes #1788 
PR: #1911
- `gco 711360d`
- Click on the update notification
- **Notice that the update modal is displayed.**
- Reload
- Click on the BPMN Studio icon in the statusbar (open the update modal)
- Click on the update notification
- **Note that the update modal is still displayed.**
=> ✨ Show Update Dropdown When Notification was Clicked

electron_app/electron.ts, src/contracts/feedback/FeedbackData.ts, src/modules/feedback-modal/feedback-modal.html, src/modules/feedback-modal/feedback-modal.ts
1. Harmonize Function Names
2. Adjust Adding Files And Folders to Zip
3. Improve Variable Naming
4. Add InternalProcessEngine Logs to Feedback Modal
5.  Improve Folder Structure of Feedback Zip
Closes #1913 
PR: #1919
- Open the feedback modal
- Fill some input fields
- Check the checkbox about PE logs
- Save the feedback.zip somewhere
- Extract the feedback.zip
- **Notice that the feedback.zip includes the logs of the InternalProcesEngine.**
=> ✨ Add InternalProcessEngine Logs to Feedback Modal

electron_app/electron-oidc.ts, electron_app/electron.ts, src/contracts/authentication/IAuthenticationService.ts, src/contracts/authentication/ITokenObject.ts, src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts, src/services/authentication-service/electron.oidc-authentication-service.ts, src/services/authentication-service/web.oidc-authentication-service.ts
1. Refresh Access Tokens via Silent Refresh in Electron
Closes #1831
PR: #1916
- Start your identity server
- Navigate to your identity server using your browser (`http://localhost:5000/`)
- Click on `Click here to manage your users and IdentityServer configuration.`
- Go to Clients
- Select `BPMN Studio` from the list
- Go to `Advanced`
- Set `ACCESS TOKEN LIFETIME (SECONDS)` to 20
- Log in to any PE using that identity server
- Open up the developer console
- Go to the `Network` tab
- Click on any request
- Try to remember the last characters of the authorization token
- Wait >10 seconds
- Click on a new request
- **Notice that the authorization token changed.**
- Open another version of BPMN Studio (e.g. stable) & log in to any PE using the same authority  & wait until the process …
=> ✨ Refresh Access Tokens (Electron)

electron_app/electron.ts
1.  Fix Starting Runtime on Windows
PR: #1928
- Build the BPMN Studio on windows
- Install the BPMN Studio
- Run the BPMN Studio
- **Notice that the Runtime has started successfully.**
- Do the same on macOS
- Run the BPMN Studio via `npm run electron-start-dev`
- **Notice that the Runtime has started successfully.**
=> 🐛 Fix Starting Runtime on Windows

src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.html, src/modules/inspect/inspect-correlation/components/inspect-panel/components/process-instance-list/process-instance-list.ts, src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.html, src/modules/inspect/inspect-correlation/inspect-correlation.html, src/modules/inspect/inspect-correlation/inspect-correlation.ts, src/modules/inspect/inspect.ts, src/modules/task-dynamic-ui/task-dynamic-ui.ts
1. Fix Selecting Correlation After Navigating to InspectProcessInstance via LET 'Bug' Overlay
2. Avoid 'Cannot set property 'currentUserTask' of null' Error Message
Closes #1922
PR: #1923
- Run a process that runs into an error
- Click on the 'Bug' overlay (<img src="https://user-images.githubusercontent.com/20394992/72264724-7b5e0e80-361b-11ea-8d67-6e91dab07123.png" width="20px">)
- **Notice that the Inspect Correlation view gets displayed and the Log Viewer is opened.**
- Click on the 'Process Instance List' tab
- **Notice that the currently selected ProcessInstance is marked with a border.**
- Click on the 'Correlation List' tab
- **Notice that the currently selected Correlation is marked with a border.**
=> 🐛 Fix Navigating to Inspect Process Instance via Let 'Bug' Overlay

electron_app/electron.ts, src/modules/status-bar/status-bar.ts
1. Log the error message to the console
2. Improve notification text and add a link to the GitHub release
Closes #1921 
PR: #1925 
- decrease the version in the package.json
- `npm run electron-build-macos`
- run the built app
- try to update the studio
=> ♻️Improve notification on update error

src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts
1. Avoid Changing ElementID on Type Change
Closes #1915 
PR: #1927
- Change the ID of the StartEvent
- Change the type of the StartEvent
- **Notice that the ID stays the same.**
=> 🐛 Avoid Changing ElementID on Type Change

src/services/authentication-service/web.oidc-authentication-service.ts
1. Refresh Access Tokens via Silent Refresh in Web
Closes #1831
PR: #1926
- Start your identity server
- Navigate to your identity server using your browser (`http://localhost:5000/`)
- Click on `Click here to manage your users and IdentityServer configuration.`
- Go to Clients
- Select `BPMN Studio` from the list
- Go to `Advanced`
- Set `ACCESS TOKEN LIFETIME (SECONDS)` to 20
- Log in to any PE using that identity server
- Open up the developer console
- Go to the `Network` tab
- Click on any request
- Try to remember the last characters of the authorization token
- Wait >20 seconds
- Click on a new request
- **Notice that the authorization token changed.**
- Open another version of BPMN Studio (e.g. stable) & log in to any PE using the same authority  & wait until the process models …
=> ✨ Refresh Access Tokens (Web)

src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts
1. Fix ID Validation
2. Consider Definition ID When Validating Element IDs
Closes #1931 
PR: #1932
- Create a new Diagram
- Copy the ID of the StartEvent
- Change the ID of the EndEvent to the ID of the StartEvent
- **Notice that a red border appears around the input field.**
- Try to change the ID of the EndEvent to 'Definition_1'
- **Notice that a red border appears around the input field.**
=> 🐛Fix ID Validation

electron_app/electron.ts
1. Fix Exporting Diagrams on Windows
Closes #1912 
PR: #1934
- Click on the export button (<img width="20px" src="https://user-images.githubusercontent.com/20394992/72507356-0883ac00-3844-11ea-870a-41fb6dfce119.png"/>)
- **Notice that only one dialog is opened.**
=> 🐛 Fix Exporting Diagrams on Windows

aurelia_project/aurelia.json, package-lock.json, package.json, src/modules/design/bpmn-io/repositories/diagram-export.repository.ts, src/services/download-service/download.service.ts
1. Remove DownloadJS
2. Create Download Service Based on DownloadJS
3. Fix Exporting Diagrams with Umlauts
Closes #1755 
PR: #1935
- Export any diagram containing umlauts
- Open the exported diagram
- **Notice that the umlauts still exist.**
=> 🐛 Fix Umlauts in Exported Files

src/modules/design/property-panel/indextabs/general/sections/basics/basics.ts
1. Prevent IDs That Contain Spaces
Related #1943 
PR: #1944
- Open any diagram
- Select any element
- Try to add spaces to the element id
=> 🐛 Prevent IDs That Contain Spaces

src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.html, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts
1. Add Description for Error Events
Closes #1933 
PR: #1950
- Open any diagram
- Add an error-event
- Select an error
- **Notice that the input fields of the error event configuration have descriptions.**
=> ✨ Add Description for Error Events

src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts
1.  Fix the empty error message input field
PR: #1952 
- add an error element to the diagram
- add an error
- fill the error message input field
- select another element
- select the previous selected error element
- see that the error message is displayed
=> 🐛 Fix the empty error message input field

src/modules/design/property-panel/styles/sections.scss
1. Fix Style of 'props-table' Headlines
Closes https://github.com/process-engine/bpmn-studio/pull/1950#issuecomment-578597683
PR: #1953
=> 💄 Fix Style of 'props-table' Headlines

src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts, src/services/solution-explorer-services/open-diagrams-solution-explorer.service.ts
1. Fix bug where unsaved changes are overwritten after open the diagram with file association
2. Fix bug where an already opened diagram gets opened although
PR: #1957 
- build the stable version of this branch
- open it to set the file association
- open a diagram
- close the studio
- open the same diagram with the command line
- see that the diagram is not opened twice in `Open Diagrams` solution
- make some changes to the diagram
- navigate/open another diagram
- open the changed diagram with the command line
- see that the studio opens the diagram
=> 🐛Fix open already opened diagrams with file association

src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/modules/think/diagram-list/diagram-list.html, src/modules/think/diagram-list/diagram-list.ts
1. Add diagram to Open Diagrams before navigating to it
2. Fix bug where the opened diagram does not get highlighted
Closes #1958
Closes #1956 
PR: #1962 
- open a local solution
- open the think view
- click on a diagram of the table
- see that it has been opened as `Open Diagrams`
- see that it is highlighted
=> 🐛Fix open and highlight diagram from think view

src/modules/inspect/dashboard/contracts/IDashboardRepository.ts, src/modules/inspect/dashboard/contracts/IDashboardService.ts, src/modules/inspect/dashboard/repositories/dashboard.repository.ts, src/modules/inspect/dashboard/services/dashboard.service.ts, src/modules/inspect/task-list/task-list.html, src/modules/inspect/task-list/task-list.scss, src/modules/inspect/task-list/task-list.ts
1. Add DynamicUI Modal to the Dashboard
2. Use the modal if the user is not authorized to see the correlation
Closes #1973 
PR: #1974 
- deploy and start a process with a user
- grant a second user the `can_read_process_model` and the lane name used before, as claims
- log in with the second user
- goto the inspect/dashboard view
- click on continue on the waiting task and finish it from the dashboard
=> 🐛Use dynamic ui on dashboard if the user is not authorized to see the correlation

src/services/diagram-creation-service/diagram-creation.service.ts
1. Use UUID for DefinitionID
Closes #1997 
PR: #1999
- Open up the XML View
- Have a look at the DefinitionId
- **Notice that the DefinitionId is a UUID.**
=> ♻️ Use UUID for DefintionId

src/services/authentication-service/electron.oidc-authentication-service.ts
1. Fix Refreshing ProcessModels After Logout
PR: #2004 
- Log in to the BPMN Studio with a user who does not has the permission to read process models
- Log out
- **Notice that the process models get displayed.**
=> 🐛 Fix Refreshing ProcessModels After Logout

.github/workflows/continuous-integration-workflow.yml
1. Remove windows portable build from pipeline
Closes #2021 
PR: #2023
=> 🔥Remove windows portable build from pipeline

src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.html, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.scss, src/modules/inspect/inspect-process-instance/components/inspect-panel/components/log-viewer/log-viewer.ts
1. Add an information modal for log entries
Closes #2010 
PR: #2027 
Open the log viewer for a process instance and click on the `Details` button
=> ✨Add log information modal

src/app.scss, src/main.ts, src/modules/config-panel/config-panel.html, src/modules/custom_elements/modal/index.ts, src/modules/custom_elements/modal/modal.html, src/modules/custom_elements/modal/modal.ts, src/modules/deploy-modals/deploy-modals.html, src/modules/design/design.html, src/modules/design/property-panel/indextabs/general/sections/basics/basics.html, src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.html, src/modules/design/property-panel/indextabs/general/sections/pool/pool.html, src/modules/design/property-panel/indextabs/general/sections/script-task/script-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/live-execution-tracker/live-execution-tracker.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/services/help-modal-service/help-modal-service.ts
1. Add focus CSS for btn-default
2. Use if bind instead of show bind on modals
3. Set the focus to the modal if it runs out of the modal
PR: #2030
=> ✨Hold focus in modals

aurelia_project/environments/dev.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.ts
1. Fix bug where the modeler canvas is broken when switching between diagrams if the XML view is open and subsequently open the detail/diagram view.
PR: #2034 
- open a diagrams detail view
- open the XML view
- choose another diagram
- open the diagrams detail view
- see that the diagram is shown correctly
=> 🐛Fix broken modeler canvas

src/services/help-modal-service/help-modal-service.ts
1. Fix copy text from modals
PR: #2035 
- open a helptext modal
- select text from the modal
- copy it with `cmd+c/ctrl+x`
=> 🐛Fix copy text from modals

package-lock.json, package.json, src/modules/design/property-panel/indextabs/general/sections/error-event/error-event.ts
1. Fix Handling ErrorMessges
PR: #2036
- Create a diagram with an ErrorBoundaryEvent
- Create a new error
- **Do not configure a message**
- **Notice that the ErrorBoundaryEvent works as it should.**
=> 🐛 Fix Handling ErrorMessges

src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.ts
1. Remove force option for setting viewer viewport
2. Fix publishing event to fit the viewport
Fixes this bug:
PR: #2052 
- try to reproduce the behavior on the gif above
=> 🐛Fix viewport when switching from a local diagram to a diagram on a remote solution

aurelia_project/environments/dev.ts, src/modules/design/bpmn-diff-view/bpmn-diff-view.ts, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.html, src/modules/design/design.ts, src/modules/design/property-panel/property-panel.ts, src/modules/inspect/heatmap/heatmap.ts, src/modules/live-execution-tracker/live-execution-tracker.ts, src/modules/live-execution-tracker/services/live-execution-tracker.service.ts, src/services/deploy-diagram-service/deploy-diagram.service.ts, src/services/xml-id-validation-module/xml-id-validation-module.ts
1. Add and use getValidXml function if a diagram contains invalid IDs.
2. Show "Incompatible Diagram" warning modal on the design view.
PR: #2053 
open a diagram with an incompatible ID e.g a whitespace character.
=> ✨Support not Qname valid diagrams

package-lock.json, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.scss
1. Make width of payload modal resizable
Closes #2049 
PR: #2059
- Create a diagram
- Add a ServiceTask
- Select 'External Task' as kind
- Click on the 'Enlarge' button of the payload field
- Resize the textarea
=> ✨ Make width of payload modal resizable

package.json, src/modules/design/bpmn-io/bpmn-io.ts, src/modules/design/design.html, src/modules/design/design.ts, src/services/xml-id-validation-module/xml-id-validation-module.ts
1. Call importXmlIntoModeler instead of modeler.importXML to handle illegal ID errors
2. Fix bug where the ID was not set at every reference
3. Fix bug where not all IDs were shown in the incompatible warning modal
PR: #2062 
try to import this diagram:
[22.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/5016026/22.bpmn.zip)
=> 🐛Fix xml id validation

src/modules/custom_elements/modal/modal.ts, src/modules/navbar/navbar.ts, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
1. Fix bug where the focus listener does not get removed
2. Fix bug where the diagram could be undefined and a bug where the method is called for wrong solutions
3. Fix bug where closeOpenDiagram is called for all solutions instead only for the open diagram solution
4. Use show bind and remove registering click handlers to handle the modal button clicks 
Fixes this bug:
PR: #2063
try to reproduce this video:
[Aug-03-2020 13-13-23.mp4.zip](https://github.com/process-engine/bpmn-studio/files/5016609/Aug-03-2020.13-13-23.mp4.zip)
=> 🐛 Fix maximum callstack size error

package.json, src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts, src/services/xml-id-validation-module/xml-id-validation-module.ts
1. Check if diagram name has invalid characters and replace them
Closes #2067 
PR: #2068 
try to reproduce the referenced issue
=> 🐛Fix bug where duplicating a diagram provides an invalid diagram name

src/modules/design/bpmn-io/bpmn-io.ts, src/services/xml-id-validation-module/xml-id-validation-module.ts
1. Fix bug where opening a diagram with an invalid definition ID does not work.
PR: #2091 
try to open e.g. this diagram:
[core_domain_retry_processinstance.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/5318039/core_domain_retry_processinstance.bpmn.zip)
=> 🐛 Fix opening diagrams with invalid definition id

package.json
1. Fix wrong package name while building the installer
PR: #2110 
=> 🐛 Fix wrong package name while building installer

.github/workflows/continuous-integration-workflow.yml, build/code-signing/mac/notarize.js, electron-builder/alpha/electron-builder.yml, electron-builder/beta/electron-builder.yml, electron-builder/stable/electron-builder.yml, package-lock.json, package.json
1. Notarize the macOS app after sign
Closes #1989 
PR: #2112 
Folgende Voraussetzungen müssen erfüllt sein:
- Xcode 10 oder neuer (`xcodebuild -version`)
- macOS 10.13.6 oder neuer (`sw_vers`)
```
export APPLE_USERNAME='...'
export APPLE_PASSWORD='...'
export CSC_LINK=<Pfad zum Apple-Developer-Zertifikat>
npm run electron-build-macos
```
Die benötigten Daten finden sich in 1Password im "ProcessEngine"-Tresor.
Zertifikat: [Apple Developer Certificate Electron](https://5minds.1password.com/vaults/nqsd7iar7qxpuy62ji4zskbz4e/allitems/mxnl26i2mczoe2xo4ekcdiiiby)
Apple-ID: [Apple-ID -- Jenkins](https://5minds.1password.com/vaults/nqsd7iar7qxpuy62ji4zskbz4e/allitems/zl754qdbbfepxdp6uybewrorl4)
Der Erfolg der Beglaubigung kann wie folgt geprüft werden:
```
codesign --test-requirement="=notarized" …
```
=> ✨ Notarize macOS builds

src/services/help-modal-service/help-texts/usertask-usage.ts
1. Fix wrong information about default values of date form fields 
Closes #2115 
PR: #2118
open the help text for user tasks
=> 🐛 Fix wrong information in help text

package-lock.json, package.json
Fixt ein Issue in der Engine, dass zu lange Pfade für ein Windows ohne Long-Path Option erzeugt hat.
Related to https://github.com/atlas-engine/AtlasEngine/pull/310
- BPMN Studio unter WIndows starten, bei deaktivierter "LongPath" Option
- Das Studio sollte starten
=> Hotfix: Zu Lange Pfade in den Engine Node Modules

package.json, src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.html, src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts
1. Erlaubt es alle Felder eines HTTP Service Tasks unabhängig von anderen Feldern zu setzen.
2. Setzt bei GET und DELETE Requests keinen Body, damit die Engine die zusammengefügten Parameter richtig parsen kann und somit auch Header für GET und DELETE nutzt. 
3. Fügt für POST und PUT einen leeren Body zu den Parametern hinzu, falls keiner angegeben ist. 
PR: #2127 
- Schauen ob bei GET und DELETE Requests die angegebenen Header auch im Request am Server ankommen
- Schauen dass man auch einen Header setzen kann, ohne vorher einen Body angeben zu müssen
=> Hotfix: Fix Request Headers on HTTP Service Task (GET, DELETE)
